// Code generated by ent, DO NOT EDIT.

package savedmessage

import (
	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/nekode/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldContainsFold(FieldID, id))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEQ(FieldTarget, v))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEQ(FieldMessageID, v))
}

// SavedByUserID applies equality check predicate on the "saved_by_user_id" field. It's identical to SavedByUserIDEQ.
func SavedByUserID(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEQ(FieldSavedByUserID, v))
}

// SavedByAgentID applies equality check predicate on the "saved_by_agent_id" field. It's identical to SavedByAgentIDEQ.
func SavedByAgentID(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEQ(FieldSavedByAgentID, v))
}

// CreatedUnix applies equality check predicate on the "created_unix" field. It's identical to CreatedUnixEQ.
func CreatedUnix(v int64) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEQ(FieldCreatedUnix, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldContainsFold(FieldTarget, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDGT applies the GT predicate on the "message_id" field.
func MessageIDGT(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldGT(FieldMessageID, v))
}

// MessageIDGTE applies the GTE predicate on the "message_id" field.
func MessageIDGTE(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldGTE(FieldMessageID, v))
}

// MessageIDLT applies the LT predicate on the "message_id" field.
func MessageIDLT(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldLT(FieldMessageID, v))
}

// MessageIDLTE applies the LTE predicate on the "message_id" field.
func MessageIDLTE(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldLTE(FieldMessageID, v))
}

// MessageIDContains applies the Contains predicate on the "message_id" field.
func MessageIDContains(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldContains(FieldMessageID, v))
}

// MessageIDHasPrefix applies the HasPrefix predicate on the "message_id" field.
func MessageIDHasPrefix(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldHasPrefix(FieldMessageID, v))
}

// MessageIDHasSuffix applies the HasSuffix predicate on the "message_id" field.
func MessageIDHasSuffix(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldHasSuffix(FieldMessageID, v))
}

// MessageIDEqualFold applies the EqualFold predicate on the "message_id" field.
func MessageIDEqualFold(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEqualFold(FieldMessageID, v))
}

// MessageIDContainsFold applies the ContainsFold predicate on the "message_id" field.
func MessageIDContainsFold(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldContainsFold(FieldMessageID, v))
}

// SavedByUserIDEQ applies the EQ predicate on the "saved_by_user_id" field.
func SavedByUserIDEQ(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEQ(FieldSavedByUserID, v))
}

// SavedByUserIDNEQ applies the NEQ predicate on the "saved_by_user_id" field.
func SavedByUserIDNEQ(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldNEQ(FieldSavedByUserID, v))
}

// SavedByUserIDIn applies the In predicate on the "saved_by_user_id" field.
func SavedByUserIDIn(vs ...string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldIn(FieldSavedByUserID, vs...))
}

// SavedByUserIDNotIn applies the NotIn predicate on the "saved_by_user_id" field.
func SavedByUserIDNotIn(vs ...string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldNotIn(FieldSavedByUserID, vs...))
}

// SavedByUserIDGT applies the GT predicate on the "saved_by_user_id" field.
func SavedByUserIDGT(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldGT(FieldSavedByUserID, v))
}

// SavedByUserIDGTE applies the GTE predicate on the "saved_by_user_id" field.
func SavedByUserIDGTE(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldGTE(FieldSavedByUserID, v))
}

// SavedByUserIDLT applies the LT predicate on the "saved_by_user_id" field.
func SavedByUserIDLT(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldLT(FieldSavedByUserID, v))
}

// SavedByUserIDLTE applies the LTE predicate on the "saved_by_user_id" field.
func SavedByUserIDLTE(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldLTE(FieldSavedByUserID, v))
}

// SavedByUserIDContains applies the Contains predicate on the "saved_by_user_id" field.
func SavedByUserIDContains(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldContains(FieldSavedByUserID, v))
}

// SavedByUserIDHasPrefix applies the HasPrefix predicate on the "saved_by_user_id" field.
func SavedByUserIDHasPrefix(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldHasPrefix(FieldSavedByUserID, v))
}

// SavedByUserIDHasSuffix applies the HasSuffix predicate on the "saved_by_user_id" field.
func SavedByUserIDHasSuffix(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldHasSuffix(FieldSavedByUserID, v))
}

// SavedByUserIDEqualFold applies the EqualFold predicate on the "saved_by_user_id" field.
func SavedByUserIDEqualFold(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEqualFold(FieldSavedByUserID, v))
}

// SavedByUserIDContainsFold applies the ContainsFold predicate on the "saved_by_user_id" field.
func SavedByUserIDContainsFold(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldContainsFold(FieldSavedByUserID, v))
}

// SavedByAgentIDEQ applies the EQ predicate on the "saved_by_agent_id" field.
func SavedByAgentIDEQ(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEQ(FieldSavedByAgentID, v))
}

// SavedByAgentIDNEQ applies the NEQ predicate on the "saved_by_agent_id" field.
func SavedByAgentIDNEQ(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldNEQ(FieldSavedByAgentID, v))
}

// SavedByAgentIDIn applies the In predicate on the "saved_by_agent_id" field.
func SavedByAgentIDIn(vs ...string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldIn(FieldSavedByAgentID, vs...))
}

// SavedByAgentIDNotIn applies the NotIn predicate on the "saved_by_agent_id" field.
func SavedByAgentIDNotIn(vs ...string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldNotIn(FieldSavedByAgentID, vs...))
}

// SavedByAgentIDGT applies the GT predicate on the "saved_by_agent_id" field.
func SavedByAgentIDGT(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldGT(FieldSavedByAgentID, v))
}

// SavedByAgentIDGTE applies the GTE predicate on the "saved_by_agent_id" field.
func SavedByAgentIDGTE(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldGTE(FieldSavedByAgentID, v))
}

// SavedByAgentIDLT applies the LT predicate on the "saved_by_agent_id" field.
func SavedByAgentIDLT(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldLT(FieldSavedByAgentID, v))
}

// SavedByAgentIDLTE applies the LTE predicate on the "saved_by_agent_id" field.
func SavedByAgentIDLTE(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldLTE(FieldSavedByAgentID, v))
}

// SavedByAgentIDContains applies the Contains predicate on the "saved_by_agent_id" field.
func SavedByAgentIDContains(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldContains(FieldSavedByAgentID, v))
}

// SavedByAgentIDHasPrefix applies the HasPrefix predicate on the "saved_by_agent_id" field.
func SavedByAgentIDHasPrefix(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldHasPrefix(FieldSavedByAgentID, v))
}

// SavedByAgentIDHasSuffix applies the HasSuffix predicate on the "saved_by_agent_id" field.
func SavedByAgentIDHasSuffix(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldHasSuffix(FieldSavedByAgentID, v))
}

// SavedByAgentIDEqualFold applies the EqualFold predicate on the "saved_by_agent_id" field.
func SavedByAgentIDEqualFold(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEqualFold(FieldSavedByAgentID, v))
}

// SavedByAgentIDContainsFold applies the ContainsFold predicate on the "saved_by_agent_id" field.
func SavedByAgentIDContainsFold(v string) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldContainsFold(FieldSavedByAgentID, v))
}

// CreatedUnixEQ applies the EQ predicate on the "created_unix" field.
func CreatedUnixEQ(v int64) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldEQ(FieldCreatedUnix, v))
}

// CreatedUnixNEQ applies the NEQ predicate on the "created_unix" field.
func CreatedUnixNEQ(v int64) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldNEQ(FieldCreatedUnix, v))
}

// CreatedUnixIn applies the In predicate on the "created_unix" field.
func CreatedUnixIn(vs ...int64) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldIn(FieldCreatedUnix, vs...))
}

// CreatedUnixNotIn applies the NotIn predicate on the "created_unix" field.
func CreatedUnixNotIn(vs ...int64) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldNotIn(FieldCreatedUnix, vs...))
}

// CreatedUnixGT applies the GT predicate on the "created_unix" field.
func CreatedUnixGT(v int64) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldGT(FieldCreatedUnix, v))
}

// CreatedUnixGTE applies the GTE predicate on the "created_unix" field.
func CreatedUnixGTE(v int64) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldGTE(FieldCreatedUnix, v))
}

// CreatedUnixLT applies the LT predicate on the "created_unix" field.
func CreatedUnixLT(v int64) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldLT(FieldCreatedUnix, v))
}

// CreatedUnixLTE applies the LTE predicate on the "created_unix" field.
func CreatedUnixLTE(v int64) predicate.SavedMessage {
	return predicate.SavedMessage(sql.FieldLTE(FieldCreatedUnix, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SavedMessage) predicate.SavedMessage {
	return predicate.SavedMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SavedMessage) predicate.SavedMessage {
	return predicate.SavedMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SavedMessage) predicate.SavedMessage {
	return predicate.SavedMessage(sql.NotPredicates(p))
}
