// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/nekode/internal/ent/agentrun"
)

// AgentRunCreate is the builder for creating a AgentRun entity.
type AgentRunCreate struct {
	config
	mutation *AgentRunMutation
	hooks    []Hook
}

// SetAgentID sets the "agent_id" field.
func (_c *AgentRunCreate) SetAgentID(v string) *AgentRunCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetComputerID sets the "computer_id" field.
func (_c *AgentRunCreate) SetComputerID(v string) *AgentRunCreate {
	_c.mutation.SetComputerID(v)
	return _c
}

// SetStartedUnix sets the "started_unix" field.
func (_c *AgentRunCreate) SetStartedUnix(v int64) *AgentRunCreate {
	_c.mutation.SetStartedUnix(v)
	return _c
}

// SetEndedUnix sets the "ended_unix" field.
func (_c *AgentRunCreate) SetEndedUnix(v int64) *AgentRunCreate {
	_c.mutation.SetEndedUnix(v)
	return _c
}

// SetNillableEndedUnix sets the "ended_unix" field if the given value is not nil.
func (_c *AgentRunCreate) SetNillableEndedUnix(v *int64) *AgentRunCreate {
	if v != nil {
		_c.SetEndedUnix(*v)
	}
	return _c
}

// SetExitCode sets the "exit_code" field.
func (_c *AgentRunCreate) SetExitCode(v int32) *AgentRunCreate {
	_c.mutation.SetExitCode(v)
	return _c
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (_c *AgentRunCreate) SetNillableExitCode(v *int32) *AgentRunCreate {
	if v != nil {
		_c.SetExitCode(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *AgentRunCreate) SetSummary(v string) *AgentRunCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *AgentRunCreate) SetNillableSummary(v *string) *AgentRunCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *AgentRunCreate) SetError(v string) *AgentRunCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *AgentRunCreate) SetNillableError(v *string) *AgentRunCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetEventCount sets the "event_count" field.
func (_c *AgentRunCreate) SetEventCount(v uint32) *AgentRunCreate {
	_c.mutation.SetEventCount(v)
	return _c
}

// SetNillableEventCount sets the "event_count" field if the given value is not nil.
func (_c *AgentRunCreate) SetNillableEventCount(v *uint32) *AgentRunCreate {
	if v != nil {
		_c.SetEventCount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentRunCreate) SetID(v string) *AgentRunCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AgentRunMutation object of the builder.
func (_c *AgentRunCreate) Mutation() *AgentRunMutation {
	return _c.mutation
}

// Save creates the AgentRun in the database.
func (_c *AgentRunCreate) Save(ctx context.Context) (*AgentRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentRunCreate) SaveX(ctx context.Context) *AgentRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentRunCreate) defaults() {
	if _, ok := _c.mutation.EndedUnix(); !ok {
		v := agentrun.DefaultEndedUnix
		_c.mutation.SetEndedUnix(v)
	}
	if _, ok := _c.mutation.ExitCode(); !ok {
		v := agentrun.DefaultExitCode
		_c.mutation.SetExitCode(v)
	}
	if _, ok := _c.mutation.Summary(); !ok {
		v := agentrun.DefaultSummary
		_c.mutation.SetSummary(v)
	}
	if _, ok := _c.mutation.Error(); !ok {
		v := agentrun.DefaultError
		_c.mutation.SetError(v)
	}
	if _, ok := _c.mutation.EventCount(); !ok {
		v := agentrun.DefaultEventCount
		_c.mutation.SetEventCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentRunCreate) check() error {
	if _, ok := _c.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "AgentRun.agent_id"`)}
	}
	if v, ok := _c.mutation.AgentID(); ok {
		if err := agentrun.AgentIDValidator(v); err != nil {
			return &ValidationError{Name: "agent_id", err: fmt.Errorf(`ent: validator failed for field "AgentRun.agent_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ComputerID(); !ok {
		return &ValidationError{Name: "computer_id", err: errors.New(`ent: missing required field "AgentRun.computer_id"`)}
	}
	if v, ok := _c.mutation.ComputerID(); ok {
		if err := agentrun.ComputerIDValidator(v); err != nil {
			return &ValidationError{Name: "computer_id", err: fmt.Errorf(`ent: validator failed for field "AgentRun.computer_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartedUnix(); !ok {
		return &ValidationError{Name: "started_unix", err: errors.New(`ent: missing required field "AgentRun.started_unix"`)}
	}
	if _, ok := _c.mutation.EndedUnix(); !ok {
		return &ValidationError{Name: "ended_unix", err: errors.New(`ent: missing required field "AgentRun.ended_unix"`)}
	}
	if _, ok := _c.mutation.ExitCode(); !ok {
		return &ValidationError{Name: "exit_code", err: errors.New(`ent: missing required field "AgentRun.exit_code"`)}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "AgentRun.summary"`)}
	}
	if _, ok := _c.mutation.Error(); !ok {
		return &ValidationError{Name: "error", err: errors.New(`ent: missing required field "AgentRun.error"`)}
	}
	if _, ok := _c.mutation.EventCount(); !ok {
		return &ValidationError{Name: "event_count", err: errors.New(`ent: missing required field "AgentRun.event_count"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := agentrun.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AgentRun.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AgentRunCreate) sqlSave(ctx context.Context) (*AgentRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AgentRun.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentRunCreate) createSpec() (*AgentRun, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentrun.Table, sqlgraph.NewFieldSpec(agentrun.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(agentrun.FieldAgentID, field.TypeString, value)
		_node.AgentID = value
	}
	if value, ok := _c.mutation.ComputerID(); ok {
		_spec.SetField(agentrun.FieldComputerID, field.TypeString, value)
		_node.ComputerID = value
	}
	if value, ok := _c.mutation.StartedUnix(); ok {
		_spec.SetField(agentrun.FieldStartedUnix, field.TypeInt64, value)
		_node.StartedUnix = value
	}
	if value, ok := _c.mutation.EndedUnix(); ok {
		_spec.SetField(agentrun.FieldEndedUnix, field.TypeInt64, value)
		_node.EndedUnix = value
	}
	if value, ok := _c.mutation.ExitCode(); ok {
		_spec.SetField(agentrun.FieldExitCode, field.TypeInt32, value)
		_node.ExitCode = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(agentrun.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(agentrun.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.EventCount(); ok {
		_spec.SetField(agentrun.FieldEventCount, field.TypeUint32, value)
		_node.EventCount = value
	}
	return _node, _spec
}

// AgentRunCreateBulk is the builder for creating many AgentRun entities in bulk.
type AgentRunCreateBulk struct {
	config
	err      error
	builders []*AgentRunCreate
}

// Save creates the AgentRun entities in the database.
func (_c *AgentRunCreateBulk) Save(ctx context.Context) ([]*AgentRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentRunCreateBulk) SaveX(ctx context.Context) []*AgentRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
