// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/nekode/internal/ent/channelmember"
)

// ChannelMember is the model entity for the ChannelMember schema.
type ChannelMember struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Target holds the value of the "target" field.
	Target string `json:"target,omitempty"`
	// MemberID holds the value of the "member_id" field.
	MemberID string `json:"member_id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// JoinedTimeUnix holds the value of the "joined_time_unix" field.
	JoinedTimeUnix int64 `json:"joined_time_unix,omitempty"`
	// UpdatedUnix holds the value of the "updated_unix" field.
	UpdatedUnix  int64 `json:"updated_unix,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelmember.FieldJoinedTimeUnix, channelmember.FieldUpdatedUnix:
			values[i] = new(sql.NullInt64)
		case channelmember.FieldID, channelmember.FieldTarget, channelmember.FieldMemberID, channelmember.FieldUsername, channelmember.FieldDisplayName, channelmember.FieldKind, channelmember.FieldRole:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelMember fields.
func (_m *ChannelMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelmember.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case channelmember.FieldTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target", values[i])
			} else if value.Valid {
				_m.Target = value.String
			}
		case channelmember.FieldMemberID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field member_id", values[i])
			} else if value.Valid {
				_m.MemberID = value.String
			}
		case channelmember.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case channelmember.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case channelmember.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case channelmember.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case channelmember.FieldJoinedTimeUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field joined_time_unix", values[i])
			} else if value.Valid {
				_m.JoinedTimeUnix = value.Int64
			}
		case channelmember.FieldUpdatedUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_unix", values[i])
			} else if value.Valid {
				_m.UpdatedUnix = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelMember.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ChannelMember.
// Note that you need to call ChannelMember.Unwrap() before calling this method if this ChannelMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelMember) Update() *ChannelMemberUpdateOne {
	return NewChannelMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelMember) Unwrap() *ChannelMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelMember) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("target=")
	builder.WriteString(_m.Target)
	builder.WriteString(", ")
	builder.WriteString("member_id=")
	builder.WriteString(_m.MemberID)
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("joined_time_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.JoinedTimeUnix))
	builder.WriteString(", ")
	builder.WriteString("updated_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedUnix))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelMembers is a parsable slice of ChannelMember.
type ChannelMembers []*ChannelMember
