// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/nekode/internal/ent/channeldecision"
)

// ChannelDecisionCreate is the builder for creating a ChannelDecision entity.
type ChannelDecisionCreate struct {
	config
	mutation *ChannelDecisionMutation
	hooks    []Hook
}

// SetTarget sets the "target" field.
func (_c *ChannelDecisionCreate) SetTarget(v string) *ChannelDecisionCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ChannelDecisionCreate) SetTitle(v string) *ChannelDecisionCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *ChannelDecisionCreate) SetBody(v string) *ChannelDecisionCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChannelDecisionCreate) SetStatus(v string) *ChannelDecisionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetProposerID sets the "proposer_id" field.
func (_c *ChannelDecisionCreate) SetProposerID(v string) *ChannelDecisionCreate {
	_c.mutation.SetProposerID(v)
	return _c
}

// SetProposerKind sets the "proposer_kind" field.
func (_c *ChannelDecisionCreate) SetProposerKind(v string) *ChannelDecisionCreate {
	_c.mutation.SetProposerKind(v)
	return _c
}

// SetCreatedUnix sets the "created_unix" field.
func (_c *ChannelDecisionCreate) SetCreatedUnix(v int64) *ChannelDecisionCreate {
	_c.mutation.SetCreatedUnix(v)
	return _c
}

// SetRatifiedUnix sets the "ratified_unix" field.
func (_c *ChannelDecisionCreate) SetRatifiedUnix(v int64) *ChannelDecisionCreate {
	_c.mutation.SetRatifiedUnix(v)
	return _c
}

// SetNillableRatifiedUnix sets the "ratified_unix" field if the given value is not nil.
func (_c *ChannelDecisionCreate) SetNillableRatifiedUnix(v *int64) *ChannelDecisionCreate {
	if v != nil {
		_c.SetRatifiedUnix(*v)
	}
	return _c
}

// SetRetiredUnix sets the "retired_unix" field.
func (_c *ChannelDecisionCreate) SetRetiredUnix(v int64) *ChannelDecisionCreate {
	_c.mutation.SetRetiredUnix(v)
	return _c
}

// SetNillableRetiredUnix sets the "retired_unix" field if the given value is not nil.
func (_c *ChannelDecisionCreate) SetNillableRetiredUnix(v *int64) *ChannelDecisionCreate {
	if v != nil {
		_c.SetRetiredUnix(*v)
	}
	return _c
}

// SetRetiredBy sets the "retired_by" field.
func (_c *ChannelDecisionCreate) SetRetiredBy(v string) *ChannelDecisionCreate {
	_c.mutation.SetRetiredBy(v)
	return _c
}

// SetNillableRetiredBy sets the "retired_by" field if the given value is not nil.
func (_c *ChannelDecisionCreate) SetNillableRetiredBy(v *string) *ChannelDecisionCreate {
	if v != nil {
		_c.SetRetiredBy(*v)
	}
	return _c
}

// SetRetireReason sets the "retire_reason" field.
func (_c *ChannelDecisionCreate) SetRetireReason(v string) *ChannelDecisionCreate {
	_c.mutation.SetRetireReason(v)
	return _c
}

// SetNillableRetireReason sets the "retire_reason" field if the given value is not nil.
func (_c *ChannelDecisionCreate) SetNillableRetireReason(v *string) *ChannelDecisionCreate {
	if v != nil {
		_c.SetRetireReason(*v)
	}
	return _c
}

// SetSupersedesDecisionID sets the "supersedes_decision_id" field.
func (_c *ChannelDecisionCreate) SetSupersedesDecisionID(v string) *ChannelDecisionCreate {
	_c.mutation.SetSupersedesDecisionID(v)
	return _c
}

// SetNillableSupersedesDecisionID sets the "supersedes_decision_id" field if the given value is not nil.
func (_c *ChannelDecisionCreate) SetNillableSupersedesDecisionID(v *string) *ChannelDecisionCreate {
	if v != nil {
		_c.SetSupersedesDecisionID(*v)
	}
	return _c
}

// SetApproveCount sets the "approve_count" field.
func (_c *ChannelDecisionCreate) SetApproveCount(v uint32) *ChannelDecisionCreate {
	_c.mutation.SetApproveCount(v)
	return _c
}

// SetNillableApproveCount sets the "approve_count" field if the given value is not nil.
func (_c *ChannelDecisionCreate) SetNillableApproveCount(v *uint32) *ChannelDecisionCreate {
	if v != nil {
		_c.SetApproveCount(*v)
	}
	return _c
}

// SetRejectCount sets the "reject_count" field.
func (_c *ChannelDecisionCreate) SetRejectCount(v uint32) *ChannelDecisionCreate {
	_c.mutation.SetRejectCount(v)
	return _c
}

// SetNillableRejectCount sets the "reject_count" field if the given value is not nil.
func (_c *ChannelDecisionCreate) SetNillableRejectCount(v *uint32) *ChannelDecisionCreate {
	if v != nil {
		_c.SetRejectCount(*v)
	}
	return _c
}

// SetAbstainCount sets the "abstain_count" field.
func (_c *ChannelDecisionCreate) SetAbstainCount(v uint32) *ChannelDecisionCreate {
	_c.mutation.SetAbstainCount(v)
	return _c
}

// SetNillableAbstainCount sets the "abstain_count" field if the given value is not nil.
func (_c *ChannelDecisionCreate) SetNillableAbstainCount(v *uint32) *ChannelDecisionCreate {
	if v != nil {
		_c.SetAbstainCount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChannelDecisionCreate) SetID(v string) *ChannelDecisionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChannelDecisionCreate) SetNillableID(v *string) *ChannelDecisionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ChannelDecisionMutation object of the builder.
func (_c *ChannelDecisionCreate) Mutation() *ChannelDecisionMutation {
	return _c.mutation
}

// Save creates the ChannelDecision in the database.
func (_c *ChannelDecisionCreate) Save(ctx context.Context) (*ChannelDecision, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelDecisionCreate) SaveX(ctx context.Context) *ChannelDecision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelDecisionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelDecisionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelDecisionCreate) defaults() {
	if _, ok := _c.mutation.RatifiedUnix(); !ok {
		v := channeldecision.DefaultRatifiedUnix
		_c.mutation.SetRatifiedUnix(v)
	}
	if _, ok := _c.mutation.RetiredUnix(); !ok {
		v := channeldecision.DefaultRetiredUnix
		_c.mutation.SetRetiredUnix(v)
	}
	if _, ok := _c.mutation.RetiredBy(); !ok {
		v := channeldecision.DefaultRetiredBy
		_c.mutation.SetRetiredBy(v)
	}
	if _, ok := _c.mutation.RetireReason(); !ok {
		v := channeldecision.DefaultRetireReason
		_c.mutation.SetRetireReason(v)
	}
	if _, ok := _c.mutation.SupersedesDecisionID(); !ok {
		v := channeldecision.DefaultSupersedesDecisionID
		_c.mutation.SetSupersedesDecisionID(v)
	}
	if _, ok := _c.mutation.ApproveCount(); !ok {
		v := channeldecision.DefaultApproveCount
		_c.mutation.SetApproveCount(v)
	}
	if _, ok := _c.mutation.RejectCount(); !ok {
		v := channeldecision.DefaultRejectCount
		_c.mutation.SetRejectCount(v)
	}
	if _, ok := _c.mutation.AbstainCount(); !ok {
		v := channeldecision.DefaultAbstainCount
		_c.mutation.SetAbstainCount(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := channeldecision.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelDecisionCreate) check() error {
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "ChannelDecision.target"`)}
	}
	if v, ok := _c.mutation.Target(); ok {
		if err := channeldecision.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "ChannelDecision.target": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ChannelDecision.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := channeldecision.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ChannelDecision.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "ChannelDecision.body"`)}
	}
	if v, ok := _c.mutation.Body(); ok {
		if err := channeldecision.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "ChannelDecision.body": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ChannelDecision.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := channeldecision.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChannelDecision.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProposerID(); !ok {
		return &ValidationError{Name: "proposer_id", err: errors.New(`ent: missing required field "ChannelDecision.proposer_id"`)}
	}
	if v, ok := _c.mutation.ProposerID(); ok {
		if err := channeldecision.ProposerIDValidator(v); err != nil {
			return &ValidationError{Name: "proposer_id", err: fmt.Errorf(`ent: validator failed for field "ChannelDecision.proposer_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProposerKind(); !ok {
		return &ValidationError{Name: "proposer_kind", err: errors.New(`ent: missing required field "ChannelDecision.proposer_kind"`)}
	}
	if v, ok := _c.mutation.ProposerKind(); ok {
		if err := channeldecision.ProposerKindValidator(v); err != nil {
			return &ValidationError{Name: "proposer_kind", err: fmt.Errorf(`ent: validator failed for field "ChannelDecision.proposer_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedUnix(); !ok {
		return &ValidationError{Name: "created_unix", err: errors.New(`ent: missing required field "ChannelDecision.created_unix"`)}
	}
	if _, ok := _c.mutation.RatifiedUnix(); !ok {
		return &ValidationError{Name: "ratified_unix", err: errors.New(`ent: missing required field "ChannelDecision.ratified_unix"`)}
	}
	if _, ok := _c.mutation.RetiredUnix(); !ok {
		return &ValidationError{Name: "retired_unix", err: errors.New(`ent: missing required field "ChannelDecision.retired_unix"`)}
	}
	if _, ok := _c.mutation.RetiredBy(); !ok {
		return &ValidationError{Name: "retired_by", err: errors.New(`ent: missing required field "ChannelDecision.retired_by"`)}
	}
	if _, ok := _c.mutation.RetireReason(); !ok {
		return &ValidationError{Name: "retire_reason", err: errors.New(`ent: missing required field "ChannelDecision.retire_reason"`)}
	}
	if _, ok := _c.mutation.SupersedesDecisionID(); !ok {
		return &ValidationError{Name: "supersedes_decision_id", err: errors.New(`ent: missing required field "ChannelDecision.supersedes_decision_id"`)}
	}
	if _, ok := _c.mutation.ApproveCount(); !ok {
		return &ValidationError{Name: "approve_count", err: errors.New(`ent: missing required field "ChannelDecision.approve_count"`)}
	}
	if _, ok := _c.mutation.RejectCount(); !ok {
		return &ValidationError{Name: "reject_count", err: errors.New(`ent: missing required field "ChannelDecision.reject_count"`)}
	}
	if _, ok := _c.mutation.AbstainCount(); !ok {
		return &ValidationError{Name: "abstain_count", err: errors.New(`ent: missing required field "ChannelDecision.abstain_count"`)}
	}
	return nil
}

func (_c *ChannelDecisionCreate) sqlSave(ctx context.Context) (*ChannelDecision, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ChannelDecision.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelDecisionCreate) createSpec() (*ChannelDecision, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelDecision{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channeldecision.Table, sqlgraph.NewFieldSpec(channeldecision.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(channeldecision.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(channeldecision.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(channeldecision.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(channeldecision.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProposerID(); ok {
		_spec.SetField(channeldecision.FieldProposerID, field.TypeString, value)
		_node.ProposerID = value
	}
	if value, ok := _c.mutation.ProposerKind(); ok {
		_spec.SetField(channeldecision.FieldProposerKind, field.TypeString, value)
		_node.ProposerKind = value
	}
	if value, ok := _c.mutation.CreatedUnix(); ok {
		_spec.SetField(channeldecision.FieldCreatedUnix, field.TypeInt64, value)
		_node.CreatedUnix = value
	}
	if value, ok := _c.mutation.RatifiedUnix(); ok {
		_spec.SetField(channeldecision.FieldRatifiedUnix, field.TypeInt64, value)
		_node.RatifiedUnix = value
	}
	if value, ok := _c.mutation.RetiredUnix(); ok {
		_spec.SetField(channeldecision.FieldRetiredUnix, field.TypeInt64, value)
		_node.RetiredUnix = value
	}
	if value, ok := _c.mutation.RetiredBy(); ok {
		_spec.SetField(channeldecision.FieldRetiredBy, field.TypeString, value)
		_node.RetiredBy = value
	}
	if value, ok := _c.mutation.RetireReason(); ok {
		_spec.SetField(channeldecision.FieldRetireReason, field.TypeString, value)
		_node.RetireReason = value
	}
	if value, ok := _c.mutation.SupersedesDecisionID(); ok {
		_spec.SetField(channeldecision.FieldSupersedesDecisionID, field.TypeString, value)
		_node.SupersedesDecisionID = value
	}
	if value, ok := _c.mutation.ApproveCount(); ok {
		_spec.SetField(channeldecision.FieldApproveCount, field.TypeUint32, value)
		_node.ApproveCount = value
	}
	if value, ok := _c.mutation.RejectCount(); ok {
		_spec.SetField(channeldecision.FieldRejectCount, field.TypeUint32, value)
		_node.RejectCount = value
	}
	if value, ok := _c.mutation.AbstainCount(); ok {
		_spec.SetField(channeldecision.FieldAbstainCount, field.TypeUint32, value)
		_node.AbstainCount = value
	}
	return _node, _spec
}

// ChannelDecisionCreateBulk is the builder for creating many ChannelDecision entities in bulk.
type ChannelDecisionCreateBulk struct {
	config
	err      error
	builders []*ChannelDecisionCreate
}

// Save creates the ChannelDecision entities in the database.
func (_c *ChannelDecisionCreateBulk) Save(ctx context.Context) ([]*ChannelDecision, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelDecision, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelDecisionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelDecisionCreateBulk) SaveX(ctx context.Context) []*ChannelDecision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelDecisionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelDecisionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
