// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/nekode/internal/ent/channeldecision"
)

// ChannelDecision is the model entity for the ChannelDecision schema.
type ChannelDecision struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Target holds the value of the "target" field.
	Target string `json:"target,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ProposerID holds the value of the "proposer_id" field.
	ProposerID string `json:"proposer_id,omitempty"`
	// ProposerKind holds the value of the "proposer_kind" field.
	ProposerKind string `json:"proposer_kind,omitempty"`
	// CreatedUnix holds the value of the "created_unix" field.
	CreatedUnix int64 `json:"created_unix,omitempty"`
	// RatifiedUnix holds the value of the "ratified_unix" field.
	RatifiedUnix int64 `json:"ratified_unix,omitempty"`
	// RetiredUnix holds the value of the "retired_unix" field.
	RetiredUnix int64 `json:"retired_unix,omitempty"`
	// RetiredBy holds the value of the "retired_by" field.
	RetiredBy string `json:"retired_by,omitempty"`
	// RetireReason holds the value of the "retire_reason" field.
	RetireReason string `json:"retire_reason,omitempty"`
	// SupersedesDecisionID holds the value of the "supersedes_decision_id" field.
	SupersedesDecisionID string `json:"supersedes_decision_id,omitempty"`
	// ApproveCount holds the value of the "approve_count" field.
	ApproveCount uint32 `json:"approve_count,omitempty"`
	// RejectCount holds the value of the "reject_count" field.
	RejectCount uint32 `json:"reject_count,omitempty"`
	// AbstainCount holds the value of the "abstain_count" field.
	AbstainCount uint32 `json:"abstain_count,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelDecision) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channeldecision.FieldCreatedUnix, channeldecision.FieldRatifiedUnix, channeldecision.FieldRetiredUnix, channeldecision.FieldApproveCount, channeldecision.FieldRejectCount, channeldecision.FieldAbstainCount:
			values[i] = new(sql.NullInt64)
		case channeldecision.FieldID, channeldecision.FieldTarget, channeldecision.FieldTitle, channeldecision.FieldBody, channeldecision.FieldStatus, channeldecision.FieldProposerID, channeldecision.FieldProposerKind, channeldecision.FieldRetiredBy, channeldecision.FieldRetireReason, channeldecision.FieldSupersedesDecisionID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelDecision fields.
func (_m *ChannelDecision) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channeldecision.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case channeldecision.FieldTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target", values[i])
			} else if value.Valid {
				_m.Target = value.String
			}
		case channeldecision.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case channeldecision.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case channeldecision.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case channeldecision.FieldProposerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field proposer_id", values[i])
			} else if value.Valid {
				_m.ProposerID = value.String
			}
		case channeldecision.FieldProposerKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field proposer_kind", values[i])
			} else if value.Valid {
				_m.ProposerKind = value.String
			}
		case channeldecision.FieldCreatedUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_unix", values[i])
			} else if value.Valid {
				_m.CreatedUnix = value.Int64
			}
		case channeldecision.FieldRatifiedUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ratified_unix", values[i])
			} else if value.Valid {
				_m.RatifiedUnix = value.Int64
			}
		case channeldecision.FieldRetiredUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retired_unix", values[i])
			} else if value.Valid {
				_m.RetiredUnix = value.Int64
			}
		case channeldecision.FieldRetiredBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field retired_by", values[i])
			} else if value.Valid {
				_m.RetiredBy = value.String
			}
		case channeldecision.FieldRetireReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field retire_reason", values[i])
			} else if value.Valid {
				_m.RetireReason = value.String
			}
		case channeldecision.FieldSupersedesDecisionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field supersedes_decision_id", values[i])
			} else if value.Valid {
				_m.SupersedesDecisionID = value.String
			}
		case channeldecision.FieldApproveCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field approve_count", values[i])
			} else if value.Valid {
				_m.ApproveCount = uint32(value.Int64)
			}
		case channeldecision.FieldRejectCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reject_count", values[i])
			} else if value.Valid {
				_m.RejectCount = uint32(value.Int64)
			}
		case channeldecision.FieldAbstainCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field abstain_count", values[i])
			} else if value.Valid {
				_m.AbstainCount = uint32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelDecision.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelDecision) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ChannelDecision.
// Note that you need to call ChannelDecision.Unwrap() before calling this method if this ChannelDecision
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelDecision) Update() *ChannelDecisionUpdateOne {
	return NewChannelDecisionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelDecision entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelDecision) Unwrap() *ChannelDecision {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelDecision is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelDecision) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelDecision(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("target=")
	builder.WriteString(_m.Target)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("proposer_id=")
	builder.WriteString(_m.ProposerID)
	builder.WriteString(", ")
	builder.WriteString("proposer_kind=")
	builder.WriteString(_m.ProposerKind)
	builder.WriteString(", ")
	builder.WriteString("created_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedUnix))
	builder.WriteString(", ")
	builder.WriteString("ratified_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.RatifiedUnix))
	builder.WriteString(", ")
	builder.WriteString("retired_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetiredUnix))
	builder.WriteString(", ")
	builder.WriteString("retired_by=")
	builder.WriteString(_m.RetiredBy)
	builder.WriteString(", ")
	builder.WriteString("retire_reason=")
	builder.WriteString(_m.RetireReason)
	builder.WriteString(", ")
	builder.WriteString("supersedes_decision_id=")
	builder.WriteString(_m.SupersedesDecisionID)
	builder.WriteString(", ")
	builder.WriteString("approve_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ApproveCount))
	builder.WriteString(", ")
	builder.WriteString("reject_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RejectCount))
	builder.WriteString(", ")
	builder.WriteString("abstain_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AbstainCount))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelDecisions is a parsable slice of ChannelDecision.
type ChannelDecisions []*ChannelDecision
