// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/nekode/internal/ent/idempotencyrecord"
)

// IdempotencyRecordCreate is the builder for creating a IdempotencyRecord entity.
type IdempotencyRecordCreate struct {
	config
	mutation *IdempotencyRecordMutation
	hooks    []Hook
}

// SetScope sets the "scope" field.
func (_c *IdempotencyRecordCreate) SetScope(v string) *IdempotencyRecordCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetMethod sets the "method" field.
func (_c *IdempotencyRecordCreate) SetMethod(v string) *IdempotencyRecordCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *IdempotencyRecordCreate) SetActorID(v string) *IdempotencyRecordCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableActorID(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetActorID(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *IdempotencyRecordCreate) SetIdempotencyKey(v string) *IdempotencyRecordCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetRequestHash sets the "request_hash" field.
func (_c *IdempotencyRecordCreate) SetRequestHash(v string) *IdempotencyRecordCreate {
	_c.mutation.SetRequestHash(v)
	return _c
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableRequestHash(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetRequestHash(*v)
	}
	return _c
}

// SetResponseType sets the "response_type" field.
func (_c *IdempotencyRecordCreate) SetResponseType(v string) *IdempotencyRecordCreate {
	_c.mutation.SetResponseType(v)
	return _c
}

// SetNillableResponseType sets the "response_type" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableResponseType(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetResponseType(*v)
	}
	return _c
}

// SetResponseJSON sets the "response_json" field.
func (_c *IdempotencyRecordCreate) SetResponseJSON(v string) *IdempotencyRecordCreate {
	_c.mutation.SetResponseJSON(v)
	return _c
}

// SetNillableResponseJSON sets the "response_json" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableResponseJSON(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetResponseJSON(*v)
	}
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *IdempotencyRecordCreate) SetResourceType(v string) *IdempotencyRecordCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableResourceType(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetResourceType(*v)
	}
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *IdempotencyRecordCreate) SetResourceID(v string) *IdempotencyRecordCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableResourceID(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetResourceID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *IdempotencyRecordCreate) SetStatus(v string) *IdempotencyRecordCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableStatus(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedUnix sets the "created_unix" field.
func (_c *IdempotencyRecordCreate) SetCreatedUnix(v int64) *IdempotencyRecordCreate {
	_c.mutation.SetCreatedUnix(v)
	return _c
}

// SetExpiresUnix sets the "expires_unix" field.
func (_c *IdempotencyRecordCreate) SetExpiresUnix(v int64) *IdempotencyRecordCreate {
	_c.mutation.SetExpiresUnix(v)
	return _c
}

// SetID sets the "id" field.
func (_c *IdempotencyRecordCreate) SetID(v string) *IdempotencyRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *IdempotencyRecordCreate) SetNillableID(v *string) *IdempotencyRecordCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the IdempotencyRecordMutation object of the builder.
func (_c *IdempotencyRecordCreate) Mutation() *IdempotencyRecordMutation {
	return _c.mutation
}

// Save creates the IdempotencyRecord in the database.
func (_c *IdempotencyRecordCreate) Save(ctx context.Context) (*IdempotencyRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IdempotencyRecordCreate) SaveX(ctx context.Context) *IdempotencyRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdempotencyRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdempotencyRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IdempotencyRecordCreate) defaults() {
	if _, ok := _c.mutation.ActorID(); !ok {
		v := idempotencyrecord.DefaultActorID
		_c.mutation.SetActorID(v)
	}
	if _, ok := _c.mutation.RequestHash(); !ok {
		v := idempotencyrecord.DefaultRequestHash
		_c.mutation.SetRequestHash(v)
	}
	if _, ok := _c.mutation.ResponseType(); !ok {
		v := idempotencyrecord.DefaultResponseType
		_c.mutation.SetResponseType(v)
	}
	if _, ok := _c.mutation.ResponseJSON(); !ok {
		v := idempotencyrecord.DefaultResponseJSON
		_c.mutation.SetResponseJSON(v)
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		v := idempotencyrecord.DefaultResourceType
		_c.mutation.SetResourceType(v)
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		v := idempotencyrecord.DefaultResourceID
		_c.mutation.SetResourceID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := idempotencyrecord.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := idempotencyrecord.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IdempotencyRecordCreate) check() error {
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "IdempotencyRecord.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := idempotencyrecord.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "IdempotencyRecord.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "IdempotencyRecord.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := idempotencyrecord.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "IdempotencyRecord.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`ent: missing required field "IdempotencyRecord.actor_id"`)}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "IdempotencyRecord.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := idempotencyrecord.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "IdempotencyRecord.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestHash(); !ok {
		return &ValidationError{Name: "request_hash", err: errors.New(`ent: missing required field "IdempotencyRecord.request_hash"`)}
	}
	if _, ok := _c.mutation.ResponseType(); !ok {
		return &ValidationError{Name: "response_type", err: errors.New(`ent: missing required field "IdempotencyRecord.response_type"`)}
	}
	if _, ok := _c.mutation.ResponseJSON(); !ok {
		return &ValidationError{Name: "response_json", err: errors.New(`ent: missing required field "IdempotencyRecord.response_json"`)}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "IdempotencyRecord.resource_type"`)}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "IdempotencyRecord.resource_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IdempotencyRecord.status"`)}
	}
	if _, ok := _c.mutation.CreatedUnix(); !ok {
		return &ValidationError{Name: "created_unix", err: errors.New(`ent: missing required field "IdempotencyRecord.created_unix"`)}
	}
	if _, ok := _c.mutation.ExpiresUnix(); !ok {
		return &ValidationError{Name: "expires_unix", err: errors.New(`ent: missing required field "IdempotencyRecord.expires_unix"`)}
	}
	return nil
}

func (_c *IdempotencyRecordCreate) sqlSave(ctx context.Context) (*IdempotencyRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected IdempotencyRecord.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IdempotencyRecordCreate) createSpec() (*IdempotencyRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &IdempotencyRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(idempotencyrecord.Table, sqlgraph.NewFieldSpec(idempotencyrecord.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(idempotencyrecord.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(idempotencyrecord.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(idempotencyrecord.FieldActorID, field.TypeString, value)
		_node.ActorID = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(idempotencyrecord.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.RequestHash(); ok {
		_spec.SetField(idempotencyrecord.FieldRequestHash, field.TypeString, value)
		_node.RequestHash = value
	}
	if value, ok := _c.mutation.ResponseType(); ok {
		_spec.SetField(idempotencyrecord.FieldResponseType, field.TypeString, value)
		_node.ResponseType = value
	}
	if value, ok := _c.mutation.ResponseJSON(); ok {
		_spec.SetField(idempotencyrecord.FieldResponseJSON, field.TypeString, value)
		_node.ResponseJSON = value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(idempotencyrecord.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(idempotencyrecord.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(idempotencyrecord.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedUnix(); ok {
		_spec.SetField(idempotencyrecord.FieldCreatedUnix, field.TypeInt64, value)
		_node.CreatedUnix = value
	}
	if value, ok := _c.mutation.ExpiresUnix(); ok {
		_spec.SetField(idempotencyrecord.FieldExpiresUnix, field.TypeInt64, value)
		_node.ExpiresUnix = value
	}
	return _node, _spec
}

// IdempotencyRecordCreateBulk is the builder for creating many IdempotencyRecord entities in bulk.
type IdempotencyRecordCreateBulk struct {
	config
	err      error
	builders []*IdempotencyRecordCreate
}

// Save creates the IdempotencyRecord entities in the database.
func (_c *IdempotencyRecordCreateBulk) Save(ctx context.Context) ([]*IdempotencyRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IdempotencyRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IdempotencyRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IdempotencyRecordCreateBulk) SaveX(ctx context.Context) []*IdempotencyRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdempotencyRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdempotencyRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
