// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/nekode/internal/ent/imchatsubscription"
)

// IMChatSubscription is the model entity for the IMChatSubscription schema.
type IMChatSubscription struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// EndpointID holds the value of the "endpoint_id" field.
	EndpointID string `json:"endpoint_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// ConversationID holds the value of the "conversation_id" field.
	ConversationID string `json:"conversation_id,omitempty"`
	// ExternalThreadID holds the value of the "external_thread_id" field.
	ExternalThreadID string `json:"external_thread_id,omitempty"`
	// ChatTitle holds the value of the "chat_title" field.
	ChatTitle string `json:"chat_title,omitempty"`
	// Target holds the value of the "target" field.
	Target string `json:"target,omitempty"`
	// ThreadID holds the value of the "thread_id" field.
	ThreadID string `json:"thread_id,omitempty"`
	// SenderExternalID holds the value of the "sender_external_id" field.
	SenderExternalID string `json:"sender_external_id,omitempty"`
	// AuthorizedByRequestID holds the value of the "authorized_by_request_id" field.
	AuthorizedByRequestID string `json:"authorized_by_request_id,omitempty"`
	// Subscribed holds the value of the "subscribed" field.
	Subscribed bool `json:"subscribed,omitempty"`
	// Verbose holds the value of the "verbose" field.
	Verbose bool `json:"verbose,omitempty"`
	// AuthorizedUnix holds the value of the "authorized_unix" field.
	AuthorizedUnix int64 `json:"authorized_unix,omitempty"`
	// SubscribedUnix holds the value of the "subscribed_unix" field.
	SubscribedUnix int64 `json:"subscribed_unix,omitempty"`
	// CreatedUnix holds the value of the "created_unix" field.
	CreatedUnix int64 `json:"created_unix,omitempty"`
	// UpdatedUnix holds the value of the "updated_unix" field.
	UpdatedUnix  int64 `json:"updated_unix,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IMChatSubscription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imchatsubscription.FieldSubscribed, imchatsubscription.FieldVerbose:
			values[i] = new(sql.NullBool)
		case imchatsubscription.FieldAuthorizedUnix, imchatsubscription.FieldSubscribedUnix, imchatsubscription.FieldCreatedUnix, imchatsubscription.FieldUpdatedUnix:
			values[i] = new(sql.NullInt64)
		case imchatsubscription.FieldID, imchatsubscription.FieldEndpointID, imchatsubscription.FieldProvider, imchatsubscription.FieldConversationID, imchatsubscription.FieldExternalThreadID, imchatsubscription.FieldChatTitle, imchatsubscription.FieldTarget, imchatsubscription.FieldThreadID, imchatsubscription.FieldSenderExternalID, imchatsubscription.FieldAuthorizedByRequestID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IMChatSubscription fields.
func (_m *IMChatSubscription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imchatsubscription.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case imchatsubscription.FieldEndpointID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint_id", values[i])
			} else if value.Valid {
				_m.EndpointID = value.String
			}
		case imchatsubscription.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case imchatsubscription.FieldConversationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field conversation_id", values[i])
			} else if value.Valid {
				_m.ConversationID = value.String
			}
		case imchatsubscription.FieldExternalThreadID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_thread_id", values[i])
			} else if value.Valid {
				_m.ExternalThreadID = value.String
			}
		case imchatsubscription.FieldChatTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chat_title", values[i])
			} else if value.Valid {
				_m.ChatTitle = value.String
			}
		case imchatsubscription.FieldTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target", values[i])
			} else if value.Valid {
				_m.Target = value.String
			}
		case imchatsubscription.FieldThreadID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field thread_id", values[i])
			} else if value.Valid {
				_m.ThreadID = value.String
			}
		case imchatsubscription.FieldSenderExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_external_id", values[i])
			} else if value.Valid {
				_m.SenderExternalID = value.String
			}
		case imchatsubscription.FieldAuthorizedByRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field authorized_by_request_id", values[i])
			} else if value.Valid {
				_m.AuthorizedByRequestID = value.String
			}
		case imchatsubscription.FieldSubscribed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field subscribed", values[i])
			} else if value.Valid {
				_m.Subscribed = value.Bool
			}
		case imchatsubscription.FieldVerbose:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field verbose", values[i])
			} else if value.Valid {
				_m.Verbose = value.Bool
			}
		case imchatsubscription.FieldAuthorizedUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field authorized_unix", values[i])
			} else if value.Valid {
				_m.AuthorizedUnix = value.Int64
			}
		case imchatsubscription.FieldSubscribedUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscribed_unix", values[i])
			} else if value.Valid {
				_m.SubscribedUnix = value.Int64
			}
		case imchatsubscription.FieldCreatedUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_unix", values[i])
			} else if value.Valid {
				_m.CreatedUnix = value.Int64
			}
		case imchatsubscription.FieldUpdatedUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_unix", values[i])
			} else if value.Valid {
				_m.UpdatedUnix = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IMChatSubscription.
// This includes values selected through modifiers, order, etc.
func (_m *IMChatSubscription) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IMChatSubscription.
// Note that you need to call IMChatSubscription.Unwrap() before calling this method if this IMChatSubscription
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IMChatSubscription) Update() *IMChatSubscriptionUpdateOne {
	return NewIMChatSubscriptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IMChatSubscription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IMChatSubscription) Unwrap() *IMChatSubscription {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IMChatSubscription is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IMChatSubscription) String() string {
	var builder strings.Builder
	builder.WriteString("IMChatSubscription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("endpoint_id=")
	builder.WriteString(_m.EndpointID)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("conversation_id=")
	builder.WriteString(_m.ConversationID)
	builder.WriteString(", ")
	builder.WriteString("external_thread_id=")
	builder.WriteString(_m.ExternalThreadID)
	builder.WriteString(", ")
	builder.WriteString("chat_title=")
	builder.WriteString(_m.ChatTitle)
	builder.WriteString(", ")
	builder.WriteString("target=")
	builder.WriteString(_m.Target)
	builder.WriteString(", ")
	builder.WriteString("thread_id=")
	builder.WriteString(_m.ThreadID)
	builder.WriteString(", ")
	builder.WriteString("sender_external_id=")
	builder.WriteString(_m.SenderExternalID)
	builder.WriteString(", ")
	builder.WriteString("authorized_by_request_id=")
	builder.WriteString(_m.AuthorizedByRequestID)
	builder.WriteString(", ")
	builder.WriteString("subscribed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Subscribed))
	builder.WriteString(", ")
	builder.WriteString("verbose=")
	builder.WriteString(fmt.Sprintf("%v", _m.Verbose))
	builder.WriteString(", ")
	builder.WriteString("authorized_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthorizedUnix))
	builder.WriteString(", ")
	builder.WriteString("subscribed_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscribedUnix))
	builder.WriteString(", ")
	builder.WriteString("created_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedUnix))
	builder.WriteString(", ")
	builder.WriteString("updated_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedUnix))
	builder.WriteByte(')')
	return builder.String()
}

// IMChatSubscriptions is a parsable slice of IMChatSubscription.
type IMChatSubscriptions []*IMChatSubscription
