// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/nekode/internal/ent/imchatauthrequest"
)

// IMChatAuthRequest is the model entity for the IMChatAuthRequest schema.
type IMChatAuthRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// EndpointID holds the value of the "endpoint_id" field.
	EndpointID string `json:"endpoint_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// ConversationID holds the value of the "conversation_id" field.
	ConversationID string `json:"conversation_id,omitempty"`
	// ExternalThreadID holds the value of the "external_thread_id" field.
	ExternalThreadID string `json:"external_thread_id,omitempty"`
	// ChatTitle holds the value of the "chat_title" field.
	ChatTitle string `json:"chat_title,omitempty"`
	// SenderExternalID holds the value of the "sender_external_id" field.
	SenderExternalID string `json:"sender_external_id,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash string `json:"token_hash,omitempty"`
	// TokenPrefix holds the value of the "token_prefix" field.
	TokenPrefix string `json:"token_prefix,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// RequestedTarget holds the value of the "requested_target" field.
	RequestedTarget string `json:"requested_target,omitempty"`
	// RequestedThreadID holds the value of the "requested_thread_id" field.
	RequestedThreadID string `json:"requested_thread_id,omitempty"`
	// ExpiresUnix holds the value of the "expires_unix" field.
	ExpiresUnix int64 `json:"expires_unix,omitempty"`
	// ResolvedByUserID holds the value of the "resolved_by_user_id" field.
	ResolvedByUserID string `json:"resolved_by_user_id,omitempty"`
	// ResolvedUnix holds the value of the "resolved_unix" field.
	ResolvedUnix int64 `json:"resolved_unix,omitempty"`
	// CreatedUnix holds the value of the "created_unix" field.
	CreatedUnix int64 `json:"created_unix,omitempty"`
	// UpdatedUnix holds the value of the "updated_unix" field.
	UpdatedUnix  int64 `json:"updated_unix,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IMChatAuthRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imchatauthrequest.FieldExpiresUnix, imchatauthrequest.FieldResolvedUnix, imchatauthrequest.FieldCreatedUnix, imchatauthrequest.FieldUpdatedUnix:
			values[i] = new(sql.NullInt64)
		case imchatauthrequest.FieldID, imchatauthrequest.FieldEndpointID, imchatauthrequest.FieldProvider, imchatauthrequest.FieldConversationID, imchatauthrequest.FieldExternalThreadID, imchatauthrequest.FieldChatTitle, imchatauthrequest.FieldSenderExternalID, imchatauthrequest.FieldTokenHash, imchatauthrequest.FieldTokenPrefix, imchatauthrequest.FieldStatus, imchatauthrequest.FieldRequestedTarget, imchatauthrequest.FieldRequestedThreadID, imchatauthrequest.FieldResolvedByUserID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IMChatAuthRequest fields.
func (_m *IMChatAuthRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imchatauthrequest.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case imchatauthrequest.FieldEndpointID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint_id", values[i])
			} else if value.Valid {
				_m.EndpointID = value.String
			}
		case imchatauthrequest.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case imchatauthrequest.FieldConversationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field conversation_id", values[i])
			} else if value.Valid {
				_m.ConversationID = value.String
			}
		case imchatauthrequest.FieldExternalThreadID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_thread_id", values[i])
			} else if value.Valid {
				_m.ExternalThreadID = value.String
			}
		case imchatauthrequest.FieldChatTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chat_title", values[i])
			} else if value.Valid {
				_m.ChatTitle = value.String
			}
		case imchatauthrequest.FieldSenderExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_external_id", values[i])
			} else if value.Valid {
				_m.SenderExternalID = value.String
			}
		case imchatauthrequest.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case imchatauthrequest.FieldTokenPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_prefix", values[i])
			} else if value.Valid {
				_m.TokenPrefix = value.String
			}
		case imchatauthrequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case imchatauthrequest.FieldRequestedTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_target", values[i])
			} else if value.Valid {
				_m.RequestedTarget = value.String
			}
		case imchatauthrequest.FieldRequestedThreadID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_thread_id", values[i])
			} else if value.Valid {
				_m.RequestedThreadID = value.String
			}
		case imchatauthrequest.FieldExpiresUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expires_unix", values[i])
			} else if value.Valid {
				_m.ExpiresUnix = value.Int64
			}
		case imchatauthrequest.FieldResolvedByUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_by_user_id", values[i])
			} else if value.Valid {
				_m.ResolvedByUserID = value.String
			}
		case imchatauthrequest.FieldResolvedUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_unix", values[i])
			} else if value.Valid {
				_m.ResolvedUnix = value.Int64
			}
		case imchatauthrequest.FieldCreatedUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_unix", values[i])
			} else if value.Valid {
				_m.CreatedUnix = value.Int64
			}
		case imchatauthrequest.FieldUpdatedUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_unix", values[i])
			} else if value.Valid {
				_m.UpdatedUnix = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IMChatAuthRequest.
// This includes values selected through modifiers, order, etc.
func (_m *IMChatAuthRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IMChatAuthRequest.
// Note that you need to call IMChatAuthRequest.Unwrap() before calling this method if this IMChatAuthRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IMChatAuthRequest) Update() *IMChatAuthRequestUpdateOne {
	return NewIMChatAuthRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IMChatAuthRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IMChatAuthRequest) Unwrap() *IMChatAuthRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IMChatAuthRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IMChatAuthRequest) String() string {
	var builder strings.Builder
	builder.WriteString("IMChatAuthRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("endpoint_id=")
	builder.WriteString(_m.EndpointID)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("conversation_id=")
	builder.WriteString(_m.ConversationID)
	builder.WriteString(", ")
	builder.WriteString("external_thread_id=")
	builder.WriteString(_m.ExternalThreadID)
	builder.WriteString(", ")
	builder.WriteString("chat_title=")
	builder.WriteString(_m.ChatTitle)
	builder.WriteString(", ")
	builder.WriteString("sender_external_id=")
	builder.WriteString(_m.SenderExternalID)
	builder.WriteString(", ")
	builder.WriteString("token_hash=")
	builder.WriteString(_m.TokenHash)
	builder.WriteString(", ")
	builder.WriteString("token_prefix=")
	builder.WriteString(_m.TokenPrefix)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("requested_target=")
	builder.WriteString(_m.RequestedTarget)
	builder.WriteString(", ")
	builder.WriteString("requested_thread_id=")
	builder.WriteString(_m.RequestedThreadID)
	builder.WriteString(", ")
	builder.WriteString("expires_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpiresUnix))
	builder.WriteString(", ")
	builder.WriteString("resolved_by_user_id=")
	builder.WriteString(_m.ResolvedByUserID)
	builder.WriteString(", ")
	builder.WriteString("resolved_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResolvedUnix))
	builder.WriteString(", ")
	builder.WriteString("created_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedUnix))
	builder.WriteString(", ")
	builder.WriteString("updated_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedUnix))
	builder.WriteByte(')')
	return builder.String()
}

// IMChatAuthRequests is a parsable slice of IMChatAuthRequest.
type IMChatAuthRequests []*IMChatAuthRequest
