// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/nekode/internal/ent/message"
	"github.com/ca-x/nekode/internal/ent/predicate"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTarget sets the "target" field.
func (_u *MessageUpdate) SetTarget(v string) *MessageUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableTarget(v *string) *MessageUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetThreadID sets the "thread_id" field.
func (_u *MessageUpdate) SetThreadID(v string) *MessageUpdate {
	_u.mutation.SetThreadID(v)
	return _u
}

// SetNillableThreadID sets the "thread_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableThreadID(v *string) *MessageUpdate {
	if v != nil {
		_u.SetThreadID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *MessageUpdate) SetRole(v string) *MessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableRole(v *string) *MessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdate) SetContent(v string) *MessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableContent(v *string) *MessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSenderUserID sets the "sender_user_id" field.
func (_u *MessageUpdate) SetSenderUserID(v string) *MessageUpdate {
	_u.mutation.SetSenderUserID(v)
	return _u
}

// SetNillableSenderUserID sets the "sender_user_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSenderUserID(v *string) *MessageUpdate {
	if v != nil {
		_u.SetSenderUserID(*v)
	}
	return _u
}

// SetSenderAgentID sets the "sender_agent_id" field.
func (_u *MessageUpdate) SetSenderAgentID(v string) *MessageUpdate {
	_u.mutation.SetSenderAgentID(v)
	return _u
}

// SetNillableSenderAgentID sets the "sender_agent_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSenderAgentID(v *string) *MessageUpdate {
	if v != nil {
		_u.SetSenderAgentID(*v)
	}
	return _u
}

// SetSenderDisplayName sets the "sender_display_name" field.
func (_u *MessageUpdate) SetSenderDisplayName(v string) *MessageUpdate {
	_u.mutation.SetSenderDisplayName(v)
	return _u
}

// SetNillableSenderDisplayName sets the "sender_display_name" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSenderDisplayName(v *string) *MessageUpdate {
	if v != nil {
		_u.SetSenderDisplayName(*v)
	}
	return _u
}

// SetSenderKind sets the "sender_kind" field.
func (_u *MessageUpdate) SetSenderKind(v string) *MessageUpdate {
	_u.mutation.SetSenderKind(v)
	return _u
}

// SetNillableSenderKind sets the "sender_kind" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSenderKind(v *string) *MessageUpdate {
	if v != nil {
		_u.SetSenderKind(*v)
	}
	return _u
}

// SetSourceEndpointID sets the "source_endpoint_id" field.
func (_u *MessageUpdate) SetSourceEndpointID(v string) *MessageUpdate {
	_u.mutation.SetSourceEndpointID(v)
	return _u
}

// SetNillableSourceEndpointID sets the "source_endpoint_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSourceEndpointID(v *string) *MessageUpdate {
	if v != nil {
		_u.SetSourceEndpointID(*v)
	}
	return _u
}

// SetExternalMessageID sets the "external_message_id" field.
func (_u *MessageUpdate) SetExternalMessageID(v string) *MessageUpdate {
	_u.mutation.SetExternalMessageID(v)
	return _u
}

// SetNillableExternalMessageID sets the "external_message_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableExternalMessageID(v *string) *MessageUpdate {
	if v != nil {
		_u.SetExternalMessageID(*v)
	}
	return _u
}

// SetMetadataJSON sets the "metadata_json" field.
func (_u *MessageUpdate) SetMetadataJSON(v string) *MessageUpdate {
	_u.mutation.SetMetadataJSON(v)
	return _u
}

// SetNillableMetadataJSON sets the "metadata_json" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableMetadataJSON(v *string) *MessageUpdate {
	if v != nil {
		_u.SetMetadataJSON(*v)
	}
	return _u
}

// SetAttachmentsJSON sets the "attachments_json" field.
func (_u *MessageUpdate) SetAttachmentsJSON(v string) *MessageUpdate {
	_u.mutation.SetAttachmentsJSON(v)
	return _u
}

// SetNillableAttachmentsJSON sets the "attachments_json" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableAttachmentsJSON(v *string) *MessageUpdate {
	if v != nil {
		_u.SetAttachmentsJSON(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *MessageUpdate) SetRequestID(v string) *MessageUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableRequestID(v *string) *MessageUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetCreatedUnix sets the "created_unix" field.
func (_u *MessageUpdate) SetCreatedUnix(v int64) *MessageUpdate {
	_u.mutation.ResetCreatedUnix()
	_u.mutation.SetCreatedUnix(v)
	return _u
}

// SetNillableCreatedUnix sets the "created_unix" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableCreatedUnix(v *int64) *MessageUpdate {
	if v != nil {
		_u.SetCreatedUnix(*v)
	}
	return _u
}

// AddCreatedUnix adds value to the "created_unix" field.
func (_u *MessageUpdate) AddCreatedUnix(v int64) *MessageUpdate {
	_u.mutation.AddCreatedUnix(v)
	return _u
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdate) Mutation() *MessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdate) check() error {
	if v, ok := _u.mutation.Target(); ok {
		if err := message.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "Message.target": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Message.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := message.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Message.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SenderKind(); ok {
		if err := message.SenderKindValidator(v); err != nil {
			return &ValidationError{Name: "sender_kind", err: fmt.Errorf(`ent: validator failed for field "Message.sender_kind": %w`, err)}
		}
	}
	return nil
}

func (_u *MessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(message.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThreadID(); ok {
		_spec.SetField(message.FieldThreadID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderUserID(); ok {
		_spec.SetField(message.FieldSenderUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderAgentID(); ok {
		_spec.SetField(message.FieldSenderAgentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderDisplayName(); ok {
		_spec.SetField(message.FieldSenderDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderKind(); ok {
		_spec.SetField(message.FieldSenderKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceEndpointID(); ok {
		_spec.SetField(message.FieldSourceEndpointID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalMessageID(); ok {
		_spec.SetField(message.FieldExternalMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataJSON(); ok {
		_spec.SetField(message.FieldMetadataJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttachmentsJSON(); ok {
		_spec.SetField(message.FieldAttachmentsJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(message.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedUnix(); ok {
		_spec.SetField(message.FieldCreatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedUnix(); ok {
		_spec.AddField(message.FieldCreatedUnix, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetTarget sets the "target" field.
func (_u *MessageUpdateOne) SetTarget(v string) *MessageUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableTarget(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetThreadID sets the "thread_id" field.
func (_u *MessageUpdateOne) SetThreadID(v string) *MessageUpdateOne {
	_u.mutation.SetThreadID(v)
	return _u
}

// SetNillableThreadID sets the "thread_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableThreadID(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetThreadID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *MessageUpdateOne) SetRole(v string) *MessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableRole(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdateOne) SetContent(v string) *MessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableContent(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSenderUserID sets the "sender_user_id" field.
func (_u *MessageUpdateOne) SetSenderUserID(v string) *MessageUpdateOne {
	_u.mutation.SetSenderUserID(v)
	return _u
}

// SetNillableSenderUserID sets the "sender_user_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSenderUserID(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetSenderUserID(*v)
	}
	return _u
}

// SetSenderAgentID sets the "sender_agent_id" field.
func (_u *MessageUpdateOne) SetSenderAgentID(v string) *MessageUpdateOne {
	_u.mutation.SetSenderAgentID(v)
	return _u
}

// SetNillableSenderAgentID sets the "sender_agent_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSenderAgentID(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetSenderAgentID(*v)
	}
	return _u
}

// SetSenderDisplayName sets the "sender_display_name" field.
func (_u *MessageUpdateOne) SetSenderDisplayName(v string) *MessageUpdateOne {
	_u.mutation.SetSenderDisplayName(v)
	return _u
}

// SetNillableSenderDisplayName sets the "sender_display_name" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSenderDisplayName(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetSenderDisplayName(*v)
	}
	return _u
}

// SetSenderKind sets the "sender_kind" field.
func (_u *MessageUpdateOne) SetSenderKind(v string) *MessageUpdateOne {
	_u.mutation.SetSenderKind(v)
	return _u
}

// SetNillableSenderKind sets the "sender_kind" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSenderKind(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetSenderKind(*v)
	}
	return _u
}

// SetSourceEndpointID sets the "source_endpoint_id" field.
func (_u *MessageUpdateOne) SetSourceEndpointID(v string) *MessageUpdateOne {
	_u.mutation.SetSourceEndpointID(v)
	return _u
}

// SetNillableSourceEndpointID sets the "source_endpoint_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSourceEndpointID(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetSourceEndpointID(*v)
	}
	return _u
}

// SetExternalMessageID sets the "external_message_id" field.
func (_u *MessageUpdateOne) SetExternalMessageID(v string) *MessageUpdateOne {
	_u.mutation.SetExternalMessageID(v)
	return _u
}

// SetNillableExternalMessageID sets the "external_message_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableExternalMessageID(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetExternalMessageID(*v)
	}
	return _u
}

// SetMetadataJSON sets the "metadata_json" field.
func (_u *MessageUpdateOne) SetMetadataJSON(v string) *MessageUpdateOne {
	_u.mutation.SetMetadataJSON(v)
	return _u
}

// SetNillableMetadataJSON sets the "metadata_json" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableMetadataJSON(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetMetadataJSON(*v)
	}
	return _u
}

// SetAttachmentsJSON sets the "attachments_json" field.
func (_u *MessageUpdateOne) SetAttachmentsJSON(v string) *MessageUpdateOne {
	_u.mutation.SetAttachmentsJSON(v)
	return _u
}

// SetNillableAttachmentsJSON sets the "attachments_json" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableAttachmentsJSON(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetAttachmentsJSON(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *MessageUpdateOne) SetRequestID(v string) *MessageUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableRequestID(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetCreatedUnix sets the "created_unix" field.
func (_u *MessageUpdateOne) SetCreatedUnix(v int64) *MessageUpdateOne {
	_u.mutation.ResetCreatedUnix()
	_u.mutation.SetCreatedUnix(v)
	return _u
}

// SetNillableCreatedUnix sets the "created_unix" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableCreatedUnix(v *int64) *MessageUpdateOne {
	if v != nil {
		_u.SetCreatedUnix(*v)
	}
	return _u
}

// AddCreatedUnix adds value to the "created_unix" field.
func (_u *MessageUpdateOne) AddCreatedUnix(v int64) *MessageUpdateOne {
	_u.mutation.AddCreatedUnix(v)
	return _u
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdateOne) Mutation() *MessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Message entity.
func (_u *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdateOne) check() error {
	if v, ok := _u.mutation.Target(); ok {
		if err := message.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "Message.target": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Message.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := message.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Message.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SenderKind(); ok {
		if err := message.SenderKindValidator(v); err != nil {
			return &ValidationError{Name: "sender_kind", err: fmt.Errorf(`ent: validator failed for field "Message.sender_kind": %w`, err)}
		}
	}
	return nil
}

func (_u *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(message.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThreadID(); ok {
		_spec.SetField(message.FieldThreadID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderUserID(); ok {
		_spec.SetField(message.FieldSenderUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderAgentID(); ok {
		_spec.SetField(message.FieldSenderAgentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderDisplayName(); ok {
		_spec.SetField(message.FieldSenderDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderKind(); ok {
		_spec.SetField(message.FieldSenderKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceEndpointID(); ok {
		_spec.SetField(message.FieldSourceEndpointID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalMessageID(); ok {
		_spec.SetField(message.FieldExternalMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataJSON(); ok {
		_spec.SetField(message.FieldMetadataJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttachmentsJSON(); ok {
		_spec.SetField(message.FieldAttachmentsJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(message.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedUnix(); ok {
		_spec.SetField(message.FieldCreatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedUnix(); ok {
		_spec.AddField(message.FieldCreatedUnix, field.TypeInt64, value)
	}
	_node = &Message{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
