// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/nekode/internal/ent/notificationroute"
	"github.com/ca-x/nekode/internal/ent/predicate"
)

// NotificationRouteUpdate is the builder for updating NotificationRoute entities.
type NotificationRouteUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationRouteMutation
}

// Where appends a list predicates to the NotificationRouteUpdate builder.
func (_u *NotificationRouteUpdate) Where(ps ...predicate.NotificationRoute) *NotificationRouteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTarget sets the "target" field.
func (_u *NotificationRouteUpdate) SetTarget(v string) *NotificationRouteUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *NotificationRouteUpdate) SetNillableTarget(v *string) *NotificationRouteUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetThreadID sets the "thread_id" field.
func (_u *NotificationRouteUpdate) SetThreadID(v string) *NotificationRouteUpdate {
	_u.mutation.SetThreadID(v)
	return _u
}

// SetNillableThreadID sets the "thread_id" field if the given value is not nil.
func (_u *NotificationRouteUpdate) SetNillableThreadID(v *string) *NotificationRouteUpdate {
	if v != nil {
		_u.SetThreadID(*v)
	}
	return _u
}

// SetEndpointID sets the "endpoint_id" field.
func (_u *NotificationRouteUpdate) SetEndpointID(v string) *NotificationRouteUpdate {
	_u.mutation.SetEndpointID(v)
	return _u
}

// SetNillableEndpointID sets the "endpoint_id" field if the given value is not nil.
func (_u *NotificationRouteUpdate) SetNillableEndpointID(v *string) *NotificationRouteUpdate {
	if v != nil {
		_u.SetEndpointID(*v)
	}
	return _u
}

// SetEventKind sets the "event_kind" field.
func (_u *NotificationRouteUpdate) SetEventKind(v string) *NotificationRouteUpdate {
	_u.mutation.SetEventKind(v)
	return _u
}

// SetNillableEventKind sets the "event_kind" field if the given value is not nil.
func (_u *NotificationRouteUpdate) SetNillableEventKind(v *string) *NotificationRouteUpdate {
	if v != nil {
		_u.SetEventKind(*v)
	}
	return _u
}

// SetPreference sets the "preference" field.
func (_u *NotificationRouteUpdate) SetPreference(v string) *NotificationRouteUpdate {
	_u.mutation.SetPreference(v)
	return _u
}

// SetNillablePreference sets the "preference" field if the given value is not nil.
func (_u *NotificationRouteUpdate) SetNillablePreference(v *string) *NotificationRouteUpdate {
	if v != nil {
		_u.SetPreference(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotificationRouteUpdate) SetEnabled(v bool) *NotificationRouteUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotificationRouteUpdate) SetNillableEnabled(v *bool) *NotificationRouteUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetConfigJSON sets the "config_json" field.
func (_u *NotificationRouteUpdate) SetConfigJSON(v string) *NotificationRouteUpdate {
	_u.mutation.SetConfigJSON(v)
	return _u
}

// SetNillableConfigJSON sets the "config_json" field if the given value is not nil.
func (_u *NotificationRouteUpdate) SetNillableConfigJSON(v *string) *NotificationRouteUpdate {
	if v != nil {
		_u.SetConfigJSON(*v)
	}
	return _u
}

// SetCreatedUnix sets the "created_unix" field.
func (_u *NotificationRouteUpdate) SetCreatedUnix(v int64) *NotificationRouteUpdate {
	_u.mutation.ResetCreatedUnix()
	_u.mutation.SetCreatedUnix(v)
	return _u
}

// SetNillableCreatedUnix sets the "created_unix" field if the given value is not nil.
func (_u *NotificationRouteUpdate) SetNillableCreatedUnix(v *int64) *NotificationRouteUpdate {
	if v != nil {
		_u.SetCreatedUnix(*v)
	}
	return _u
}

// AddCreatedUnix adds value to the "created_unix" field.
func (_u *NotificationRouteUpdate) AddCreatedUnix(v int64) *NotificationRouteUpdate {
	_u.mutation.AddCreatedUnix(v)
	return _u
}

// SetUpdatedUnix sets the "updated_unix" field.
func (_u *NotificationRouteUpdate) SetUpdatedUnix(v int64) *NotificationRouteUpdate {
	_u.mutation.ResetUpdatedUnix()
	_u.mutation.SetUpdatedUnix(v)
	return _u
}

// SetNillableUpdatedUnix sets the "updated_unix" field if the given value is not nil.
func (_u *NotificationRouteUpdate) SetNillableUpdatedUnix(v *int64) *NotificationRouteUpdate {
	if v != nil {
		_u.SetUpdatedUnix(*v)
	}
	return _u
}

// AddUpdatedUnix adds value to the "updated_unix" field.
func (_u *NotificationRouteUpdate) AddUpdatedUnix(v int64) *NotificationRouteUpdate {
	_u.mutation.AddUpdatedUnix(v)
	return _u
}

// Mutation returns the NotificationRouteMutation object of the builder.
func (_u *NotificationRouteUpdate) Mutation() *NotificationRouteMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationRouteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationRouteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationRouteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationRouteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationRouteUpdate) check() error {
	if v, ok := _u.mutation.Target(); ok {
		if err := notificationroute.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "NotificationRoute.target": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EndpointID(); ok {
		if err := notificationroute.EndpointIDValidator(v); err != nil {
			return &ValidationError{Name: "endpoint_id", err: fmt.Errorf(`ent: validator failed for field "NotificationRoute.endpoint_id": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationRouteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationroute.Table, notificationroute.Columns, sqlgraph.NewFieldSpec(notificationroute.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(notificationroute.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThreadID(); ok {
		_spec.SetField(notificationroute.FieldThreadID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndpointID(); ok {
		_spec.SetField(notificationroute.FieldEndpointID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventKind(); ok {
		_spec.SetField(notificationroute.FieldEventKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Preference(); ok {
		_spec.SetField(notificationroute.FieldPreference, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notificationroute.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConfigJSON(); ok {
		_spec.SetField(notificationroute.FieldConfigJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedUnix(); ok {
		_spec.SetField(notificationroute.FieldCreatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedUnix(); ok {
		_spec.AddField(notificationroute.FieldCreatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedUnix(); ok {
		_spec.SetField(notificationroute.FieldUpdatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedUnix(); ok {
		_spec.AddField(notificationroute.FieldUpdatedUnix, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationroute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationRouteUpdateOne is the builder for updating a single NotificationRoute entity.
type NotificationRouteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationRouteMutation
}

// SetTarget sets the "target" field.
func (_u *NotificationRouteUpdateOne) SetTarget(v string) *NotificationRouteUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *NotificationRouteUpdateOne) SetNillableTarget(v *string) *NotificationRouteUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetThreadID sets the "thread_id" field.
func (_u *NotificationRouteUpdateOne) SetThreadID(v string) *NotificationRouteUpdateOne {
	_u.mutation.SetThreadID(v)
	return _u
}

// SetNillableThreadID sets the "thread_id" field if the given value is not nil.
func (_u *NotificationRouteUpdateOne) SetNillableThreadID(v *string) *NotificationRouteUpdateOne {
	if v != nil {
		_u.SetThreadID(*v)
	}
	return _u
}

// SetEndpointID sets the "endpoint_id" field.
func (_u *NotificationRouteUpdateOne) SetEndpointID(v string) *NotificationRouteUpdateOne {
	_u.mutation.SetEndpointID(v)
	return _u
}

// SetNillableEndpointID sets the "endpoint_id" field if the given value is not nil.
func (_u *NotificationRouteUpdateOne) SetNillableEndpointID(v *string) *NotificationRouteUpdateOne {
	if v != nil {
		_u.SetEndpointID(*v)
	}
	return _u
}

// SetEventKind sets the "event_kind" field.
func (_u *NotificationRouteUpdateOne) SetEventKind(v string) *NotificationRouteUpdateOne {
	_u.mutation.SetEventKind(v)
	return _u
}

// SetNillableEventKind sets the "event_kind" field if the given value is not nil.
func (_u *NotificationRouteUpdateOne) SetNillableEventKind(v *string) *NotificationRouteUpdateOne {
	if v != nil {
		_u.SetEventKind(*v)
	}
	return _u
}

// SetPreference sets the "preference" field.
func (_u *NotificationRouteUpdateOne) SetPreference(v string) *NotificationRouteUpdateOne {
	_u.mutation.SetPreference(v)
	return _u
}

// SetNillablePreference sets the "preference" field if the given value is not nil.
func (_u *NotificationRouteUpdateOne) SetNillablePreference(v *string) *NotificationRouteUpdateOne {
	if v != nil {
		_u.SetPreference(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotificationRouteUpdateOne) SetEnabled(v bool) *NotificationRouteUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotificationRouteUpdateOne) SetNillableEnabled(v *bool) *NotificationRouteUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetConfigJSON sets the "config_json" field.
func (_u *NotificationRouteUpdateOne) SetConfigJSON(v string) *NotificationRouteUpdateOne {
	_u.mutation.SetConfigJSON(v)
	return _u
}

// SetNillableConfigJSON sets the "config_json" field if the given value is not nil.
func (_u *NotificationRouteUpdateOne) SetNillableConfigJSON(v *string) *NotificationRouteUpdateOne {
	if v != nil {
		_u.SetConfigJSON(*v)
	}
	return _u
}

// SetCreatedUnix sets the "created_unix" field.
func (_u *NotificationRouteUpdateOne) SetCreatedUnix(v int64) *NotificationRouteUpdateOne {
	_u.mutation.ResetCreatedUnix()
	_u.mutation.SetCreatedUnix(v)
	return _u
}

// SetNillableCreatedUnix sets the "created_unix" field if the given value is not nil.
func (_u *NotificationRouteUpdateOne) SetNillableCreatedUnix(v *int64) *NotificationRouteUpdateOne {
	if v != nil {
		_u.SetCreatedUnix(*v)
	}
	return _u
}

// AddCreatedUnix adds value to the "created_unix" field.
func (_u *NotificationRouteUpdateOne) AddCreatedUnix(v int64) *NotificationRouteUpdateOne {
	_u.mutation.AddCreatedUnix(v)
	return _u
}

// SetUpdatedUnix sets the "updated_unix" field.
func (_u *NotificationRouteUpdateOne) SetUpdatedUnix(v int64) *NotificationRouteUpdateOne {
	_u.mutation.ResetUpdatedUnix()
	_u.mutation.SetUpdatedUnix(v)
	return _u
}

// SetNillableUpdatedUnix sets the "updated_unix" field if the given value is not nil.
func (_u *NotificationRouteUpdateOne) SetNillableUpdatedUnix(v *int64) *NotificationRouteUpdateOne {
	if v != nil {
		_u.SetUpdatedUnix(*v)
	}
	return _u
}

// AddUpdatedUnix adds value to the "updated_unix" field.
func (_u *NotificationRouteUpdateOne) AddUpdatedUnix(v int64) *NotificationRouteUpdateOne {
	_u.mutation.AddUpdatedUnix(v)
	return _u
}

// Mutation returns the NotificationRouteMutation object of the builder.
func (_u *NotificationRouteUpdateOne) Mutation() *NotificationRouteMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationRouteUpdate builder.
func (_u *NotificationRouteUpdateOne) Where(ps ...predicate.NotificationRoute) *NotificationRouteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationRouteUpdateOne) Select(field string, fields ...string) *NotificationRouteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationRoute entity.
func (_u *NotificationRouteUpdateOne) Save(ctx context.Context) (*NotificationRoute, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationRouteUpdateOne) SaveX(ctx context.Context) *NotificationRoute {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationRouteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationRouteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationRouteUpdateOne) check() error {
	if v, ok := _u.mutation.Target(); ok {
		if err := notificationroute.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "NotificationRoute.target": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EndpointID(); ok {
		if err := notificationroute.EndpointIDValidator(v); err != nil {
			return &ValidationError{Name: "endpoint_id", err: fmt.Errorf(`ent: validator failed for field "NotificationRoute.endpoint_id": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationRouteUpdateOne) sqlSave(ctx context.Context) (_node *NotificationRoute, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationroute.Table, notificationroute.Columns, sqlgraph.NewFieldSpec(notificationroute.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationRoute.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationroute.FieldID)
		for _, f := range fields {
			if !notificationroute.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationroute.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(notificationroute.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThreadID(); ok {
		_spec.SetField(notificationroute.FieldThreadID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndpointID(); ok {
		_spec.SetField(notificationroute.FieldEndpointID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventKind(); ok {
		_spec.SetField(notificationroute.FieldEventKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Preference(); ok {
		_spec.SetField(notificationroute.FieldPreference, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notificationroute.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConfigJSON(); ok {
		_spec.SetField(notificationroute.FieldConfigJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedUnix(); ok {
		_spec.SetField(notificationroute.FieldCreatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedUnix(); ok {
		_spec.AddField(notificationroute.FieldCreatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedUnix(); ok {
		_spec.SetField(notificationroute.FieldUpdatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedUnix(); ok {
		_spec.AddField(notificationroute.FieldUpdatedUnix, field.TypeInt64, value)
	}
	_node = &NotificationRoute{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationroute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
