// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/nekode/internal/ent/reminderevent"
)

// ReminderEventCreate is the builder for creating a ReminderEvent entity.
type ReminderEventCreate struct {
	config
	mutation *ReminderEventMutation
	hooks    []Hook
}

// SetReminderID sets the "reminder_id" field.
func (_c *ReminderEventCreate) SetReminderID(v string) *ReminderEventCreate {
	_c.mutation.SetReminderID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *ReminderEventCreate) SetEventType(v string) *ReminderEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetActorType sets the "actor_type" field.
func (_c *ReminderEventCreate) SetActorType(v string) *ReminderEventCreate {
	_c.mutation.SetActorType(v)
	return _c
}

// SetNillableActorType sets the "actor_type" field if the given value is not nil.
func (_c *ReminderEventCreate) SetNillableActorType(v *string) *ReminderEventCreate {
	if v != nil {
		_c.SetActorType(*v)
	}
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *ReminderEventCreate) SetActorID(v string) *ReminderEventCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_c *ReminderEventCreate) SetNillableActorID(v *string) *ReminderEventCreate {
	if v != nil {
		_c.SetActorID(*v)
	}
	return _c
}

// SetOccurredTimeUnix sets the "occurred_time_unix" field.
func (_c *ReminderEventCreate) SetOccurredTimeUnix(v int64) *ReminderEventCreate {
	_c.mutation.SetOccurredTimeUnix(v)
	return _c
}

// SetNextFireTimeUnix sets the "next_fire_time_unix" field.
func (_c *ReminderEventCreate) SetNextFireTimeUnix(v int64) *ReminderEventCreate {
	_c.mutation.SetNextFireTimeUnix(v)
	return _c
}

// SetNillableNextFireTimeUnix sets the "next_fire_time_unix" field if the given value is not nil.
func (_c *ReminderEventCreate) SetNillableNextFireTimeUnix(v *int64) *ReminderEventCreate {
	if v != nil {
		_c.SetNextFireTimeUnix(*v)
	}
	return _c
}

// SetDetail sets the "detail" field.
func (_c *ReminderEventCreate) SetDetail(v string) *ReminderEventCreate {
	_c.mutation.SetDetail(v)
	return _c
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_c *ReminderEventCreate) SetNillableDetail(v *string) *ReminderEventCreate {
	if v != nil {
		_c.SetDetail(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ReminderEventCreate) SetID(v string) *ReminderEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ReminderEventCreate) SetNillableID(v *string) *ReminderEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ReminderEventMutation object of the builder.
func (_c *ReminderEventCreate) Mutation() *ReminderEventMutation {
	return _c.mutation
}

// Save creates the ReminderEvent in the database.
func (_c *ReminderEventCreate) Save(ctx context.Context) (*ReminderEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReminderEventCreate) SaveX(ctx context.Context) *ReminderEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReminderEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReminderEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReminderEventCreate) defaults() {
	if _, ok := _c.mutation.ActorType(); !ok {
		v := reminderevent.DefaultActorType
		_c.mutation.SetActorType(v)
	}
	if _, ok := _c.mutation.ActorID(); !ok {
		v := reminderevent.DefaultActorID
		_c.mutation.SetActorID(v)
	}
	if _, ok := _c.mutation.NextFireTimeUnix(); !ok {
		v := reminderevent.DefaultNextFireTimeUnix
		_c.mutation.SetNextFireTimeUnix(v)
	}
	if _, ok := _c.mutation.Detail(); !ok {
		v := reminderevent.DefaultDetail
		_c.mutation.SetDetail(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := reminderevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReminderEventCreate) check() error {
	if _, ok := _c.mutation.ReminderID(); !ok {
		return &ValidationError{Name: "reminder_id", err: errors.New(`ent: missing required field "ReminderEvent.reminder_id"`)}
	}
	if v, ok := _c.mutation.ReminderID(); ok {
		if err := reminderevent.ReminderIDValidator(v); err != nil {
			return &ValidationError{Name: "reminder_id", err: fmt.Errorf(`ent: validator failed for field "ReminderEvent.reminder_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "ReminderEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := reminderevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "ReminderEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorType(); !ok {
		return &ValidationError{Name: "actor_type", err: errors.New(`ent: missing required field "ReminderEvent.actor_type"`)}
	}
	if _, ok := _c.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`ent: missing required field "ReminderEvent.actor_id"`)}
	}
	if _, ok := _c.mutation.OccurredTimeUnix(); !ok {
		return &ValidationError{Name: "occurred_time_unix", err: errors.New(`ent: missing required field "ReminderEvent.occurred_time_unix"`)}
	}
	if _, ok := _c.mutation.NextFireTimeUnix(); !ok {
		return &ValidationError{Name: "next_fire_time_unix", err: errors.New(`ent: missing required field "ReminderEvent.next_fire_time_unix"`)}
	}
	if _, ok := _c.mutation.Detail(); !ok {
		return &ValidationError{Name: "detail", err: errors.New(`ent: missing required field "ReminderEvent.detail"`)}
	}
	return nil
}

func (_c *ReminderEventCreate) sqlSave(ctx context.Context) (*ReminderEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ReminderEvent.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReminderEventCreate) createSpec() (*ReminderEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &ReminderEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reminderevent.Table, sqlgraph.NewFieldSpec(reminderevent.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ReminderID(); ok {
		_spec.SetField(reminderevent.FieldReminderID, field.TypeString, value)
		_node.ReminderID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(reminderevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.ActorType(); ok {
		_spec.SetField(reminderevent.FieldActorType, field.TypeString, value)
		_node.ActorType = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(reminderevent.FieldActorID, field.TypeString, value)
		_node.ActorID = value
	}
	if value, ok := _c.mutation.OccurredTimeUnix(); ok {
		_spec.SetField(reminderevent.FieldOccurredTimeUnix, field.TypeInt64, value)
		_node.OccurredTimeUnix = value
	}
	if value, ok := _c.mutation.NextFireTimeUnix(); ok {
		_spec.SetField(reminderevent.FieldNextFireTimeUnix, field.TypeInt64, value)
		_node.NextFireTimeUnix = value
	}
	if value, ok := _c.mutation.Detail(); ok {
		_spec.SetField(reminderevent.FieldDetail, field.TypeString, value)
		_node.Detail = value
	}
	return _node, _spec
}

// ReminderEventCreateBulk is the builder for creating many ReminderEvent entities in bulk.
type ReminderEventCreateBulk struct {
	config
	err      error
	builders []*ReminderEventCreate
}

// Save creates the ReminderEvent entities in the database.
func (_c *ReminderEventCreateBulk) Save(ctx context.Context) ([]*ReminderEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReminderEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReminderEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReminderEventCreateBulk) SaveX(ctx context.Context) []*ReminderEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReminderEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReminderEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
