// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/nekode/internal/ent/savedmessage"
)

// SavedMessage is the model entity for the SavedMessage schema.
type SavedMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Target holds the value of the "target" field.
	Target string `json:"target,omitempty"`
	// MessageID holds the value of the "message_id" field.
	MessageID string `json:"message_id,omitempty"`
	// SavedByUserID holds the value of the "saved_by_user_id" field.
	SavedByUserID string `json:"saved_by_user_id,omitempty"`
	// SavedByAgentID holds the value of the "saved_by_agent_id" field.
	SavedByAgentID string `json:"saved_by_agent_id,omitempty"`
	// CreatedUnix holds the value of the "created_unix" field.
	CreatedUnix  int64 `json:"created_unix,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SavedMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case savedmessage.FieldCreatedUnix:
			values[i] = new(sql.NullInt64)
		case savedmessage.FieldID, savedmessage.FieldTarget, savedmessage.FieldMessageID, savedmessage.FieldSavedByUserID, savedmessage.FieldSavedByAgentID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SavedMessage fields.
func (_m *SavedMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case savedmessage.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case savedmessage.FieldTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target", values[i])
			} else if value.Valid {
				_m.Target = value.String
			}
		case savedmessage.FieldMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				_m.MessageID = value.String
			}
		case savedmessage.FieldSavedByUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field saved_by_user_id", values[i])
			} else if value.Valid {
				_m.SavedByUserID = value.String
			}
		case savedmessage.FieldSavedByAgentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field saved_by_agent_id", values[i])
			} else if value.Valid {
				_m.SavedByAgentID = value.String
			}
		case savedmessage.FieldCreatedUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_unix", values[i])
			} else if value.Valid {
				_m.CreatedUnix = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SavedMessage.
// This includes values selected through modifiers, order, etc.
func (_m *SavedMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SavedMessage.
// Note that you need to call SavedMessage.Unwrap() before calling this method if this SavedMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SavedMessage) Update() *SavedMessageUpdateOne {
	return NewSavedMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SavedMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SavedMessage) Unwrap() *SavedMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SavedMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SavedMessage) String() string {
	var builder strings.Builder
	builder.WriteString("SavedMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("target=")
	builder.WriteString(_m.Target)
	builder.WriteString(", ")
	builder.WriteString("message_id=")
	builder.WriteString(_m.MessageID)
	builder.WriteString(", ")
	builder.WriteString("saved_by_user_id=")
	builder.WriteString(_m.SavedByUserID)
	builder.WriteString(", ")
	builder.WriteString("saved_by_agent_id=")
	builder.WriteString(_m.SavedByAgentID)
	builder.WriteString(", ")
	builder.WriteString("created_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedUnix))
	builder.WriteByte(')')
	return builder.String()
}

// SavedMessages is a parsable slice of SavedMessage.
type SavedMessages []*SavedMessage
