// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/nekode/internal/ent/savedmessage"
)

// SavedMessageCreate is the builder for creating a SavedMessage entity.
type SavedMessageCreate struct {
	config
	mutation *SavedMessageMutation
	hooks    []Hook
}

// SetTarget sets the "target" field.
func (_c *SavedMessageCreate) SetTarget(v string) *SavedMessageCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *SavedMessageCreate) SetMessageID(v string) *SavedMessageCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetSavedByUserID sets the "saved_by_user_id" field.
func (_c *SavedMessageCreate) SetSavedByUserID(v string) *SavedMessageCreate {
	_c.mutation.SetSavedByUserID(v)
	return _c
}

// SetNillableSavedByUserID sets the "saved_by_user_id" field if the given value is not nil.
func (_c *SavedMessageCreate) SetNillableSavedByUserID(v *string) *SavedMessageCreate {
	if v != nil {
		_c.SetSavedByUserID(*v)
	}
	return _c
}

// SetSavedByAgentID sets the "saved_by_agent_id" field.
func (_c *SavedMessageCreate) SetSavedByAgentID(v string) *SavedMessageCreate {
	_c.mutation.SetSavedByAgentID(v)
	return _c
}

// SetNillableSavedByAgentID sets the "saved_by_agent_id" field if the given value is not nil.
func (_c *SavedMessageCreate) SetNillableSavedByAgentID(v *string) *SavedMessageCreate {
	if v != nil {
		_c.SetSavedByAgentID(*v)
	}
	return _c
}

// SetCreatedUnix sets the "created_unix" field.
func (_c *SavedMessageCreate) SetCreatedUnix(v int64) *SavedMessageCreate {
	_c.mutation.SetCreatedUnix(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SavedMessageCreate) SetID(v string) *SavedMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SavedMessageCreate) SetNillableID(v *string) *SavedMessageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SavedMessageMutation object of the builder.
func (_c *SavedMessageCreate) Mutation() *SavedMessageMutation {
	return _c.mutation
}

// Save creates the SavedMessage in the database.
func (_c *SavedMessageCreate) Save(ctx context.Context) (*SavedMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SavedMessageCreate) SaveX(ctx context.Context) *SavedMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SavedMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SavedMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SavedMessageCreate) defaults() {
	if _, ok := _c.mutation.SavedByUserID(); !ok {
		v := savedmessage.DefaultSavedByUserID
		_c.mutation.SetSavedByUserID(v)
	}
	if _, ok := _c.mutation.SavedByAgentID(); !ok {
		v := savedmessage.DefaultSavedByAgentID
		_c.mutation.SetSavedByAgentID(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := savedmessage.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SavedMessageCreate) check() error {
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "SavedMessage.target"`)}
	}
	if v, ok := _c.mutation.Target(); ok {
		if err := savedmessage.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "SavedMessage.target": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "SavedMessage.message_id"`)}
	}
	if v, ok := _c.mutation.MessageID(); ok {
		if err := savedmessage.MessageIDValidator(v); err != nil {
			return &ValidationError{Name: "message_id", err: fmt.Errorf(`ent: validator failed for field "SavedMessage.message_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SavedByUserID(); !ok {
		return &ValidationError{Name: "saved_by_user_id", err: errors.New(`ent: missing required field "SavedMessage.saved_by_user_id"`)}
	}
	if _, ok := _c.mutation.SavedByAgentID(); !ok {
		return &ValidationError{Name: "saved_by_agent_id", err: errors.New(`ent: missing required field "SavedMessage.saved_by_agent_id"`)}
	}
	if _, ok := _c.mutation.CreatedUnix(); !ok {
		return &ValidationError{Name: "created_unix", err: errors.New(`ent: missing required field "SavedMessage.created_unix"`)}
	}
	return nil
}

func (_c *SavedMessageCreate) sqlSave(ctx context.Context) (*SavedMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SavedMessage.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SavedMessageCreate) createSpec() (*SavedMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &SavedMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(savedmessage.Table, sqlgraph.NewFieldSpec(savedmessage.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(savedmessage.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(savedmessage.FieldMessageID, field.TypeString, value)
		_node.MessageID = value
	}
	if value, ok := _c.mutation.SavedByUserID(); ok {
		_spec.SetField(savedmessage.FieldSavedByUserID, field.TypeString, value)
		_node.SavedByUserID = value
	}
	if value, ok := _c.mutation.SavedByAgentID(); ok {
		_spec.SetField(savedmessage.FieldSavedByAgentID, field.TypeString, value)
		_node.SavedByAgentID = value
	}
	if value, ok := _c.mutation.CreatedUnix(); ok {
		_spec.SetField(savedmessage.FieldCreatedUnix, field.TypeInt64, value)
		_node.CreatedUnix = value
	}
	return _node, _spec
}

// SavedMessageCreateBulk is the builder for creating many SavedMessage entities in bulk.
type SavedMessageCreateBulk struct {
	config
	err      error
	builders []*SavedMessageCreate
}

// Save creates the SavedMessage entities in the database.
func (_c *SavedMessageCreateBulk) Save(ctx context.Context) ([]*SavedMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SavedMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SavedMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SavedMessageCreateBulk) SaveX(ctx context.Context) []*SavedMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SavedMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SavedMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
