// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/nekode/internal/ent/tunnel"
)

// Tunnel is the model entity for the Tunnel schema.
type Tunnel struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// ComputerID holds the value of the "computer_id" field.
	ComputerID string `json:"computer_id,omitempty"`
	// DaemonID holds the value of the "daemon_id" field.
	DaemonID string `json:"daemon_id,omitempty"`
	// LocalPort holds the value of the "local_port" field.
	LocalPort uint32 `json:"local_port,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// AccessPolicy holds the value of the "access_policy" field.
	AccessPolicy string `json:"access_policy,omitempty"`
	// CreatorID holds the value of the "creator_id" field.
	CreatorID string `json:"creator_id,omitempty"`
	// CreatorKind holds the value of the "creator_kind" field.
	CreatorKind string `json:"creator_kind,omitempty"`
	// CreatedUnix holds the value of the "created_unix" field.
	CreatedUnix int64 `json:"created_unix,omitempty"`
	// ExpiresUnix holds the value of the "expires_unix" field.
	ExpiresUnix int64 `json:"expires_unix,omitempty"`
	// ApprovedUnix holds the value of the "approved_unix" field.
	ApprovedUnix int64 `json:"approved_unix,omitempty"`
	// ApprovedBy holds the value of the "approved_by" field.
	ApprovedBy string `json:"approved_by,omitempty"`
	// ClosedUnix holds the value of the "closed_unix" field.
	ClosedUnix int64 `json:"closed_unix,omitempty"`
	// CloseReason holds the value of the "close_reason" field.
	CloseReason  string `json:"close_reason,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tunnel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tunnel.FieldLocalPort, tunnel.FieldCreatedUnix, tunnel.FieldExpiresUnix, tunnel.FieldApprovedUnix, tunnel.FieldClosedUnix:
			values[i] = new(sql.NullInt64)
		case tunnel.FieldID, tunnel.FieldToken, tunnel.FieldComputerID, tunnel.FieldDaemonID, tunnel.FieldLabel, tunnel.FieldState, tunnel.FieldAccessPolicy, tunnel.FieldCreatorID, tunnel.FieldCreatorKind, tunnel.FieldApprovedBy, tunnel.FieldCloseReason:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tunnel fields.
func (_m *Tunnel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tunnel.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case tunnel.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case tunnel.FieldComputerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field computer_id", values[i])
			} else if value.Valid {
				_m.ComputerID = value.String
			}
		case tunnel.FieldDaemonID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field daemon_id", values[i])
			} else if value.Valid {
				_m.DaemonID = value.String
			}
		case tunnel.FieldLocalPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field local_port", values[i])
			} else if value.Valid {
				_m.LocalPort = uint32(value.Int64)
			}
		case tunnel.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case tunnel.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case tunnel.FieldAccessPolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_policy", values[i])
			} else if value.Valid {
				_m.AccessPolicy = value.String
			}
		case tunnel.FieldCreatorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creator_id", values[i])
			} else if value.Valid {
				_m.CreatorID = value.String
			}
		case tunnel.FieldCreatorKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creator_kind", values[i])
			} else if value.Valid {
				_m.CreatorKind = value.String
			}
		case tunnel.FieldCreatedUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_unix", values[i])
			} else if value.Valid {
				_m.CreatedUnix = value.Int64
			}
		case tunnel.FieldExpiresUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expires_unix", values[i])
			} else if value.Valid {
				_m.ExpiresUnix = value.Int64
			}
		case tunnel.FieldApprovedUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field approved_unix", values[i])
			} else if value.Valid {
				_m.ApprovedUnix = value.Int64
			}
		case tunnel.FieldApprovedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field approved_by", values[i])
			} else if value.Valid {
				_m.ApprovedBy = value.String
			}
		case tunnel.FieldClosedUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field closed_unix", values[i])
			} else if value.Valid {
				_m.ClosedUnix = value.Int64
			}
		case tunnel.FieldCloseReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field close_reason", values[i])
			} else if value.Valid {
				_m.CloseReason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Tunnel.
// This includes values selected through modifiers, order, etc.
func (_m *Tunnel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Tunnel.
// Note that you need to call Tunnel.Unwrap() before calling this method if this Tunnel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Tunnel) Update() *TunnelUpdateOne {
	return NewTunnelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Tunnel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Tunnel) Unwrap() *Tunnel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Tunnel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Tunnel) String() string {
	var builder strings.Builder
	builder.WriteString("Tunnel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("computer_id=")
	builder.WriteString(_m.ComputerID)
	builder.WriteString(", ")
	builder.WriteString("daemon_id=")
	builder.WriteString(_m.DaemonID)
	builder.WriteString(", ")
	builder.WriteString("local_port=")
	builder.WriteString(fmt.Sprintf("%v", _m.LocalPort))
	builder.WriteString(", ")
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("access_policy=")
	builder.WriteString(_m.AccessPolicy)
	builder.WriteString(", ")
	builder.WriteString("creator_id=")
	builder.WriteString(_m.CreatorID)
	builder.WriteString(", ")
	builder.WriteString("creator_kind=")
	builder.WriteString(_m.CreatorKind)
	builder.WriteString(", ")
	builder.WriteString("created_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedUnix))
	builder.WriteString(", ")
	builder.WriteString("expires_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpiresUnix))
	builder.WriteString(", ")
	builder.WriteString("approved_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.ApprovedUnix))
	builder.WriteString(", ")
	builder.WriteString("approved_by=")
	builder.WriteString(_m.ApprovedBy)
	builder.WriteString(", ")
	builder.WriteString("closed_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClosedUnix))
	builder.WriteString(", ")
	builder.WriteString("close_reason=")
	builder.WriteString(_m.CloseReason)
	builder.WriteByte(')')
	return builder.String()
}

// Tunnels is a parsable slice of Tunnel.
type Tunnels []*Tunnel
