// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/nekode/internal/ent/predicate"
	"github.com/ca-x/nekode/internal/ent/tunnel"
)

// TunnelUpdate is the builder for updating Tunnel entities.
type TunnelUpdate struct {
	config
	hooks    []Hook
	mutation *TunnelMutation
}

// Where appends a list predicates to the TunnelUpdate builder.
func (_u *TunnelUpdate) Where(ps ...predicate.Tunnel) *TunnelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetToken sets the "token" field.
func (_u *TunnelUpdate) SetToken(v string) *TunnelUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableToken(v *string) *TunnelUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetComputerID sets the "computer_id" field.
func (_u *TunnelUpdate) SetComputerID(v string) *TunnelUpdate {
	_u.mutation.SetComputerID(v)
	return _u
}

// SetNillableComputerID sets the "computer_id" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableComputerID(v *string) *TunnelUpdate {
	if v != nil {
		_u.SetComputerID(*v)
	}
	return _u
}

// SetDaemonID sets the "daemon_id" field.
func (_u *TunnelUpdate) SetDaemonID(v string) *TunnelUpdate {
	_u.mutation.SetDaemonID(v)
	return _u
}

// SetNillableDaemonID sets the "daemon_id" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableDaemonID(v *string) *TunnelUpdate {
	if v != nil {
		_u.SetDaemonID(*v)
	}
	return _u
}

// SetLocalPort sets the "local_port" field.
func (_u *TunnelUpdate) SetLocalPort(v uint32) *TunnelUpdate {
	_u.mutation.ResetLocalPort()
	_u.mutation.SetLocalPort(v)
	return _u
}

// SetNillableLocalPort sets the "local_port" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableLocalPort(v *uint32) *TunnelUpdate {
	if v != nil {
		_u.SetLocalPort(*v)
	}
	return _u
}

// AddLocalPort adds value to the "local_port" field.
func (_u *TunnelUpdate) AddLocalPort(v int32) *TunnelUpdate {
	_u.mutation.AddLocalPort(v)
	return _u
}

// SetLabel sets the "label" field.
func (_u *TunnelUpdate) SetLabel(v string) *TunnelUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableLabel(v *string) *TunnelUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *TunnelUpdate) SetState(v string) *TunnelUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableState(v *string) *TunnelUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetAccessPolicy sets the "access_policy" field.
func (_u *TunnelUpdate) SetAccessPolicy(v string) *TunnelUpdate {
	_u.mutation.SetAccessPolicy(v)
	return _u
}

// SetNillableAccessPolicy sets the "access_policy" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableAccessPolicy(v *string) *TunnelUpdate {
	if v != nil {
		_u.SetAccessPolicy(*v)
	}
	return _u
}

// SetCreatorID sets the "creator_id" field.
func (_u *TunnelUpdate) SetCreatorID(v string) *TunnelUpdate {
	_u.mutation.SetCreatorID(v)
	return _u
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableCreatorID(v *string) *TunnelUpdate {
	if v != nil {
		_u.SetCreatorID(*v)
	}
	return _u
}

// SetCreatorKind sets the "creator_kind" field.
func (_u *TunnelUpdate) SetCreatorKind(v string) *TunnelUpdate {
	_u.mutation.SetCreatorKind(v)
	return _u
}

// SetNillableCreatorKind sets the "creator_kind" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableCreatorKind(v *string) *TunnelUpdate {
	if v != nil {
		_u.SetCreatorKind(*v)
	}
	return _u
}

// SetCreatedUnix sets the "created_unix" field.
func (_u *TunnelUpdate) SetCreatedUnix(v int64) *TunnelUpdate {
	_u.mutation.ResetCreatedUnix()
	_u.mutation.SetCreatedUnix(v)
	return _u
}

// SetNillableCreatedUnix sets the "created_unix" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableCreatedUnix(v *int64) *TunnelUpdate {
	if v != nil {
		_u.SetCreatedUnix(*v)
	}
	return _u
}

// AddCreatedUnix adds value to the "created_unix" field.
func (_u *TunnelUpdate) AddCreatedUnix(v int64) *TunnelUpdate {
	_u.mutation.AddCreatedUnix(v)
	return _u
}

// SetExpiresUnix sets the "expires_unix" field.
func (_u *TunnelUpdate) SetExpiresUnix(v int64) *TunnelUpdate {
	_u.mutation.ResetExpiresUnix()
	_u.mutation.SetExpiresUnix(v)
	return _u
}

// SetNillableExpiresUnix sets the "expires_unix" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableExpiresUnix(v *int64) *TunnelUpdate {
	if v != nil {
		_u.SetExpiresUnix(*v)
	}
	return _u
}

// AddExpiresUnix adds value to the "expires_unix" field.
func (_u *TunnelUpdate) AddExpiresUnix(v int64) *TunnelUpdate {
	_u.mutation.AddExpiresUnix(v)
	return _u
}

// SetApprovedUnix sets the "approved_unix" field.
func (_u *TunnelUpdate) SetApprovedUnix(v int64) *TunnelUpdate {
	_u.mutation.ResetApprovedUnix()
	_u.mutation.SetApprovedUnix(v)
	return _u
}

// SetNillableApprovedUnix sets the "approved_unix" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableApprovedUnix(v *int64) *TunnelUpdate {
	if v != nil {
		_u.SetApprovedUnix(*v)
	}
	return _u
}

// AddApprovedUnix adds value to the "approved_unix" field.
func (_u *TunnelUpdate) AddApprovedUnix(v int64) *TunnelUpdate {
	_u.mutation.AddApprovedUnix(v)
	return _u
}

// SetApprovedBy sets the "approved_by" field.
func (_u *TunnelUpdate) SetApprovedBy(v string) *TunnelUpdate {
	_u.mutation.SetApprovedBy(v)
	return _u
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableApprovedBy(v *string) *TunnelUpdate {
	if v != nil {
		_u.SetApprovedBy(*v)
	}
	return _u
}

// SetClosedUnix sets the "closed_unix" field.
func (_u *TunnelUpdate) SetClosedUnix(v int64) *TunnelUpdate {
	_u.mutation.ResetClosedUnix()
	_u.mutation.SetClosedUnix(v)
	return _u
}

// SetNillableClosedUnix sets the "closed_unix" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableClosedUnix(v *int64) *TunnelUpdate {
	if v != nil {
		_u.SetClosedUnix(*v)
	}
	return _u
}

// AddClosedUnix adds value to the "closed_unix" field.
func (_u *TunnelUpdate) AddClosedUnix(v int64) *TunnelUpdate {
	_u.mutation.AddClosedUnix(v)
	return _u
}

// SetCloseReason sets the "close_reason" field.
func (_u *TunnelUpdate) SetCloseReason(v string) *TunnelUpdate {
	_u.mutation.SetCloseReason(v)
	return _u
}

// SetNillableCloseReason sets the "close_reason" field if the given value is not nil.
func (_u *TunnelUpdate) SetNillableCloseReason(v *string) *TunnelUpdate {
	if v != nil {
		_u.SetCloseReason(*v)
	}
	return _u
}

// Mutation returns the TunnelMutation object of the builder.
func (_u *TunnelUpdate) Mutation() *TunnelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TunnelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TunnelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TunnelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TunnelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TunnelUpdate) check() error {
	if v, ok := _u.mutation.Token(); ok {
		if err := tunnel.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Tunnel.token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ComputerID(); ok {
		if err := tunnel.ComputerIDValidator(v); err != nil {
			return &ValidationError{Name: "computer_id", err: fmt.Errorf(`ent: validator failed for field "Tunnel.computer_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := tunnel.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Tunnel.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessPolicy(); ok {
		if err := tunnel.AccessPolicyValidator(v); err != nil {
			return &ValidationError{Name: "access_policy", err: fmt.Errorf(`ent: validator failed for field "Tunnel.access_policy": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatorID(); ok {
		if err := tunnel.CreatorIDValidator(v); err != nil {
			return &ValidationError{Name: "creator_id", err: fmt.Errorf(`ent: validator failed for field "Tunnel.creator_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatorKind(); ok {
		if err := tunnel.CreatorKindValidator(v); err != nil {
			return &ValidationError{Name: "creator_kind", err: fmt.Errorf(`ent: validator failed for field "Tunnel.creator_kind": %w`, err)}
		}
	}
	return nil
}

func (_u *TunnelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunnel.Table, tunnel.Columns, sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(tunnel.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.ComputerID(); ok {
		_spec.SetField(tunnel.FieldComputerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DaemonID(); ok {
		_spec.SetField(tunnel.FieldDaemonID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalPort(); ok {
		_spec.SetField(tunnel.FieldLocalPort, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedLocalPort(); ok {
		_spec.AddField(tunnel.FieldLocalPort, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(tunnel.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(tunnel.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessPolicy(); ok {
		_spec.SetField(tunnel.FieldAccessPolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatorID(); ok {
		_spec.SetField(tunnel.FieldCreatorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatorKind(); ok {
		_spec.SetField(tunnel.FieldCreatorKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedUnix(); ok {
		_spec.SetField(tunnel.FieldCreatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedUnix(); ok {
		_spec.AddField(tunnel.FieldCreatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresUnix(); ok {
		_spec.SetField(tunnel.FieldExpiresUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpiresUnix(); ok {
		_spec.AddField(tunnel.FieldExpiresUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ApprovedUnix(); ok {
		_spec.SetField(tunnel.FieldApprovedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedApprovedUnix(); ok {
		_spec.AddField(tunnel.FieldApprovedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ApprovedBy(); ok {
		_spec.SetField(tunnel.FieldApprovedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClosedUnix(); ok {
		_spec.SetField(tunnel.FieldClosedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClosedUnix(); ok {
		_spec.AddField(tunnel.FieldClosedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CloseReason(); ok {
		_spec.SetField(tunnel.FieldCloseReason, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunnel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TunnelUpdateOne is the builder for updating a single Tunnel entity.
type TunnelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TunnelMutation
}

// SetToken sets the "token" field.
func (_u *TunnelUpdateOne) SetToken(v string) *TunnelUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableToken(v *string) *TunnelUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetComputerID sets the "computer_id" field.
func (_u *TunnelUpdateOne) SetComputerID(v string) *TunnelUpdateOne {
	_u.mutation.SetComputerID(v)
	return _u
}

// SetNillableComputerID sets the "computer_id" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableComputerID(v *string) *TunnelUpdateOne {
	if v != nil {
		_u.SetComputerID(*v)
	}
	return _u
}

// SetDaemonID sets the "daemon_id" field.
func (_u *TunnelUpdateOne) SetDaemonID(v string) *TunnelUpdateOne {
	_u.mutation.SetDaemonID(v)
	return _u
}

// SetNillableDaemonID sets the "daemon_id" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableDaemonID(v *string) *TunnelUpdateOne {
	if v != nil {
		_u.SetDaemonID(*v)
	}
	return _u
}

// SetLocalPort sets the "local_port" field.
func (_u *TunnelUpdateOne) SetLocalPort(v uint32) *TunnelUpdateOne {
	_u.mutation.ResetLocalPort()
	_u.mutation.SetLocalPort(v)
	return _u
}

// SetNillableLocalPort sets the "local_port" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableLocalPort(v *uint32) *TunnelUpdateOne {
	if v != nil {
		_u.SetLocalPort(*v)
	}
	return _u
}

// AddLocalPort adds value to the "local_port" field.
func (_u *TunnelUpdateOne) AddLocalPort(v int32) *TunnelUpdateOne {
	_u.mutation.AddLocalPort(v)
	return _u
}

// SetLabel sets the "label" field.
func (_u *TunnelUpdateOne) SetLabel(v string) *TunnelUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableLabel(v *string) *TunnelUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *TunnelUpdateOne) SetState(v string) *TunnelUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableState(v *string) *TunnelUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetAccessPolicy sets the "access_policy" field.
func (_u *TunnelUpdateOne) SetAccessPolicy(v string) *TunnelUpdateOne {
	_u.mutation.SetAccessPolicy(v)
	return _u
}

// SetNillableAccessPolicy sets the "access_policy" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableAccessPolicy(v *string) *TunnelUpdateOne {
	if v != nil {
		_u.SetAccessPolicy(*v)
	}
	return _u
}

// SetCreatorID sets the "creator_id" field.
func (_u *TunnelUpdateOne) SetCreatorID(v string) *TunnelUpdateOne {
	_u.mutation.SetCreatorID(v)
	return _u
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableCreatorID(v *string) *TunnelUpdateOne {
	if v != nil {
		_u.SetCreatorID(*v)
	}
	return _u
}

// SetCreatorKind sets the "creator_kind" field.
func (_u *TunnelUpdateOne) SetCreatorKind(v string) *TunnelUpdateOne {
	_u.mutation.SetCreatorKind(v)
	return _u
}

// SetNillableCreatorKind sets the "creator_kind" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableCreatorKind(v *string) *TunnelUpdateOne {
	if v != nil {
		_u.SetCreatorKind(*v)
	}
	return _u
}

// SetCreatedUnix sets the "created_unix" field.
func (_u *TunnelUpdateOne) SetCreatedUnix(v int64) *TunnelUpdateOne {
	_u.mutation.ResetCreatedUnix()
	_u.mutation.SetCreatedUnix(v)
	return _u
}

// SetNillableCreatedUnix sets the "created_unix" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableCreatedUnix(v *int64) *TunnelUpdateOne {
	if v != nil {
		_u.SetCreatedUnix(*v)
	}
	return _u
}

// AddCreatedUnix adds value to the "created_unix" field.
func (_u *TunnelUpdateOne) AddCreatedUnix(v int64) *TunnelUpdateOne {
	_u.mutation.AddCreatedUnix(v)
	return _u
}

// SetExpiresUnix sets the "expires_unix" field.
func (_u *TunnelUpdateOne) SetExpiresUnix(v int64) *TunnelUpdateOne {
	_u.mutation.ResetExpiresUnix()
	_u.mutation.SetExpiresUnix(v)
	return _u
}

// SetNillableExpiresUnix sets the "expires_unix" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableExpiresUnix(v *int64) *TunnelUpdateOne {
	if v != nil {
		_u.SetExpiresUnix(*v)
	}
	return _u
}

// AddExpiresUnix adds value to the "expires_unix" field.
func (_u *TunnelUpdateOne) AddExpiresUnix(v int64) *TunnelUpdateOne {
	_u.mutation.AddExpiresUnix(v)
	return _u
}

// SetApprovedUnix sets the "approved_unix" field.
func (_u *TunnelUpdateOne) SetApprovedUnix(v int64) *TunnelUpdateOne {
	_u.mutation.ResetApprovedUnix()
	_u.mutation.SetApprovedUnix(v)
	return _u
}

// SetNillableApprovedUnix sets the "approved_unix" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableApprovedUnix(v *int64) *TunnelUpdateOne {
	if v != nil {
		_u.SetApprovedUnix(*v)
	}
	return _u
}

// AddApprovedUnix adds value to the "approved_unix" field.
func (_u *TunnelUpdateOne) AddApprovedUnix(v int64) *TunnelUpdateOne {
	_u.mutation.AddApprovedUnix(v)
	return _u
}

// SetApprovedBy sets the "approved_by" field.
func (_u *TunnelUpdateOne) SetApprovedBy(v string) *TunnelUpdateOne {
	_u.mutation.SetApprovedBy(v)
	return _u
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableApprovedBy(v *string) *TunnelUpdateOne {
	if v != nil {
		_u.SetApprovedBy(*v)
	}
	return _u
}

// SetClosedUnix sets the "closed_unix" field.
func (_u *TunnelUpdateOne) SetClosedUnix(v int64) *TunnelUpdateOne {
	_u.mutation.ResetClosedUnix()
	_u.mutation.SetClosedUnix(v)
	return _u
}

// SetNillableClosedUnix sets the "closed_unix" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableClosedUnix(v *int64) *TunnelUpdateOne {
	if v != nil {
		_u.SetClosedUnix(*v)
	}
	return _u
}

// AddClosedUnix adds value to the "closed_unix" field.
func (_u *TunnelUpdateOne) AddClosedUnix(v int64) *TunnelUpdateOne {
	_u.mutation.AddClosedUnix(v)
	return _u
}

// SetCloseReason sets the "close_reason" field.
func (_u *TunnelUpdateOne) SetCloseReason(v string) *TunnelUpdateOne {
	_u.mutation.SetCloseReason(v)
	return _u
}

// SetNillableCloseReason sets the "close_reason" field if the given value is not nil.
func (_u *TunnelUpdateOne) SetNillableCloseReason(v *string) *TunnelUpdateOne {
	if v != nil {
		_u.SetCloseReason(*v)
	}
	return _u
}

// Mutation returns the TunnelMutation object of the builder.
func (_u *TunnelUpdateOne) Mutation() *TunnelMutation {
	return _u.mutation
}

// Where appends a list predicates to the TunnelUpdate builder.
func (_u *TunnelUpdateOne) Where(ps ...predicate.Tunnel) *TunnelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TunnelUpdateOne) Select(field string, fields ...string) *TunnelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tunnel entity.
func (_u *TunnelUpdateOne) Save(ctx context.Context) (*Tunnel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TunnelUpdateOne) SaveX(ctx context.Context) *Tunnel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TunnelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TunnelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TunnelUpdateOne) check() error {
	if v, ok := _u.mutation.Token(); ok {
		if err := tunnel.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Tunnel.token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ComputerID(); ok {
		if err := tunnel.ComputerIDValidator(v); err != nil {
			return &ValidationError{Name: "computer_id", err: fmt.Errorf(`ent: validator failed for field "Tunnel.computer_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := tunnel.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Tunnel.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessPolicy(); ok {
		if err := tunnel.AccessPolicyValidator(v); err != nil {
			return &ValidationError{Name: "access_policy", err: fmt.Errorf(`ent: validator failed for field "Tunnel.access_policy": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatorID(); ok {
		if err := tunnel.CreatorIDValidator(v); err != nil {
			return &ValidationError{Name: "creator_id", err: fmt.Errorf(`ent: validator failed for field "Tunnel.creator_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatorKind(); ok {
		if err := tunnel.CreatorKindValidator(v); err != nil {
			return &ValidationError{Name: "creator_kind", err: fmt.Errorf(`ent: validator failed for field "Tunnel.creator_kind": %w`, err)}
		}
	}
	return nil
}

func (_u *TunnelUpdateOne) sqlSave(ctx context.Context) (_node *Tunnel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tunnel.Table, tunnel.Columns, sqlgraph.NewFieldSpec(tunnel.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tunnel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tunnel.FieldID)
		for _, f := range fields {
			if !tunnel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tunnel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(tunnel.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.ComputerID(); ok {
		_spec.SetField(tunnel.FieldComputerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DaemonID(); ok {
		_spec.SetField(tunnel.FieldDaemonID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalPort(); ok {
		_spec.SetField(tunnel.FieldLocalPort, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedLocalPort(); ok {
		_spec.AddField(tunnel.FieldLocalPort, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(tunnel.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(tunnel.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessPolicy(); ok {
		_spec.SetField(tunnel.FieldAccessPolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatorID(); ok {
		_spec.SetField(tunnel.FieldCreatorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatorKind(); ok {
		_spec.SetField(tunnel.FieldCreatorKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedUnix(); ok {
		_spec.SetField(tunnel.FieldCreatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedUnix(); ok {
		_spec.AddField(tunnel.FieldCreatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresUnix(); ok {
		_spec.SetField(tunnel.FieldExpiresUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpiresUnix(); ok {
		_spec.AddField(tunnel.FieldExpiresUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ApprovedUnix(); ok {
		_spec.SetField(tunnel.FieldApprovedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedApprovedUnix(); ok {
		_spec.AddField(tunnel.FieldApprovedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ApprovedBy(); ok {
		_spec.SetField(tunnel.FieldApprovedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClosedUnix(); ok {
		_spec.SetField(tunnel.FieldClosedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClosedUnix(); ok {
		_spec.AddField(tunnel.FieldClosedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CloseReason(); ok {
		_spec.SetField(tunnel.FieldCloseReason, field.TypeString, value)
	}
	_node = &Tunnel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tunnel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
