// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CollaborationEvent is the predicate function for collaborationevent builders.
type CollaborationEvent func(*sql.Selector)

// IdempotencyRecord is the predicate function for idempotencyrecord builders.
type IdempotencyRecord func(*sql.Selector)

// InteractionEndpoint is the predicate function for interactionendpoint builders.
type InteractionEndpoint func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Reminder is the predicate function for reminder builders.
type Reminder func(*sql.Selector)

// ReminderEvent is the predicate function for reminderevent builders.
type ReminderEvent func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// ThreadReadState is the predicate function for threadreadstate builders.
type ThreadReadState func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
