// Code generated by ent, DO NOT EDIT.

package message

import (
	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/nekode/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldID, id))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldTarget, v))
}

// ThreadID applies equality check predicate on the "thread_id" field. It's identical to ThreadIDEQ.
func ThreadID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldThreadID, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldRole, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldContent, v))
}

// ReplyToMessageID applies equality check predicate on the "reply_to_message_id" field. It's identical to ReplyToMessageIDEQ.
func ReplyToMessageID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldReplyToMessageID, v))
}

// SenderUserID applies equality check predicate on the "sender_user_id" field. It's identical to SenderUserIDEQ.
func SenderUserID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderUserID, v))
}

// SenderAgentID applies equality check predicate on the "sender_agent_id" field. It's identical to SenderAgentIDEQ.
func SenderAgentID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderAgentID, v))
}

// SenderDisplayName applies equality check predicate on the "sender_display_name" field. It's identical to SenderDisplayNameEQ.
func SenderDisplayName(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderDisplayName, v))
}

// SenderKind applies equality check predicate on the "sender_kind" field. It's identical to SenderKindEQ.
func SenderKind(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderKind, v))
}

// SourceEndpointID applies equality check predicate on the "source_endpoint_id" field. It's identical to SourceEndpointIDEQ.
func SourceEndpointID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSourceEndpointID, v))
}

// ExternalMessageID applies equality check predicate on the "external_message_id" field. It's identical to ExternalMessageIDEQ.
func ExternalMessageID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldExternalMessageID, v))
}

// MetadataJSON applies equality check predicate on the "metadata_json" field. It's identical to MetadataJSONEQ.
func MetadataJSON(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldMetadataJSON, v))
}

// AttachmentsJSON applies equality check predicate on the "attachments_json" field. It's identical to AttachmentsJSONEQ.
func AttachmentsJSON(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldAttachmentsJSON, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldRequestID, v))
}

// CreatedUnix applies equality check predicate on the "created_unix" field. It's identical to CreatedUnixEQ.
func CreatedUnix(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCreatedUnix, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldTarget, v))
}

// ThreadIDEQ applies the EQ predicate on the "thread_id" field.
func ThreadIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldThreadID, v))
}

// ThreadIDNEQ applies the NEQ predicate on the "thread_id" field.
func ThreadIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldThreadID, v))
}

// ThreadIDIn applies the In predicate on the "thread_id" field.
func ThreadIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldThreadID, vs...))
}

// ThreadIDNotIn applies the NotIn predicate on the "thread_id" field.
func ThreadIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldThreadID, vs...))
}

// ThreadIDGT applies the GT predicate on the "thread_id" field.
func ThreadIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldThreadID, v))
}

// ThreadIDGTE applies the GTE predicate on the "thread_id" field.
func ThreadIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldThreadID, v))
}

// ThreadIDLT applies the LT predicate on the "thread_id" field.
func ThreadIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldThreadID, v))
}

// ThreadIDLTE applies the LTE predicate on the "thread_id" field.
func ThreadIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldThreadID, v))
}

// ThreadIDContains applies the Contains predicate on the "thread_id" field.
func ThreadIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldThreadID, v))
}

// ThreadIDHasPrefix applies the HasPrefix predicate on the "thread_id" field.
func ThreadIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldThreadID, v))
}

// ThreadIDHasSuffix applies the HasSuffix predicate on the "thread_id" field.
func ThreadIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldThreadID, v))
}

// ThreadIDEqualFold applies the EqualFold predicate on the "thread_id" field.
func ThreadIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldThreadID, v))
}

// ThreadIDContainsFold applies the ContainsFold predicate on the "thread_id" field.
func ThreadIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldThreadID, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldRole, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldContent, v))
}

// ReplyToMessageIDEQ applies the EQ predicate on the "reply_to_message_id" field.
func ReplyToMessageIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldReplyToMessageID, v))
}

// ReplyToMessageIDNEQ applies the NEQ predicate on the "reply_to_message_id" field.
func ReplyToMessageIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldReplyToMessageID, v))
}

// ReplyToMessageIDIn applies the In predicate on the "reply_to_message_id" field.
func ReplyToMessageIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldReplyToMessageID, vs...))
}

// ReplyToMessageIDNotIn applies the NotIn predicate on the "reply_to_message_id" field.
func ReplyToMessageIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldReplyToMessageID, vs...))
}

// ReplyToMessageIDGT applies the GT predicate on the "reply_to_message_id" field.
func ReplyToMessageIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldReplyToMessageID, v))
}

// ReplyToMessageIDGTE applies the GTE predicate on the "reply_to_message_id" field.
func ReplyToMessageIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldReplyToMessageID, v))
}

// ReplyToMessageIDLT applies the LT predicate on the "reply_to_message_id" field.
func ReplyToMessageIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldReplyToMessageID, v))
}

// ReplyToMessageIDLTE applies the LTE predicate on the "reply_to_message_id" field.
func ReplyToMessageIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldReplyToMessageID, v))
}

// ReplyToMessageIDContains applies the Contains predicate on the "reply_to_message_id" field.
func ReplyToMessageIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldReplyToMessageID, v))
}

// ReplyToMessageIDHasPrefix applies the HasPrefix predicate on the "reply_to_message_id" field.
func ReplyToMessageIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldReplyToMessageID, v))
}

// ReplyToMessageIDHasSuffix applies the HasSuffix predicate on the "reply_to_message_id" field.
func ReplyToMessageIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldReplyToMessageID, v))
}

// ReplyToMessageIDEqualFold applies the EqualFold predicate on the "reply_to_message_id" field.
func ReplyToMessageIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldReplyToMessageID, v))
}

// ReplyToMessageIDContainsFold applies the ContainsFold predicate on the "reply_to_message_id" field.
func ReplyToMessageIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldReplyToMessageID, v))
}

// SenderUserIDEQ applies the EQ predicate on the "sender_user_id" field.
func SenderUserIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderUserID, v))
}

// SenderUserIDNEQ applies the NEQ predicate on the "sender_user_id" field.
func SenderUserIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSenderUserID, v))
}

// SenderUserIDIn applies the In predicate on the "sender_user_id" field.
func SenderUserIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSenderUserID, vs...))
}

// SenderUserIDNotIn applies the NotIn predicate on the "sender_user_id" field.
func SenderUserIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSenderUserID, vs...))
}

// SenderUserIDGT applies the GT predicate on the "sender_user_id" field.
func SenderUserIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSenderUserID, v))
}

// SenderUserIDGTE applies the GTE predicate on the "sender_user_id" field.
func SenderUserIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSenderUserID, v))
}

// SenderUserIDLT applies the LT predicate on the "sender_user_id" field.
func SenderUserIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSenderUserID, v))
}

// SenderUserIDLTE applies the LTE predicate on the "sender_user_id" field.
func SenderUserIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSenderUserID, v))
}

// SenderUserIDContains applies the Contains predicate on the "sender_user_id" field.
func SenderUserIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldSenderUserID, v))
}

// SenderUserIDHasPrefix applies the HasPrefix predicate on the "sender_user_id" field.
func SenderUserIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldSenderUserID, v))
}

// SenderUserIDHasSuffix applies the HasSuffix predicate on the "sender_user_id" field.
func SenderUserIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldSenderUserID, v))
}

// SenderUserIDEqualFold applies the EqualFold predicate on the "sender_user_id" field.
func SenderUserIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldSenderUserID, v))
}

// SenderUserIDContainsFold applies the ContainsFold predicate on the "sender_user_id" field.
func SenderUserIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldSenderUserID, v))
}

// SenderAgentIDEQ applies the EQ predicate on the "sender_agent_id" field.
func SenderAgentIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderAgentID, v))
}

// SenderAgentIDNEQ applies the NEQ predicate on the "sender_agent_id" field.
func SenderAgentIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSenderAgentID, v))
}

// SenderAgentIDIn applies the In predicate on the "sender_agent_id" field.
func SenderAgentIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSenderAgentID, vs...))
}

// SenderAgentIDNotIn applies the NotIn predicate on the "sender_agent_id" field.
func SenderAgentIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSenderAgentID, vs...))
}

// SenderAgentIDGT applies the GT predicate on the "sender_agent_id" field.
func SenderAgentIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSenderAgentID, v))
}

// SenderAgentIDGTE applies the GTE predicate on the "sender_agent_id" field.
func SenderAgentIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSenderAgentID, v))
}

// SenderAgentIDLT applies the LT predicate on the "sender_agent_id" field.
func SenderAgentIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSenderAgentID, v))
}

// SenderAgentIDLTE applies the LTE predicate on the "sender_agent_id" field.
func SenderAgentIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSenderAgentID, v))
}

// SenderAgentIDContains applies the Contains predicate on the "sender_agent_id" field.
func SenderAgentIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldSenderAgentID, v))
}

// SenderAgentIDHasPrefix applies the HasPrefix predicate on the "sender_agent_id" field.
func SenderAgentIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldSenderAgentID, v))
}

// SenderAgentIDHasSuffix applies the HasSuffix predicate on the "sender_agent_id" field.
func SenderAgentIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldSenderAgentID, v))
}

// SenderAgentIDEqualFold applies the EqualFold predicate on the "sender_agent_id" field.
func SenderAgentIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldSenderAgentID, v))
}

// SenderAgentIDContainsFold applies the ContainsFold predicate on the "sender_agent_id" field.
func SenderAgentIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldSenderAgentID, v))
}

// SenderDisplayNameEQ applies the EQ predicate on the "sender_display_name" field.
func SenderDisplayNameEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderDisplayName, v))
}

// SenderDisplayNameNEQ applies the NEQ predicate on the "sender_display_name" field.
func SenderDisplayNameNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSenderDisplayName, v))
}

// SenderDisplayNameIn applies the In predicate on the "sender_display_name" field.
func SenderDisplayNameIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSenderDisplayName, vs...))
}

// SenderDisplayNameNotIn applies the NotIn predicate on the "sender_display_name" field.
func SenderDisplayNameNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSenderDisplayName, vs...))
}

// SenderDisplayNameGT applies the GT predicate on the "sender_display_name" field.
func SenderDisplayNameGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSenderDisplayName, v))
}

// SenderDisplayNameGTE applies the GTE predicate on the "sender_display_name" field.
func SenderDisplayNameGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSenderDisplayName, v))
}

// SenderDisplayNameLT applies the LT predicate on the "sender_display_name" field.
func SenderDisplayNameLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSenderDisplayName, v))
}

// SenderDisplayNameLTE applies the LTE predicate on the "sender_display_name" field.
func SenderDisplayNameLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSenderDisplayName, v))
}

// SenderDisplayNameContains applies the Contains predicate on the "sender_display_name" field.
func SenderDisplayNameContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldSenderDisplayName, v))
}

// SenderDisplayNameHasPrefix applies the HasPrefix predicate on the "sender_display_name" field.
func SenderDisplayNameHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldSenderDisplayName, v))
}

// SenderDisplayNameHasSuffix applies the HasSuffix predicate on the "sender_display_name" field.
func SenderDisplayNameHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldSenderDisplayName, v))
}

// SenderDisplayNameEqualFold applies the EqualFold predicate on the "sender_display_name" field.
func SenderDisplayNameEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldSenderDisplayName, v))
}

// SenderDisplayNameContainsFold applies the ContainsFold predicate on the "sender_display_name" field.
func SenderDisplayNameContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldSenderDisplayName, v))
}

// SenderKindEQ applies the EQ predicate on the "sender_kind" field.
func SenderKindEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderKind, v))
}

// SenderKindNEQ applies the NEQ predicate on the "sender_kind" field.
func SenderKindNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSenderKind, v))
}

// SenderKindIn applies the In predicate on the "sender_kind" field.
func SenderKindIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSenderKind, vs...))
}

// SenderKindNotIn applies the NotIn predicate on the "sender_kind" field.
func SenderKindNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSenderKind, vs...))
}

// SenderKindGT applies the GT predicate on the "sender_kind" field.
func SenderKindGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSenderKind, v))
}

// SenderKindGTE applies the GTE predicate on the "sender_kind" field.
func SenderKindGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSenderKind, v))
}

// SenderKindLT applies the LT predicate on the "sender_kind" field.
func SenderKindLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSenderKind, v))
}

// SenderKindLTE applies the LTE predicate on the "sender_kind" field.
func SenderKindLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSenderKind, v))
}

// SenderKindContains applies the Contains predicate on the "sender_kind" field.
func SenderKindContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldSenderKind, v))
}

// SenderKindHasPrefix applies the HasPrefix predicate on the "sender_kind" field.
func SenderKindHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldSenderKind, v))
}

// SenderKindHasSuffix applies the HasSuffix predicate on the "sender_kind" field.
func SenderKindHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldSenderKind, v))
}

// SenderKindEqualFold applies the EqualFold predicate on the "sender_kind" field.
func SenderKindEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldSenderKind, v))
}

// SenderKindContainsFold applies the ContainsFold predicate on the "sender_kind" field.
func SenderKindContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldSenderKind, v))
}

// SourceEndpointIDEQ applies the EQ predicate on the "source_endpoint_id" field.
func SourceEndpointIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSourceEndpointID, v))
}

// SourceEndpointIDNEQ applies the NEQ predicate on the "source_endpoint_id" field.
func SourceEndpointIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSourceEndpointID, v))
}

// SourceEndpointIDIn applies the In predicate on the "source_endpoint_id" field.
func SourceEndpointIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSourceEndpointID, vs...))
}

// SourceEndpointIDNotIn applies the NotIn predicate on the "source_endpoint_id" field.
func SourceEndpointIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSourceEndpointID, vs...))
}

// SourceEndpointIDGT applies the GT predicate on the "source_endpoint_id" field.
func SourceEndpointIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSourceEndpointID, v))
}

// SourceEndpointIDGTE applies the GTE predicate on the "source_endpoint_id" field.
func SourceEndpointIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSourceEndpointID, v))
}

// SourceEndpointIDLT applies the LT predicate on the "source_endpoint_id" field.
func SourceEndpointIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSourceEndpointID, v))
}

// SourceEndpointIDLTE applies the LTE predicate on the "source_endpoint_id" field.
func SourceEndpointIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSourceEndpointID, v))
}

// SourceEndpointIDContains applies the Contains predicate on the "source_endpoint_id" field.
func SourceEndpointIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldSourceEndpointID, v))
}

// SourceEndpointIDHasPrefix applies the HasPrefix predicate on the "source_endpoint_id" field.
func SourceEndpointIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldSourceEndpointID, v))
}

// SourceEndpointIDHasSuffix applies the HasSuffix predicate on the "source_endpoint_id" field.
func SourceEndpointIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldSourceEndpointID, v))
}

// SourceEndpointIDEqualFold applies the EqualFold predicate on the "source_endpoint_id" field.
func SourceEndpointIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldSourceEndpointID, v))
}

// SourceEndpointIDContainsFold applies the ContainsFold predicate on the "source_endpoint_id" field.
func SourceEndpointIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldSourceEndpointID, v))
}

// ExternalMessageIDEQ applies the EQ predicate on the "external_message_id" field.
func ExternalMessageIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldExternalMessageID, v))
}

// ExternalMessageIDNEQ applies the NEQ predicate on the "external_message_id" field.
func ExternalMessageIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldExternalMessageID, v))
}

// ExternalMessageIDIn applies the In predicate on the "external_message_id" field.
func ExternalMessageIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldExternalMessageID, vs...))
}

// ExternalMessageIDNotIn applies the NotIn predicate on the "external_message_id" field.
func ExternalMessageIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldExternalMessageID, vs...))
}

// ExternalMessageIDGT applies the GT predicate on the "external_message_id" field.
func ExternalMessageIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldExternalMessageID, v))
}

// ExternalMessageIDGTE applies the GTE predicate on the "external_message_id" field.
func ExternalMessageIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldExternalMessageID, v))
}

// ExternalMessageIDLT applies the LT predicate on the "external_message_id" field.
func ExternalMessageIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldExternalMessageID, v))
}

// ExternalMessageIDLTE applies the LTE predicate on the "external_message_id" field.
func ExternalMessageIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldExternalMessageID, v))
}

// ExternalMessageIDContains applies the Contains predicate on the "external_message_id" field.
func ExternalMessageIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldExternalMessageID, v))
}

// ExternalMessageIDHasPrefix applies the HasPrefix predicate on the "external_message_id" field.
func ExternalMessageIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldExternalMessageID, v))
}

// ExternalMessageIDHasSuffix applies the HasSuffix predicate on the "external_message_id" field.
func ExternalMessageIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldExternalMessageID, v))
}

// ExternalMessageIDEqualFold applies the EqualFold predicate on the "external_message_id" field.
func ExternalMessageIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldExternalMessageID, v))
}

// ExternalMessageIDContainsFold applies the ContainsFold predicate on the "external_message_id" field.
func ExternalMessageIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldExternalMessageID, v))
}

// MetadataJSONEQ applies the EQ predicate on the "metadata_json" field.
func MetadataJSONEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldMetadataJSON, v))
}

// MetadataJSONNEQ applies the NEQ predicate on the "metadata_json" field.
func MetadataJSONNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldMetadataJSON, v))
}

// MetadataJSONIn applies the In predicate on the "metadata_json" field.
func MetadataJSONIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldMetadataJSON, vs...))
}

// MetadataJSONNotIn applies the NotIn predicate on the "metadata_json" field.
func MetadataJSONNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldMetadataJSON, vs...))
}

// MetadataJSONGT applies the GT predicate on the "metadata_json" field.
func MetadataJSONGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldMetadataJSON, v))
}

// MetadataJSONGTE applies the GTE predicate on the "metadata_json" field.
func MetadataJSONGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldMetadataJSON, v))
}

// MetadataJSONLT applies the LT predicate on the "metadata_json" field.
func MetadataJSONLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldMetadataJSON, v))
}

// MetadataJSONLTE applies the LTE predicate on the "metadata_json" field.
func MetadataJSONLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldMetadataJSON, v))
}

// MetadataJSONContains applies the Contains predicate on the "metadata_json" field.
func MetadataJSONContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldMetadataJSON, v))
}

// MetadataJSONHasPrefix applies the HasPrefix predicate on the "metadata_json" field.
func MetadataJSONHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldMetadataJSON, v))
}

// MetadataJSONHasSuffix applies the HasSuffix predicate on the "metadata_json" field.
func MetadataJSONHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldMetadataJSON, v))
}

// MetadataJSONEqualFold applies the EqualFold predicate on the "metadata_json" field.
func MetadataJSONEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldMetadataJSON, v))
}

// MetadataJSONContainsFold applies the ContainsFold predicate on the "metadata_json" field.
func MetadataJSONContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldMetadataJSON, v))
}

// AttachmentsJSONEQ applies the EQ predicate on the "attachments_json" field.
func AttachmentsJSONEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldAttachmentsJSON, v))
}

// AttachmentsJSONNEQ applies the NEQ predicate on the "attachments_json" field.
func AttachmentsJSONNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldAttachmentsJSON, v))
}

// AttachmentsJSONIn applies the In predicate on the "attachments_json" field.
func AttachmentsJSONIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldAttachmentsJSON, vs...))
}

// AttachmentsJSONNotIn applies the NotIn predicate on the "attachments_json" field.
func AttachmentsJSONNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldAttachmentsJSON, vs...))
}

// AttachmentsJSONGT applies the GT predicate on the "attachments_json" field.
func AttachmentsJSONGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldAttachmentsJSON, v))
}

// AttachmentsJSONGTE applies the GTE predicate on the "attachments_json" field.
func AttachmentsJSONGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldAttachmentsJSON, v))
}

// AttachmentsJSONLT applies the LT predicate on the "attachments_json" field.
func AttachmentsJSONLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldAttachmentsJSON, v))
}

// AttachmentsJSONLTE applies the LTE predicate on the "attachments_json" field.
func AttachmentsJSONLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldAttachmentsJSON, v))
}

// AttachmentsJSONContains applies the Contains predicate on the "attachments_json" field.
func AttachmentsJSONContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldAttachmentsJSON, v))
}

// AttachmentsJSONHasPrefix applies the HasPrefix predicate on the "attachments_json" field.
func AttachmentsJSONHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldAttachmentsJSON, v))
}

// AttachmentsJSONHasSuffix applies the HasSuffix predicate on the "attachments_json" field.
func AttachmentsJSONHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldAttachmentsJSON, v))
}

// AttachmentsJSONEqualFold applies the EqualFold predicate on the "attachments_json" field.
func AttachmentsJSONEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldAttachmentsJSON, v))
}

// AttachmentsJSONContainsFold applies the ContainsFold predicate on the "attachments_json" field.
func AttachmentsJSONContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldAttachmentsJSON, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldRequestID, v))
}

// CreatedUnixEQ applies the EQ predicate on the "created_unix" field.
func CreatedUnixEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCreatedUnix, v))
}

// CreatedUnixNEQ applies the NEQ predicate on the "created_unix" field.
func CreatedUnixNEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldCreatedUnix, v))
}

// CreatedUnixIn applies the In predicate on the "created_unix" field.
func CreatedUnixIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldCreatedUnix, vs...))
}

// CreatedUnixNotIn applies the NotIn predicate on the "created_unix" field.
func CreatedUnixNotIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldCreatedUnix, vs...))
}

// CreatedUnixGT applies the GT predicate on the "created_unix" field.
func CreatedUnixGT(v int64) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldCreatedUnix, v))
}

// CreatedUnixGTE applies the GTE predicate on the "created_unix" field.
func CreatedUnixGTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldCreatedUnix, v))
}

// CreatedUnixLT applies the LT predicate on the "created_unix" field.
func CreatedUnixLT(v int64) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldCreatedUnix, v))
}

// CreatedUnixLTE applies the LTE predicate on the "created_unix" field.
func CreatedUnixLTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldCreatedUnix, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Message) predicate.Message {
	return predicate.Message(sql.NotPredicates(p))
}
