// Code generated by ent, DO NOT EDIT.

package channelmember

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the channelmember type in the database.
	Label = "channel_member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldMemberID holds the string denoting the member_id field in the database.
	FieldMemberID = "member_id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldJoinedTimeUnix holds the string denoting the joined_time_unix field in the database.
	FieldJoinedTimeUnix = "joined_time_unix"
	// FieldUpdatedUnix holds the string denoting the updated_unix field in the database.
	FieldUpdatedUnix = "updated_unix"
	// Table holds the table name of the channelmember in the database.
	Table = "channel_members"
)

// Columns holds all SQL columns for channelmember fields.
var Columns = []string{
	FieldID,
	FieldTarget,
	FieldMemberID,
	FieldUsername,
	FieldDisplayName,
	FieldKind,
	FieldRole,
	FieldJoinedTimeUnix,
	FieldUpdatedUnix,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TargetValidator is a validator for the "target" field. It is called by the builders before save.
	TargetValidator func(string) error
	// MemberIDValidator is a validator for the "member_id" field. It is called by the builders before save.
	MemberIDValidator func(string) error
	// DefaultUsername holds the default value on creation for the "username" field.
	DefaultUsername string
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// DefaultKind holds the default value on creation for the "kind" field.
	DefaultKind string
	// DefaultRole holds the default value on creation for the "role" field.
	DefaultRole string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the ChannelMember queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByMemberID orders the results by the member_id field.
func ByMemberID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemberID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByJoinedTimeUnix orders the results by the joined_time_unix field.
func ByJoinedTimeUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJoinedTimeUnix, opts...).ToFunc()
}

// ByUpdatedUnix orders the results by the updated_unix field.
func ByUpdatedUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedUnix, opts...).ToFunc()
}
