// Code generated by ent, DO NOT EDIT.

package agentrun

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the agentrun type in the database.
	Label = "agent_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAgentID holds the string denoting the agent_id field in the database.
	FieldAgentID = "agent_id"
	// FieldComputerID holds the string denoting the computer_id field in the database.
	FieldComputerID = "computer_id"
	// FieldStartedUnix holds the string denoting the started_unix field in the database.
	FieldStartedUnix = "started_unix"
	// FieldEndedUnix holds the string denoting the ended_unix field in the database.
	FieldEndedUnix = "ended_unix"
	// FieldExitCode holds the string denoting the exit_code field in the database.
	FieldExitCode = "exit_code"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldEventCount holds the string denoting the event_count field in the database.
	FieldEventCount = "event_count"
	// Table holds the table name of the agentrun in the database.
	Table = "agent_runs"
)

// Columns holds all SQL columns for agentrun fields.
var Columns = []string{
	FieldID,
	FieldAgentID,
	FieldComputerID,
	FieldStartedUnix,
	FieldEndedUnix,
	FieldExitCode,
	FieldSummary,
	FieldError,
	FieldEventCount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AgentIDValidator is a validator for the "agent_id" field. It is called by the builders before save.
	AgentIDValidator func(string) error
	// ComputerIDValidator is a validator for the "computer_id" field. It is called by the builders before save.
	ComputerIDValidator func(string) error
	// DefaultEndedUnix holds the default value on creation for the "ended_unix" field.
	DefaultEndedUnix int64
	// DefaultExitCode holds the default value on creation for the "exit_code" field.
	DefaultExitCode int32
	// DefaultSummary holds the default value on creation for the "summary" field.
	DefaultSummary string
	// DefaultError holds the default value on creation for the "error" field.
	DefaultError string
	// DefaultEventCount holds the default value on creation for the "event_count" field.
	DefaultEventCount uint32
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the AgentRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAgentID orders the results by the agent_id field.
func ByAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentID, opts...).ToFunc()
}

// ByComputerID orders the results by the computer_id field.
func ByComputerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComputerID, opts...).ToFunc()
}

// ByStartedUnix orders the results by the started_unix field.
func ByStartedUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedUnix, opts...).ToFunc()
}

// ByEndedUnix orders the results by the ended_unix field.
func ByEndedUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndedUnix, opts...).ToFunc()
}

// ByExitCode orders the results by the exit_code field.
func ByExitCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExitCode, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByEventCount orders the results by the event_count field.
func ByEventCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventCount, opts...).ToFunc()
}
