// Code generated by ent, DO NOT EDIT.

package agentrun

import (
	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/nekode/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldContainsFold(FieldID, id))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldAgentID, v))
}

// ComputerID applies equality check predicate on the "computer_id" field. It's identical to ComputerIDEQ.
func ComputerID(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldComputerID, v))
}

// StartedUnix applies equality check predicate on the "started_unix" field. It's identical to StartedUnixEQ.
func StartedUnix(v int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldStartedUnix, v))
}

// EndedUnix applies equality check predicate on the "ended_unix" field. It's identical to EndedUnixEQ.
func EndedUnix(v int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldEndedUnix, v))
}

// ExitCode applies equality check predicate on the "exit_code" field. It's identical to ExitCodeEQ.
func ExitCode(v int32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldExitCode, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldSummary, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldError, v))
}

// EventCount applies equality check predicate on the "event_count" field. It's identical to EventCountEQ.
func EventCount(v uint32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldEventCount, v))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNotIn(FieldAgentID, vs...))
}

// AgentIDGT applies the GT predicate on the "agent_id" field.
func AgentIDGT(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGT(FieldAgentID, v))
}

// AgentIDGTE applies the GTE predicate on the "agent_id" field.
func AgentIDGTE(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGTE(FieldAgentID, v))
}

// AgentIDLT applies the LT predicate on the "agent_id" field.
func AgentIDLT(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLT(FieldAgentID, v))
}

// AgentIDLTE applies the LTE predicate on the "agent_id" field.
func AgentIDLTE(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLTE(FieldAgentID, v))
}

// AgentIDContains applies the Contains predicate on the "agent_id" field.
func AgentIDContains(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldContains(FieldAgentID, v))
}

// AgentIDHasPrefix applies the HasPrefix predicate on the "agent_id" field.
func AgentIDHasPrefix(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldHasPrefix(FieldAgentID, v))
}

// AgentIDHasSuffix applies the HasSuffix predicate on the "agent_id" field.
func AgentIDHasSuffix(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldHasSuffix(FieldAgentID, v))
}

// AgentIDEqualFold applies the EqualFold predicate on the "agent_id" field.
func AgentIDEqualFold(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEqualFold(FieldAgentID, v))
}

// AgentIDContainsFold applies the ContainsFold predicate on the "agent_id" field.
func AgentIDContainsFold(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldContainsFold(FieldAgentID, v))
}

// ComputerIDEQ applies the EQ predicate on the "computer_id" field.
func ComputerIDEQ(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldComputerID, v))
}

// ComputerIDNEQ applies the NEQ predicate on the "computer_id" field.
func ComputerIDNEQ(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNEQ(FieldComputerID, v))
}

// ComputerIDIn applies the In predicate on the "computer_id" field.
func ComputerIDIn(vs ...string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldIn(FieldComputerID, vs...))
}

// ComputerIDNotIn applies the NotIn predicate on the "computer_id" field.
func ComputerIDNotIn(vs ...string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNotIn(FieldComputerID, vs...))
}

// ComputerIDGT applies the GT predicate on the "computer_id" field.
func ComputerIDGT(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGT(FieldComputerID, v))
}

// ComputerIDGTE applies the GTE predicate on the "computer_id" field.
func ComputerIDGTE(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGTE(FieldComputerID, v))
}

// ComputerIDLT applies the LT predicate on the "computer_id" field.
func ComputerIDLT(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLT(FieldComputerID, v))
}

// ComputerIDLTE applies the LTE predicate on the "computer_id" field.
func ComputerIDLTE(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLTE(FieldComputerID, v))
}

// ComputerIDContains applies the Contains predicate on the "computer_id" field.
func ComputerIDContains(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldContains(FieldComputerID, v))
}

// ComputerIDHasPrefix applies the HasPrefix predicate on the "computer_id" field.
func ComputerIDHasPrefix(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldHasPrefix(FieldComputerID, v))
}

// ComputerIDHasSuffix applies the HasSuffix predicate on the "computer_id" field.
func ComputerIDHasSuffix(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldHasSuffix(FieldComputerID, v))
}

// ComputerIDEqualFold applies the EqualFold predicate on the "computer_id" field.
func ComputerIDEqualFold(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEqualFold(FieldComputerID, v))
}

// ComputerIDContainsFold applies the ContainsFold predicate on the "computer_id" field.
func ComputerIDContainsFold(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldContainsFold(FieldComputerID, v))
}

// StartedUnixEQ applies the EQ predicate on the "started_unix" field.
func StartedUnixEQ(v int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldStartedUnix, v))
}

// StartedUnixNEQ applies the NEQ predicate on the "started_unix" field.
func StartedUnixNEQ(v int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNEQ(FieldStartedUnix, v))
}

// StartedUnixIn applies the In predicate on the "started_unix" field.
func StartedUnixIn(vs ...int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldIn(FieldStartedUnix, vs...))
}

// StartedUnixNotIn applies the NotIn predicate on the "started_unix" field.
func StartedUnixNotIn(vs ...int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNotIn(FieldStartedUnix, vs...))
}

// StartedUnixGT applies the GT predicate on the "started_unix" field.
func StartedUnixGT(v int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGT(FieldStartedUnix, v))
}

// StartedUnixGTE applies the GTE predicate on the "started_unix" field.
func StartedUnixGTE(v int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGTE(FieldStartedUnix, v))
}

// StartedUnixLT applies the LT predicate on the "started_unix" field.
func StartedUnixLT(v int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLT(FieldStartedUnix, v))
}

// StartedUnixLTE applies the LTE predicate on the "started_unix" field.
func StartedUnixLTE(v int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLTE(FieldStartedUnix, v))
}

// EndedUnixEQ applies the EQ predicate on the "ended_unix" field.
func EndedUnixEQ(v int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldEndedUnix, v))
}

// EndedUnixNEQ applies the NEQ predicate on the "ended_unix" field.
func EndedUnixNEQ(v int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNEQ(FieldEndedUnix, v))
}

// EndedUnixIn applies the In predicate on the "ended_unix" field.
func EndedUnixIn(vs ...int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldIn(FieldEndedUnix, vs...))
}

// EndedUnixNotIn applies the NotIn predicate on the "ended_unix" field.
func EndedUnixNotIn(vs ...int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNotIn(FieldEndedUnix, vs...))
}

// EndedUnixGT applies the GT predicate on the "ended_unix" field.
func EndedUnixGT(v int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGT(FieldEndedUnix, v))
}

// EndedUnixGTE applies the GTE predicate on the "ended_unix" field.
func EndedUnixGTE(v int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGTE(FieldEndedUnix, v))
}

// EndedUnixLT applies the LT predicate on the "ended_unix" field.
func EndedUnixLT(v int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLT(FieldEndedUnix, v))
}

// EndedUnixLTE applies the LTE predicate on the "ended_unix" field.
func EndedUnixLTE(v int64) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLTE(FieldEndedUnix, v))
}

// ExitCodeEQ applies the EQ predicate on the "exit_code" field.
func ExitCodeEQ(v int32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldExitCode, v))
}

// ExitCodeNEQ applies the NEQ predicate on the "exit_code" field.
func ExitCodeNEQ(v int32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNEQ(FieldExitCode, v))
}

// ExitCodeIn applies the In predicate on the "exit_code" field.
func ExitCodeIn(vs ...int32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldIn(FieldExitCode, vs...))
}

// ExitCodeNotIn applies the NotIn predicate on the "exit_code" field.
func ExitCodeNotIn(vs ...int32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNotIn(FieldExitCode, vs...))
}

// ExitCodeGT applies the GT predicate on the "exit_code" field.
func ExitCodeGT(v int32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGT(FieldExitCode, v))
}

// ExitCodeGTE applies the GTE predicate on the "exit_code" field.
func ExitCodeGTE(v int32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGTE(FieldExitCode, v))
}

// ExitCodeLT applies the LT predicate on the "exit_code" field.
func ExitCodeLT(v int32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLT(FieldExitCode, v))
}

// ExitCodeLTE applies the LTE predicate on the "exit_code" field.
func ExitCodeLTE(v int32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLTE(FieldExitCode, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldContainsFold(FieldSummary, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldHasSuffix(FieldError, v))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldContainsFold(FieldError, v))
}

// EventCountEQ applies the EQ predicate on the "event_count" field.
func EventCountEQ(v uint32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldEQ(FieldEventCount, v))
}

// EventCountNEQ applies the NEQ predicate on the "event_count" field.
func EventCountNEQ(v uint32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNEQ(FieldEventCount, v))
}

// EventCountIn applies the In predicate on the "event_count" field.
func EventCountIn(vs ...uint32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldIn(FieldEventCount, vs...))
}

// EventCountNotIn applies the NotIn predicate on the "event_count" field.
func EventCountNotIn(vs ...uint32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldNotIn(FieldEventCount, vs...))
}

// EventCountGT applies the GT predicate on the "event_count" field.
func EventCountGT(v uint32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGT(FieldEventCount, v))
}

// EventCountGTE applies the GTE predicate on the "event_count" field.
func EventCountGTE(v uint32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldGTE(FieldEventCount, v))
}

// EventCountLT applies the LT predicate on the "event_count" field.
func EventCountLT(v uint32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLT(FieldEventCount, v))
}

// EventCountLTE applies the LTE predicate on the "event_count" field.
func EventCountLTE(v uint32) predicate.AgentRun {
	return predicate.AgentRun(sql.FieldLTE(FieldEventCount, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentRun) predicate.AgentRun {
	return predicate.AgentRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentRun) predicate.AgentRun {
	return predicate.AgentRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentRun) predicate.AgentRun {
	return predicate.AgentRun(sql.NotPredicates(p))
}
