// Code generated by ent, DO NOT EDIT.

package outbounddelivery

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the outbounddelivery type in the database.
	Label = "outbound_delivery"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldMessageID holds the string denoting the message_id field in the database.
	FieldMessageID = "message_id"
	// FieldEndpointID holds the string denoting the endpoint_id field in the database.
	FieldEndpointID = "endpoint_id"
	// FieldEndpointKind holds the string denoting the endpoint_kind field in the database.
	FieldEndpointKind = "endpoint_kind"
	// FieldExternalMessageID holds the string denoting the external_message_id field in the database.
	FieldExternalMessageID = "external_message_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAttemptCount holds the string denoting the attempt_count field in the database.
	FieldAttemptCount = "attempt_count"
	// FieldNextRetryTimeUnix holds the string denoting the next_retry_time_unix field in the database.
	FieldNextRetryTimeUnix = "next_retry_time_unix"
	// FieldDeliveredTimeUnix holds the string denoting the delivered_time_unix field in the database.
	FieldDeliveredTimeUnix = "delivered_time_unix"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldCreatedUnix holds the string denoting the created_unix field in the database.
	FieldCreatedUnix = "created_unix"
	// FieldUpdatedUnix holds the string denoting the updated_unix field in the database.
	FieldUpdatedUnix = "updated_unix"
	// Table holds the table name of the outbounddelivery in the database.
	Table = "outbound_deliveries"
)

// Columns holds all SQL columns for outbounddelivery fields.
var Columns = []string{
	FieldID,
	FieldTarget,
	FieldMessageID,
	FieldEndpointID,
	FieldEndpointKind,
	FieldExternalMessageID,
	FieldStatus,
	FieldAttemptCount,
	FieldNextRetryTimeUnix,
	FieldDeliveredTimeUnix,
	FieldLastError,
	FieldRequestID,
	FieldCreatedUnix,
	FieldUpdatedUnix,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TargetValidator is a validator for the "target" field. It is called by the builders before save.
	TargetValidator func(string) error
	// MessageIDValidator is a validator for the "message_id" field. It is called by the builders before save.
	MessageIDValidator func(string) error
	// EndpointIDValidator is a validator for the "endpoint_id" field. It is called by the builders before save.
	EndpointIDValidator func(string) error
	// DefaultEndpointKind holds the default value on creation for the "endpoint_kind" field.
	DefaultEndpointKind string
	// DefaultExternalMessageID holds the default value on creation for the "external_message_id" field.
	DefaultExternalMessageID string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultAttemptCount holds the default value on creation for the "attempt_count" field.
	DefaultAttemptCount uint32
	// DefaultNextRetryTimeUnix holds the default value on creation for the "next_retry_time_unix" field.
	DefaultNextRetryTimeUnix int64
	// DefaultDeliveredTimeUnix holds the default value on creation for the "delivered_time_unix" field.
	DefaultDeliveredTimeUnix int64
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultRequestID holds the default value on creation for the "request_id" field.
	DefaultRequestID string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the OutboundDelivery queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByMessageID orders the results by the message_id field.
func ByMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageID, opts...).ToFunc()
}

// ByEndpointID orders the results by the endpoint_id field.
func ByEndpointID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpointID, opts...).ToFunc()
}

// ByEndpointKind orders the results by the endpoint_kind field.
func ByEndpointKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpointKind, opts...).ToFunc()
}

// ByExternalMessageID orders the results by the external_message_id field.
func ByExternalMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalMessageID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAttemptCount orders the results by the attempt_count field.
func ByAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptCount, opts...).ToFunc()
}

// ByNextRetryTimeUnix orders the results by the next_retry_time_unix field.
func ByNextRetryTimeUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRetryTimeUnix, opts...).ToFunc()
}

// ByDeliveredTimeUnix orders the results by the delivered_time_unix field.
func ByDeliveredTimeUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveredTimeUnix, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByCreatedUnix orders the results by the created_unix field.
func ByCreatedUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedUnix, opts...).ToFunc()
}

// ByUpdatedUnix orders the results by the updated_unix field.
func ByUpdatedUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedUnix, opts...).ToFunc()
}
