// Code generated by ent, DO NOT EDIT.

package outbounddelivery

import (
	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/nekode/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContainsFold(FieldID, id))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldTarget, v))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldMessageID, v))
}

// EndpointID applies equality check predicate on the "endpoint_id" field. It's identical to EndpointIDEQ.
func EndpointID(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldEndpointID, v))
}

// EndpointKind applies equality check predicate on the "endpoint_kind" field. It's identical to EndpointKindEQ.
func EndpointKind(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldEndpointKind, v))
}

// ExternalMessageID applies equality check predicate on the "external_message_id" field. It's identical to ExternalMessageIDEQ.
func ExternalMessageID(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldExternalMessageID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldStatus, v))
}

// AttemptCount applies equality check predicate on the "attempt_count" field. It's identical to AttemptCountEQ.
func AttemptCount(v uint32) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldAttemptCount, v))
}

// NextRetryTimeUnix applies equality check predicate on the "next_retry_time_unix" field. It's identical to NextRetryTimeUnixEQ.
func NextRetryTimeUnix(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldNextRetryTimeUnix, v))
}

// DeliveredTimeUnix applies equality check predicate on the "delivered_time_unix" field. It's identical to DeliveredTimeUnixEQ.
func DeliveredTimeUnix(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldDeliveredTimeUnix, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldLastError, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldRequestID, v))
}

// CreatedUnix applies equality check predicate on the "created_unix" field. It's identical to CreatedUnixEQ.
func CreatedUnix(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldCreatedUnix, v))
}

// UpdatedUnix applies equality check predicate on the "updated_unix" field. It's identical to UpdatedUnixEQ.
func UpdatedUnix(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldUpdatedUnix, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContainsFold(FieldTarget, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDGT applies the GT predicate on the "message_id" field.
func MessageIDGT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGT(FieldMessageID, v))
}

// MessageIDGTE applies the GTE predicate on the "message_id" field.
func MessageIDGTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGTE(FieldMessageID, v))
}

// MessageIDLT applies the LT predicate on the "message_id" field.
func MessageIDLT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLT(FieldMessageID, v))
}

// MessageIDLTE applies the LTE predicate on the "message_id" field.
func MessageIDLTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLTE(FieldMessageID, v))
}

// MessageIDContains applies the Contains predicate on the "message_id" field.
func MessageIDContains(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContains(FieldMessageID, v))
}

// MessageIDHasPrefix applies the HasPrefix predicate on the "message_id" field.
func MessageIDHasPrefix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasPrefix(FieldMessageID, v))
}

// MessageIDHasSuffix applies the HasSuffix predicate on the "message_id" field.
func MessageIDHasSuffix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasSuffix(FieldMessageID, v))
}

// MessageIDEqualFold applies the EqualFold predicate on the "message_id" field.
func MessageIDEqualFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEqualFold(FieldMessageID, v))
}

// MessageIDContainsFold applies the ContainsFold predicate on the "message_id" field.
func MessageIDContainsFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContainsFold(FieldMessageID, v))
}

// EndpointIDEQ applies the EQ predicate on the "endpoint_id" field.
func EndpointIDEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldEndpointID, v))
}

// EndpointIDNEQ applies the NEQ predicate on the "endpoint_id" field.
func EndpointIDNEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNEQ(FieldEndpointID, v))
}

// EndpointIDIn applies the In predicate on the "endpoint_id" field.
func EndpointIDIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldIn(FieldEndpointID, vs...))
}

// EndpointIDNotIn applies the NotIn predicate on the "endpoint_id" field.
func EndpointIDNotIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNotIn(FieldEndpointID, vs...))
}

// EndpointIDGT applies the GT predicate on the "endpoint_id" field.
func EndpointIDGT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGT(FieldEndpointID, v))
}

// EndpointIDGTE applies the GTE predicate on the "endpoint_id" field.
func EndpointIDGTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGTE(FieldEndpointID, v))
}

// EndpointIDLT applies the LT predicate on the "endpoint_id" field.
func EndpointIDLT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLT(FieldEndpointID, v))
}

// EndpointIDLTE applies the LTE predicate on the "endpoint_id" field.
func EndpointIDLTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLTE(FieldEndpointID, v))
}

// EndpointIDContains applies the Contains predicate on the "endpoint_id" field.
func EndpointIDContains(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContains(FieldEndpointID, v))
}

// EndpointIDHasPrefix applies the HasPrefix predicate on the "endpoint_id" field.
func EndpointIDHasPrefix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasPrefix(FieldEndpointID, v))
}

// EndpointIDHasSuffix applies the HasSuffix predicate on the "endpoint_id" field.
func EndpointIDHasSuffix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasSuffix(FieldEndpointID, v))
}

// EndpointIDEqualFold applies the EqualFold predicate on the "endpoint_id" field.
func EndpointIDEqualFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEqualFold(FieldEndpointID, v))
}

// EndpointIDContainsFold applies the ContainsFold predicate on the "endpoint_id" field.
func EndpointIDContainsFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContainsFold(FieldEndpointID, v))
}

// EndpointKindEQ applies the EQ predicate on the "endpoint_kind" field.
func EndpointKindEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldEndpointKind, v))
}

// EndpointKindNEQ applies the NEQ predicate on the "endpoint_kind" field.
func EndpointKindNEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNEQ(FieldEndpointKind, v))
}

// EndpointKindIn applies the In predicate on the "endpoint_kind" field.
func EndpointKindIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldIn(FieldEndpointKind, vs...))
}

// EndpointKindNotIn applies the NotIn predicate on the "endpoint_kind" field.
func EndpointKindNotIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNotIn(FieldEndpointKind, vs...))
}

// EndpointKindGT applies the GT predicate on the "endpoint_kind" field.
func EndpointKindGT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGT(FieldEndpointKind, v))
}

// EndpointKindGTE applies the GTE predicate on the "endpoint_kind" field.
func EndpointKindGTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGTE(FieldEndpointKind, v))
}

// EndpointKindLT applies the LT predicate on the "endpoint_kind" field.
func EndpointKindLT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLT(FieldEndpointKind, v))
}

// EndpointKindLTE applies the LTE predicate on the "endpoint_kind" field.
func EndpointKindLTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLTE(FieldEndpointKind, v))
}

// EndpointKindContains applies the Contains predicate on the "endpoint_kind" field.
func EndpointKindContains(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContains(FieldEndpointKind, v))
}

// EndpointKindHasPrefix applies the HasPrefix predicate on the "endpoint_kind" field.
func EndpointKindHasPrefix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasPrefix(FieldEndpointKind, v))
}

// EndpointKindHasSuffix applies the HasSuffix predicate on the "endpoint_kind" field.
func EndpointKindHasSuffix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasSuffix(FieldEndpointKind, v))
}

// EndpointKindEqualFold applies the EqualFold predicate on the "endpoint_kind" field.
func EndpointKindEqualFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEqualFold(FieldEndpointKind, v))
}

// EndpointKindContainsFold applies the ContainsFold predicate on the "endpoint_kind" field.
func EndpointKindContainsFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContainsFold(FieldEndpointKind, v))
}

// ExternalMessageIDEQ applies the EQ predicate on the "external_message_id" field.
func ExternalMessageIDEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldExternalMessageID, v))
}

// ExternalMessageIDNEQ applies the NEQ predicate on the "external_message_id" field.
func ExternalMessageIDNEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNEQ(FieldExternalMessageID, v))
}

// ExternalMessageIDIn applies the In predicate on the "external_message_id" field.
func ExternalMessageIDIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldIn(FieldExternalMessageID, vs...))
}

// ExternalMessageIDNotIn applies the NotIn predicate on the "external_message_id" field.
func ExternalMessageIDNotIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNotIn(FieldExternalMessageID, vs...))
}

// ExternalMessageIDGT applies the GT predicate on the "external_message_id" field.
func ExternalMessageIDGT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGT(FieldExternalMessageID, v))
}

// ExternalMessageIDGTE applies the GTE predicate on the "external_message_id" field.
func ExternalMessageIDGTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGTE(FieldExternalMessageID, v))
}

// ExternalMessageIDLT applies the LT predicate on the "external_message_id" field.
func ExternalMessageIDLT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLT(FieldExternalMessageID, v))
}

// ExternalMessageIDLTE applies the LTE predicate on the "external_message_id" field.
func ExternalMessageIDLTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLTE(FieldExternalMessageID, v))
}

// ExternalMessageIDContains applies the Contains predicate on the "external_message_id" field.
func ExternalMessageIDContains(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContains(FieldExternalMessageID, v))
}

// ExternalMessageIDHasPrefix applies the HasPrefix predicate on the "external_message_id" field.
func ExternalMessageIDHasPrefix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasPrefix(FieldExternalMessageID, v))
}

// ExternalMessageIDHasSuffix applies the HasSuffix predicate on the "external_message_id" field.
func ExternalMessageIDHasSuffix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasSuffix(FieldExternalMessageID, v))
}

// ExternalMessageIDEqualFold applies the EqualFold predicate on the "external_message_id" field.
func ExternalMessageIDEqualFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEqualFold(FieldExternalMessageID, v))
}

// ExternalMessageIDContainsFold applies the ContainsFold predicate on the "external_message_id" field.
func ExternalMessageIDContainsFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContainsFold(FieldExternalMessageID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContainsFold(FieldStatus, v))
}

// AttemptCountEQ applies the EQ predicate on the "attempt_count" field.
func AttemptCountEQ(v uint32) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldAttemptCount, v))
}

// AttemptCountNEQ applies the NEQ predicate on the "attempt_count" field.
func AttemptCountNEQ(v uint32) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNEQ(FieldAttemptCount, v))
}

// AttemptCountIn applies the In predicate on the "attempt_count" field.
func AttemptCountIn(vs ...uint32) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldIn(FieldAttemptCount, vs...))
}

// AttemptCountNotIn applies the NotIn predicate on the "attempt_count" field.
func AttemptCountNotIn(vs ...uint32) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNotIn(FieldAttemptCount, vs...))
}

// AttemptCountGT applies the GT predicate on the "attempt_count" field.
func AttemptCountGT(v uint32) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGT(FieldAttemptCount, v))
}

// AttemptCountGTE applies the GTE predicate on the "attempt_count" field.
func AttemptCountGTE(v uint32) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGTE(FieldAttemptCount, v))
}

// AttemptCountLT applies the LT predicate on the "attempt_count" field.
func AttemptCountLT(v uint32) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLT(FieldAttemptCount, v))
}

// AttemptCountLTE applies the LTE predicate on the "attempt_count" field.
func AttemptCountLTE(v uint32) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLTE(FieldAttemptCount, v))
}

// NextRetryTimeUnixEQ applies the EQ predicate on the "next_retry_time_unix" field.
func NextRetryTimeUnixEQ(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldNextRetryTimeUnix, v))
}

// NextRetryTimeUnixNEQ applies the NEQ predicate on the "next_retry_time_unix" field.
func NextRetryTimeUnixNEQ(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNEQ(FieldNextRetryTimeUnix, v))
}

// NextRetryTimeUnixIn applies the In predicate on the "next_retry_time_unix" field.
func NextRetryTimeUnixIn(vs ...int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldIn(FieldNextRetryTimeUnix, vs...))
}

// NextRetryTimeUnixNotIn applies the NotIn predicate on the "next_retry_time_unix" field.
func NextRetryTimeUnixNotIn(vs ...int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNotIn(FieldNextRetryTimeUnix, vs...))
}

// NextRetryTimeUnixGT applies the GT predicate on the "next_retry_time_unix" field.
func NextRetryTimeUnixGT(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGT(FieldNextRetryTimeUnix, v))
}

// NextRetryTimeUnixGTE applies the GTE predicate on the "next_retry_time_unix" field.
func NextRetryTimeUnixGTE(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGTE(FieldNextRetryTimeUnix, v))
}

// NextRetryTimeUnixLT applies the LT predicate on the "next_retry_time_unix" field.
func NextRetryTimeUnixLT(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLT(FieldNextRetryTimeUnix, v))
}

// NextRetryTimeUnixLTE applies the LTE predicate on the "next_retry_time_unix" field.
func NextRetryTimeUnixLTE(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLTE(FieldNextRetryTimeUnix, v))
}

// DeliveredTimeUnixEQ applies the EQ predicate on the "delivered_time_unix" field.
func DeliveredTimeUnixEQ(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldDeliveredTimeUnix, v))
}

// DeliveredTimeUnixNEQ applies the NEQ predicate on the "delivered_time_unix" field.
func DeliveredTimeUnixNEQ(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNEQ(FieldDeliveredTimeUnix, v))
}

// DeliveredTimeUnixIn applies the In predicate on the "delivered_time_unix" field.
func DeliveredTimeUnixIn(vs ...int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldIn(FieldDeliveredTimeUnix, vs...))
}

// DeliveredTimeUnixNotIn applies the NotIn predicate on the "delivered_time_unix" field.
func DeliveredTimeUnixNotIn(vs ...int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNotIn(FieldDeliveredTimeUnix, vs...))
}

// DeliveredTimeUnixGT applies the GT predicate on the "delivered_time_unix" field.
func DeliveredTimeUnixGT(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGT(FieldDeliveredTimeUnix, v))
}

// DeliveredTimeUnixGTE applies the GTE predicate on the "delivered_time_unix" field.
func DeliveredTimeUnixGTE(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGTE(FieldDeliveredTimeUnix, v))
}

// DeliveredTimeUnixLT applies the LT predicate on the "delivered_time_unix" field.
func DeliveredTimeUnixLT(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLT(FieldDeliveredTimeUnix, v))
}

// DeliveredTimeUnixLTE applies the LTE predicate on the "delivered_time_unix" field.
func DeliveredTimeUnixLTE(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLTE(FieldDeliveredTimeUnix, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContainsFold(FieldLastError, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldContainsFold(FieldRequestID, v))
}

// CreatedUnixEQ applies the EQ predicate on the "created_unix" field.
func CreatedUnixEQ(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldCreatedUnix, v))
}

// CreatedUnixNEQ applies the NEQ predicate on the "created_unix" field.
func CreatedUnixNEQ(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNEQ(FieldCreatedUnix, v))
}

// CreatedUnixIn applies the In predicate on the "created_unix" field.
func CreatedUnixIn(vs ...int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldIn(FieldCreatedUnix, vs...))
}

// CreatedUnixNotIn applies the NotIn predicate on the "created_unix" field.
func CreatedUnixNotIn(vs ...int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNotIn(FieldCreatedUnix, vs...))
}

// CreatedUnixGT applies the GT predicate on the "created_unix" field.
func CreatedUnixGT(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGT(FieldCreatedUnix, v))
}

// CreatedUnixGTE applies the GTE predicate on the "created_unix" field.
func CreatedUnixGTE(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGTE(FieldCreatedUnix, v))
}

// CreatedUnixLT applies the LT predicate on the "created_unix" field.
func CreatedUnixLT(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLT(FieldCreatedUnix, v))
}

// CreatedUnixLTE applies the LTE predicate on the "created_unix" field.
func CreatedUnixLTE(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLTE(FieldCreatedUnix, v))
}

// UpdatedUnixEQ applies the EQ predicate on the "updated_unix" field.
func UpdatedUnixEQ(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldEQ(FieldUpdatedUnix, v))
}

// UpdatedUnixNEQ applies the NEQ predicate on the "updated_unix" field.
func UpdatedUnixNEQ(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNEQ(FieldUpdatedUnix, v))
}

// UpdatedUnixIn applies the In predicate on the "updated_unix" field.
func UpdatedUnixIn(vs ...int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldIn(FieldUpdatedUnix, vs...))
}

// UpdatedUnixNotIn applies the NotIn predicate on the "updated_unix" field.
func UpdatedUnixNotIn(vs ...int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldNotIn(FieldUpdatedUnix, vs...))
}

// UpdatedUnixGT applies the GT predicate on the "updated_unix" field.
func UpdatedUnixGT(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGT(FieldUpdatedUnix, v))
}

// UpdatedUnixGTE applies the GTE predicate on the "updated_unix" field.
func UpdatedUnixGTE(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldGTE(FieldUpdatedUnix, v))
}

// UpdatedUnixLT applies the LT predicate on the "updated_unix" field.
func UpdatedUnixLT(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLT(FieldUpdatedUnix, v))
}

// UpdatedUnixLTE applies the LTE predicate on the "updated_unix" field.
func UpdatedUnixLTE(v int64) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.FieldLTE(FieldUpdatedUnix, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OutboundDelivery) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OutboundDelivery) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OutboundDelivery) predicate.OutboundDelivery {
	return predicate.OutboundDelivery(sql.NotPredicates(p))
}
