// Code generated by ent, DO NOT EDIT.

package imchatsubscription

import (
	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/nekode/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContainsFold(FieldID, id))
}

// EndpointID applies equality check predicate on the "endpoint_id" field. It's identical to EndpointIDEQ.
func EndpointID(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldEndpointID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldProvider, v))
}

// ConversationID applies equality check predicate on the "conversation_id" field. It's identical to ConversationIDEQ.
func ConversationID(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldConversationID, v))
}

// ExternalThreadID applies equality check predicate on the "external_thread_id" field. It's identical to ExternalThreadIDEQ.
func ExternalThreadID(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldExternalThreadID, v))
}

// ChatTitle applies equality check predicate on the "chat_title" field. It's identical to ChatTitleEQ.
func ChatTitle(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldChatTitle, v))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldTarget, v))
}

// ThreadID applies equality check predicate on the "thread_id" field. It's identical to ThreadIDEQ.
func ThreadID(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldThreadID, v))
}

// SenderExternalID applies equality check predicate on the "sender_external_id" field. It's identical to SenderExternalIDEQ.
func SenderExternalID(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldSenderExternalID, v))
}

// AuthorizedByRequestID applies equality check predicate on the "authorized_by_request_id" field. It's identical to AuthorizedByRequestIDEQ.
func AuthorizedByRequestID(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldAuthorizedByRequestID, v))
}

// Subscribed applies equality check predicate on the "subscribed" field. It's identical to SubscribedEQ.
func Subscribed(v bool) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldSubscribed, v))
}

// Verbose applies equality check predicate on the "verbose" field. It's identical to VerboseEQ.
func Verbose(v bool) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldVerbose, v))
}

// AuthorizedUnix applies equality check predicate on the "authorized_unix" field. It's identical to AuthorizedUnixEQ.
func AuthorizedUnix(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldAuthorizedUnix, v))
}

// SubscribedUnix applies equality check predicate on the "subscribed_unix" field. It's identical to SubscribedUnixEQ.
func SubscribedUnix(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldSubscribedUnix, v))
}

// CreatedUnix applies equality check predicate on the "created_unix" field. It's identical to CreatedUnixEQ.
func CreatedUnix(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldCreatedUnix, v))
}

// UpdatedUnix applies equality check predicate on the "updated_unix" field. It's identical to UpdatedUnixEQ.
func UpdatedUnix(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldUpdatedUnix, v))
}

// EndpointIDEQ applies the EQ predicate on the "endpoint_id" field.
func EndpointIDEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldEndpointID, v))
}

// EndpointIDNEQ applies the NEQ predicate on the "endpoint_id" field.
func EndpointIDNEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldEndpointID, v))
}

// EndpointIDIn applies the In predicate on the "endpoint_id" field.
func EndpointIDIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldIn(FieldEndpointID, vs...))
}

// EndpointIDNotIn applies the NotIn predicate on the "endpoint_id" field.
func EndpointIDNotIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNotIn(FieldEndpointID, vs...))
}

// EndpointIDGT applies the GT predicate on the "endpoint_id" field.
func EndpointIDGT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGT(FieldEndpointID, v))
}

// EndpointIDGTE applies the GTE predicate on the "endpoint_id" field.
func EndpointIDGTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGTE(FieldEndpointID, v))
}

// EndpointIDLT applies the LT predicate on the "endpoint_id" field.
func EndpointIDLT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLT(FieldEndpointID, v))
}

// EndpointIDLTE applies the LTE predicate on the "endpoint_id" field.
func EndpointIDLTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLTE(FieldEndpointID, v))
}

// EndpointIDContains applies the Contains predicate on the "endpoint_id" field.
func EndpointIDContains(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContains(FieldEndpointID, v))
}

// EndpointIDHasPrefix applies the HasPrefix predicate on the "endpoint_id" field.
func EndpointIDHasPrefix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasPrefix(FieldEndpointID, v))
}

// EndpointIDHasSuffix applies the HasSuffix predicate on the "endpoint_id" field.
func EndpointIDHasSuffix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasSuffix(FieldEndpointID, v))
}

// EndpointIDEqualFold applies the EqualFold predicate on the "endpoint_id" field.
func EndpointIDEqualFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEqualFold(FieldEndpointID, v))
}

// EndpointIDContainsFold applies the ContainsFold predicate on the "endpoint_id" field.
func EndpointIDContainsFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContainsFold(FieldEndpointID, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContainsFold(FieldProvider, v))
}

// ConversationIDEQ applies the EQ predicate on the "conversation_id" field.
func ConversationIDEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldConversationID, v))
}

// ConversationIDNEQ applies the NEQ predicate on the "conversation_id" field.
func ConversationIDNEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldConversationID, v))
}

// ConversationIDIn applies the In predicate on the "conversation_id" field.
func ConversationIDIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldIn(FieldConversationID, vs...))
}

// ConversationIDNotIn applies the NotIn predicate on the "conversation_id" field.
func ConversationIDNotIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNotIn(FieldConversationID, vs...))
}

// ConversationIDGT applies the GT predicate on the "conversation_id" field.
func ConversationIDGT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGT(FieldConversationID, v))
}

// ConversationIDGTE applies the GTE predicate on the "conversation_id" field.
func ConversationIDGTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGTE(FieldConversationID, v))
}

// ConversationIDLT applies the LT predicate on the "conversation_id" field.
func ConversationIDLT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLT(FieldConversationID, v))
}

// ConversationIDLTE applies the LTE predicate on the "conversation_id" field.
func ConversationIDLTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLTE(FieldConversationID, v))
}

// ConversationIDContains applies the Contains predicate on the "conversation_id" field.
func ConversationIDContains(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContains(FieldConversationID, v))
}

// ConversationIDHasPrefix applies the HasPrefix predicate on the "conversation_id" field.
func ConversationIDHasPrefix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasPrefix(FieldConversationID, v))
}

// ConversationIDHasSuffix applies the HasSuffix predicate on the "conversation_id" field.
func ConversationIDHasSuffix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasSuffix(FieldConversationID, v))
}

// ConversationIDEqualFold applies the EqualFold predicate on the "conversation_id" field.
func ConversationIDEqualFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEqualFold(FieldConversationID, v))
}

// ConversationIDContainsFold applies the ContainsFold predicate on the "conversation_id" field.
func ConversationIDContainsFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContainsFold(FieldConversationID, v))
}

// ExternalThreadIDEQ applies the EQ predicate on the "external_thread_id" field.
func ExternalThreadIDEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldExternalThreadID, v))
}

// ExternalThreadIDNEQ applies the NEQ predicate on the "external_thread_id" field.
func ExternalThreadIDNEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldExternalThreadID, v))
}

// ExternalThreadIDIn applies the In predicate on the "external_thread_id" field.
func ExternalThreadIDIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldIn(FieldExternalThreadID, vs...))
}

// ExternalThreadIDNotIn applies the NotIn predicate on the "external_thread_id" field.
func ExternalThreadIDNotIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNotIn(FieldExternalThreadID, vs...))
}

// ExternalThreadIDGT applies the GT predicate on the "external_thread_id" field.
func ExternalThreadIDGT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGT(FieldExternalThreadID, v))
}

// ExternalThreadIDGTE applies the GTE predicate on the "external_thread_id" field.
func ExternalThreadIDGTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGTE(FieldExternalThreadID, v))
}

// ExternalThreadIDLT applies the LT predicate on the "external_thread_id" field.
func ExternalThreadIDLT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLT(FieldExternalThreadID, v))
}

// ExternalThreadIDLTE applies the LTE predicate on the "external_thread_id" field.
func ExternalThreadIDLTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLTE(FieldExternalThreadID, v))
}

// ExternalThreadIDContains applies the Contains predicate on the "external_thread_id" field.
func ExternalThreadIDContains(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContains(FieldExternalThreadID, v))
}

// ExternalThreadIDHasPrefix applies the HasPrefix predicate on the "external_thread_id" field.
func ExternalThreadIDHasPrefix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasPrefix(FieldExternalThreadID, v))
}

// ExternalThreadIDHasSuffix applies the HasSuffix predicate on the "external_thread_id" field.
func ExternalThreadIDHasSuffix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasSuffix(FieldExternalThreadID, v))
}

// ExternalThreadIDEqualFold applies the EqualFold predicate on the "external_thread_id" field.
func ExternalThreadIDEqualFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEqualFold(FieldExternalThreadID, v))
}

// ExternalThreadIDContainsFold applies the ContainsFold predicate on the "external_thread_id" field.
func ExternalThreadIDContainsFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContainsFold(FieldExternalThreadID, v))
}

// ChatTitleEQ applies the EQ predicate on the "chat_title" field.
func ChatTitleEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldChatTitle, v))
}

// ChatTitleNEQ applies the NEQ predicate on the "chat_title" field.
func ChatTitleNEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldChatTitle, v))
}

// ChatTitleIn applies the In predicate on the "chat_title" field.
func ChatTitleIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldIn(FieldChatTitle, vs...))
}

// ChatTitleNotIn applies the NotIn predicate on the "chat_title" field.
func ChatTitleNotIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNotIn(FieldChatTitle, vs...))
}

// ChatTitleGT applies the GT predicate on the "chat_title" field.
func ChatTitleGT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGT(FieldChatTitle, v))
}

// ChatTitleGTE applies the GTE predicate on the "chat_title" field.
func ChatTitleGTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGTE(FieldChatTitle, v))
}

// ChatTitleLT applies the LT predicate on the "chat_title" field.
func ChatTitleLT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLT(FieldChatTitle, v))
}

// ChatTitleLTE applies the LTE predicate on the "chat_title" field.
func ChatTitleLTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLTE(FieldChatTitle, v))
}

// ChatTitleContains applies the Contains predicate on the "chat_title" field.
func ChatTitleContains(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContains(FieldChatTitle, v))
}

// ChatTitleHasPrefix applies the HasPrefix predicate on the "chat_title" field.
func ChatTitleHasPrefix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasPrefix(FieldChatTitle, v))
}

// ChatTitleHasSuffix applies the HasSuffix predicate on the "chat_title" field.
func ChatTitleHasSuffix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasSuffix(FieldChatTitle, v))
}

// ChatTitleEqualFold applies the EqualFold predicate on the "chat_title" field.
func ChatTitleEqualFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEqualFold(FieldChatTitle, v))
}

// ChatTitleContainsFold applies the ContainsFold predicate on the "chat_title" field.
func ChatTitleContainsFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContainsFold(FieldChatTitle, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContainsFold(FieldTarget, v))
}

// ThreadIDEQ applies the EQ predicate on the "thread_id" field.
func ThreadIDEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldThreadID, v))
}

// ThreadIDNEQ applies the NEQ predicate on the "thread_id" field.
func ThreadIDNEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldThreadID, v))
}

// ThreadIDIn applies the In predicate on the "thread_id" field.
func ThreadIDIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldIn(FieldThreadID, vs...))
}

// ThreadIDNotIn applies the NotIn predicate on the "thread_id" field.
func ThreadIDNotIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNotIn(FieldThreadID, vs...))
}

// ThreadIDGT applies the GT predicate on the "thread_id" field.
func ThreadIDGT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGT(FieldThreadID, v))
}

// ThreadIDGTE applies the GTE predicate on the "thread_id" field.
func ThreadIDGTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGTE(FieldThreadID, v))
}

// ThreadIDLT applies the LT predicate on the "thread_id" field.
func ThreadIDLT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLT(FieldThreadID, v))
}

// ThreadIDLTE applies the LTE predicate on the "thread_id" field.
func ThreadIDLTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLTE(FieldThreadID, v))
}

// ThreadIDContains applies the Contains predicate on the "thread_id" field.
func ThreadIDContains(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContains(FieldThreadID, v))
}

// ThreadIDHasPrefix applies the HasPrefix predicate on the "thread_id" field.
func ThreadIDHasPrefix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasPrefix(FieldThreadID, v))
}

// ThreadIDHasSuffix applies the HasSuffix predicate on the "thread_id" field.
func ThreadIDHasSuffix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasSuffix(FieldThreadID, v))
}

// ThreadIDEqualFold applies the EqualFold predicate on the "thread_id" field.
func ThreadIDEqualFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEqualFold(FieldThreadID, v))
}

// ThreadIDContainsFold applies the ContainsFold predicate on the "thread_id" field.
func ThreadIDContainsFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContainsFold(FieldThreadID, v))
}

// SenderExternalIDEQ applies the EQ predicate on the "sender_external_id" field.
func SenderExternalIDEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldSenderExternalID, v))
}

// SenderExternalIDNEQ applies the NEQ predicate on the "sender_external_id" field.
func SenderExternalIDNEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldSenderExternalID, v))
}

// SenderExternalIDIn applies the In predicate on the "sender_external_id" field.
func SenderExternalIDIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldIn(FieldSenderExternalID, vs...))
}

// SenderExternalIDNotIn applies the NotIn predicate on the "sender_external_id" field.
func SenderExternalIDNotIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNotIn(FieldSenderExternalID, vs...))
}

// SenderExternalIDGT applies the GT predicate on the "sender_external_id" field.
func SenderExternalIDGT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGT(FieldSenderExternalID, v))
}

// SenderExternalIDGTE applies the GTE predicate on the "sender_external_id" field.
func SenderExternalIDGTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGTE(FieldSenderExternalID, v))
}

// SenderExternalIDLT applies the LT predicate on the "sender_external_id" field.
func SenderExternalIDLT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLT(FieldSenderExternalID, v))
}

// SenderExternalIDLTE applies the LTE predicate on the "sender_external_id" field.
func SenderExternalIDLTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLTE(FieldSenderExternalID, v))
}

// SenderExternalIDContains applies the Contains predicate on the "sender_external_id" field.
func SenderExternalIDContains(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContains(FieldSenderExternalID, v))
}

// SenderExternalIDHasPrefix applies the HasPrefix predicate on the "sender_external_id" field.
func SenderExternalIDHasPrefix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasPrefix(FieldSenderExternalID, v))
}

// SenderExternalIDHasSuffix applies the HasSuffix predicate on the "sender_external_id" field.
func SenderExternalIDHasSuffix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasSuffix(FieldSenderExternalID, v))
}

// SenderExternalIDEqualFold applies the EqualFold predicate on the "sender_external_id" field.
func SenderExternalIDEqualFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEqualFold(FieldSenderExternalID, v))
}

// SenderExternalIDContainsFold applies the ContainsFold predicate on the "sender_external_id" field.
func SenderExternalIDContainsFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContainsFold(FieldSenderExternalID, v))
}

// AuthorizedByRequestIDEQ applies the EQ predicate on the "authorized_by_request_id" field.
func AuthorizedByRequestIDEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldAuthorizedByRequestID, v))
}

// AuthorizedByRequestIDNEQ applies the NEQ predicate on the "authorized_by_request_id" field.
func AuthorizedByRequestIDNEQ(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldAuthorizedByRequestID, v))
}

// AuthorizedByRequestIDIn applies the In predicate on the "authorized_by_request_id" field.
func AuthorizedByRequestIDIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldIn(FieldAuthorizedByRequestID, vs...))
}

// AuthorizedByRequestIDNotIn applies the NotIn predicate on the "authorized_by_request_id" field.
func AuthorizedByRequestIDNotIn(vs ...string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNotIn(FieldAuthorizedByRequestID, vs...))
}

// AuthorizedByRequestIDGT applies the GT predicate on the "authorized_by_request_id" field.
func AuthorizedByRequestIDGT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGT(FieldAuthorizedByRequestID, v))
}

// AuthorizedByRequestIDGTE applies the GTE predicate on the "authorized_by_request_id" field.
func AuthorizedByRequestIDGTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGTE(FieldAuthorizedByRequestID, v))
}

// AuthorizedByRequestIDLT applies the LT predicate on the "authorized_by_request_id" field.
func AuthorizedByRequestIDLT(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLT(FieldAuthorizedByRequestID, v))
}

// AuthorizedByRequestIDLTE applies the LTE predicate on the "authorized_by_request_id" field.
func AuthorizedByRequestIDLTE(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLTE(FieldAuthorizedByRequestID, v))
}

// AuthorizedByRequestIDContains applies the Contains predicate on the "authorized_by_request_id" field.
func AuthorizedByRequestIDContains(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContains(FieldAuthorizedByRequestID, v))
}

// AuthorizedByRequestIDHasPrefix applies the HasPrefix predicate on the "authorized_by_request_id" field.
func AuthorizedByRequestIDHasPrefix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasPrefix(FieldAuthorizedByRequestID, v))
}

// AuthorizedByRequestIDHasSuffix applies the HasSuffix predicate on the "authorized_by_request_id" field.
func AuthorizedByRequestIDHasSuffix(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldHasSuffix(FieldAuthorizedByRequestID, v))
}

// AuthorizedByRequestIDEqualFold applies the EqualFold predicate on the "authorized_by_request_id" field.
func AuthorizedByRequestIDEqualFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEqualFold(FieldAuthorizedByRequestID, v))
}

// AuthorizedByRequestIDContainsFold applies the ContainsFold predicate on the "authorized_by_request_id" field.
func AuthorizedByRequestIDContainsFold(v string) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldContainsFold(FieldAuthorizedByRequestID, v))
}

// SubscribedEQ applies the EQ predicate on the "subscribed" field.
func SubscribedEQ(v bool) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldSubscribed, v))
}

// SubscribedNEQ applies the NEQ predicate on the "subscribed" field.
func SubscribedNEQ(v bool) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldSubscribed, v))
}

// VerboseEQ applies the EQ predicate on the "verbose" field.
func VerboseEQ(v bool) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldVerbose, v))
}

// VerboseNEQ applies the NEQ predicate on the "verbose" field.
func VerboseNEQ(v bool) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldVerbose, v))
}

// AuthorizedUnixEQ applies the EQ predicate on the "authorized_unix" field.
func AuthorizedUnixEQ(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldAuthorizedUnix, v))
}

// AuthorizedUnixNEQ applies the NEQ predicate on the "authorized_unix" field.
func AuthorizedUnixNEQ(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldAuthorizedUnix, v))
}

// AuthorizedUnixIn applies the In predicate on the "authorized_unix" field.
func AuthorizedUnixIn(vs ...int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldIn(FieldAuthorizedUnix, vs...))
}

// AuthorizedUnixNotIn applies the NotIn predicate on the "authorized_unix" field.
func AuthorizedUnixNotIn(vs ...int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNotIn(FieldAuthorizedUnix, vs...))
}

// AuthorizedUnixGT applies the GT predicate on the "authorized_unix" field.
func AuthorizedUnixGT(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGT(FieldAuthorizedUnix, v))
}

// AuthorizedUnixGTE applies the GTE predicate on the "authorized_unix" field.
func AuthorizedUnixGTE(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGTE(FieldAuthorizedUnix, v))
}

// AuthorizedUnixLT applies the LT predicate on the "authorized_unix" field.
func AuthorizedUnixLT(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLT(FieldAuthorizedUnix, v))
}

// AuthorizedUnixLTE applies the LTE predicate on the "authorized_unix" field.
func AuthorizedUnixLTE(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLTE(FieldAuthorizedUnix, v))
}

// SubscribedUnixEQ applies the EQ predicate on the "subscribed_unix" field.
func SubscribedUnixEQ(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldSubscribedUnix, v))
}

// SubscribedUnixNEQ applies the NEQ predicate on the "subscribed_unix" field.
func SubscribedUnixNEQ(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldSubscribedUnix, v))
}

// SubscribedUnixIn applies the In predicate on the "subscribed_unix" field.
func SubscribedUnixIn(vs ...int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldIn(FieldSubscribedUnix, vs...))
}

// SubscribedUnixNotIn applies the NotIn predicate on the "subscribed_unix" field.
func SubscribedUnixNotIn(vs ...int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNotIn(FieldSubscribedUnix, vs...))
}

// SubscribedUnixGT applies the GT predicate on the "subscribed_unix" field.
func SubscribedUnixGT(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGT(FieldSubscribedUnix, v))
}

// SubscribedUnixGTE applies the GTE predicate on the "subscribed_unix" field.
func SubscribedUnixGTE(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGTE(FieldSubscribedUnix, v))
}

// SubscribedUnixLT applies the LT predicate on the "subscribed_unix" field.
func SubscribedUnixLT(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLT(FieldSubscribedUnix, v))
}

// SubscribedUnixLTE applies the LTE predicate on the "subscribed_unix" field.
func SubscribedUnixLTE(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLTE(FieldSubscribedUnix, v))
}

// CreatedUnixEQ applies the EQ predicate on the "created_unix" field.
func CreatedUnixEQ(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldCreatedUnix, v))
}

// CreatedUnixNEQ applies the NEQ predicate on the "created_unix" field.
func CreatedUnixNEQ(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldCreatedUnix, v))
}

// CreatedUnixIn applies the In predicate on the "created_unix" field.
func CreatedUnixIn(vs ...int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldIn(FieldCreatedUnix, vs...))
}

// CreatedUnixNotIn applies the NotIn predicate on the "created_unix" field.
func CreatedUnixNotIn(vs ...int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNotIn(FieldCreatedUnix, vs...))
}

// CreatedUnixGT applies the GT predicate on the "created_unix" field.
func CreatedUnixGT(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGT(FieldCreatedUnix, v))
}

// CreatedUnixGTE applies the GTE predicate on the "created_unix" field.
func CreatedUnixGTE(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGTE(FieldCreatedUnix, v))
}

// CreatedUnixLT applies the LT predicate on the "created_unix" field.
func CreatedUnixLT(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLT(FieldCreatedUnix, v))
}

// CreatedUnixLTE applies the LTE predicate on the "created_unix" field.
func CreatedUnixLTE(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLTE(FieldCreatedUnix, v))
}

// UpdatedUnixEQ applies the EQ predicate on the "updated_unix" field.
func UpdatedUnixEQ(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldEQ(FieldUpdatedUnix, v))
}

// UpdatedUnixNEQ applies the NEQ predicate on the "updated_unix" field.
func UpdatedUnixNEQ(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNEQ(FieldUpdatedUnix, v))
}

// UpdatedUnixIn applies the In predicate on the "updated_unix" field.
func UpdatedUnixIn(vs ...int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldIn(FieldUpdatedUnix, vs...))
}

// UpdatedUnixNotIn applies the NotIn predicate on the "updated_unix" field.
func UpdatedUnixNotIn(vs ...int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldNotIn(FieldUpdatedUnix, vs...))
}

// UpdatedUnixGT applies the GT predicate on the "updated_unix" field.
func UpdatedUnixGT(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGT(FieldUpdatedUnix, v))
}

// UpdatedUnixGTE applies the GTE predicate on the "updated_unix" field.
func UpdatedUnixGTE(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldGTE(FieldUpdatedUnix, v))
}

// UpdatedUnixLT applies the LT predicate on the "updated_unix" field.
func UpdatedUnixLT(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLT(FieldUpdatedUnix, v))
}

// UpdatedUnixLTE applies the LTE predicate on the "updated_unix" field.
func UpdatedUnixLTE(v int64) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.FieldLTE(FieldUpdatedUnix, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IMChatSubscription) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IMChatSubscription) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IMChatSubscription) predicate.IMChatSubscription {
	return predicate.IMChatSubscription(sql.NotPredicates(p))
}
