// Code generated by ent, DO NOT EDIT.

package taskattempt

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the taskattempt type in the database.
	Label = "task_attempt"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldAttempt holds the string denoting the attempt field in the database.
	FieldAttempt = "attempt"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldAgentID holds the string denoting the agent_id field in the database.
	FieldAgentID = "agent_id"
	// FieldClaimLeaseID holds the string denoting the claim_lease_id field in the database.
	FieldClaimLeaseID = "claim_lease_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldOutputJSON holds the string denoting the output_json field in the database.
	FieldOutputJSON = "output_json"
	// FieldOutputDigest holds the string denoting the output_digest field in the database.
	FieldOutputDigest = "output_digest"
	// FieldOutputSignature holds the string denoting the output_signature field in the database.
	FieldOutputSignature = "output_signature"
	// FieldSignaturePublicKey holds the string denoting the signature_public_key field in the database.
	FieldSignaturePublicKey = "signature_public_key"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldClaimedUnix holds the string denoting the claimed_unix field in the database.
	FieldClaimedUnix = "claimed_unix"
	// FieldStartedUnix holds the string denoting the started_unix field in the database.
	FieldStartedUnix = "started_unix"
	// FieldCompletedUnix holds the string denoting the completed_unix field in the database.
	FieldCompletedUnix = "completed_unix"
	// FieldUpdatedUnix holds the string denoting the updated_unix field in the database.
	FieldUpdatedUnix = "updated_unix"
	// Table holds the table name of the taskattempt in the database.
	Table = "task_attempts"
)

// Columns holds all SQL columns for taskattempt fields.
var Columns = []string{
	FieldID,
	FieldTaskID,
	FieldAttempt,
	FieldRunID,
	FieldAgentID,
	FieldClaimLeaseID,
	FieldStatus,
	FieldOutputJSON,
	FieldOutputDigest,
	FieldOutputSignature,
	FieldSignaturePublicKey,
	FieldErrorMessage,
	FieldClaimedUnix,
	FieldStartedUnix,
	FieldCompletedUnix,
	FieldUpdatedUnix,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TaskIDValidator is a validator for the "task_id" field. It is called by the builders before save.
	TaskIDValidator func(string) error
	// DefaultAttempt holds the default value on creation for the "attempt" field.
	DefaultAttempt uint32
	// DefaultRunID holds the default value on creation for the "run_id" field.
	DefaultRunID string
	// DefaultAgentID holds the default value on creation for the "agent_id" field.
	DefaultAgentID string
	// DefaultClaimLeaseID holds the default value on creation for the "claim_lease_id" field.
	DefaultClaimLeaseID string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultOutputJSON holds the default value on creation for the "output_json" field.
	DefaultOutputJSON string
	// DefaultOutputDigest holds the default value on creation for the "output_digest" field.
	DefaultOutputDigest string
	// DefaultOutputSignature holds the default value on creation for the "output_signature" field.
	DefaultOutputSignature string
	// DefaultSignaturePublicKey holds the default value on creation for the "signature_public_key" field.
	DefaultSignaturePublicKey string
	// DefaultErrorMessage holds the default value on creation for the "error_message" field.
	DefaultErrorMessage string
	// DefaultClaimedUnix holds the default value on creation for the "claimed_unix" field.
	DefaultClaimedUnix int64
	// DefaultStartedUnix holds the default value on creation for the "started_unix" field.
	DefaultStartedUnix int64
	// DefaultCompletedUnix holds the default value on creation for the "completed_unix" field.
	DefaultCompletedUnix int64
	// DefaultUpdatedUnix holds the default value on creation for the "updated_unix" field.
	DefaultUpdatedUnix int64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the TaskAttempt queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByAttempt orders the results by the attempt field.
func ByAttempt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempt, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByAgentID orders the results by the agent_id field.
func ByAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentID, opts...).ToFunc()
}

// ByClaimLeaseID orders the results by the claim_lease_id field.
func ByClaimLeaseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimLeaseID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByOutputJSON orders the results by the output_json field.
func ByOutputJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputJSON, opts...).ToFunc()
}

// ByOutputDigest orders the results by the output_digest field.
func ByOutputDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputDigest, opts...).ToFunc()
}

// ByOutputSignature orders the results by the output_signature field.
func ByOutputSignature(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputSignature, opts...).ToFunc()
}

// BySignaturePublicKey orders the results by the signature_public_key field.
func BySignaturePublicKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSignaturePublicKey, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByClaimedUnix orders the results by the claimed_unix field.
func ByClaimedUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimedUnix, opts...).ToFunc()
}

// ByStartedUnix orders the results by the started_unix field.
func ByStartedUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedUnix, opts...).ToFunc()
}

// ByCompletedUnix orders the results by the completed_unix field.
func ByCompletedUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedUnix, opts...).ToFunc()
}

// ByUpdatedUnix orders the results by the updated_unix field.
func ByUpdatedUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedUnix, opts...).ToFunc()
}
